### ISSUE TITLE
Treat all files in the //-directory as original?

### ISSUE THREAD

**Issue by lliseil** [sahib/rmlint#104]
Hi, rmlint and sshfs are saving my ass after reorganizing some GB of data between computers. Now I've yet to find out how to tell rmlint to find duplicates in 'duplicateFolder' (ok)... keeping any duplicate in 'originalFolder' untouched if it can do that?

$ rmlint '//originalFolder' 'duplicateFolder'

    # Duplicate(s):
       ls temp/rep1/file3
       rm temp/rep1/file1		<< rmlint pliz keep any file in rep1 as it is
       rm temp/rep2/file2

Refs
* #29 
	"Future versions might treat all files in the //-directory as original."
* #45

**Comment by sahib** [comment]
Sure you can. 

Just use ```--keep-all-tagged```:

```
λ /tmp/ tree a b
a
├── x
└── y
b
├── x
└── y

0 directories, 4 files
λ /tmp/ rmlint a // b --keep-all-tagged                    

# Duplikate:
    ls /tmp/b/y
    ls /tmp/b/x
    rm /tmp/a/x
    rm /tmp/a/y

==> Insgesamt 4 dateien, von denen 2 Duplikate in 1 Gruppen sind.
==> Dies entspricht 4 B an Duplikaten die entfernt werden können.

Eine sh Datei wurde nach /tmp/rmlint.sh geschrieben.
```

Everything behind the ```//``` is recognized as original directory. You used the old ```rmlint 1.x.x``` syntax which is slightly... err... outdated.

You may want to look into ```--must-match-tagged``` which requires a duplicate to appear in both directories to be reported.

Considering those refs you gave: You are sure that you're using a recent version of ```rmlint? (>= 2.0.0)```

**Comment by lliseil** [comment]
Now you say it sahib...

    aur/rmlint-git 967.812a5d5-3 [installed: 1:2013.04.01-1] 
Woow seems I never updated rmlint-git ever since, as cower/yaourt lost its trace for some reason!
Now to adapt myself to the vast amount of changes and additional capabilities :)

BTW

    $ rmlint temp/dir2 // temp/dir1/ --keep-all-tagged --must-match-tagged

    # Doublon(s):
        ls /home/kozaki/temp/dir1/file1
        ls /home/kozaki/temp/dir1/file3
        rm /home/kozaki/temp/dir2/file2
Thanks
