### ISSUE TITLE
Unable to compile on Gentoo GNU/Linux

### ISSUE THREAD

**Issue by youknowwho** [sahib/rmlint#105]
Hello:

This looks like a great tool. Thank you for developing it.

I was trying to learn how to use it but I wasn't able to compile it. The error messages are returned below.

I am using a recent Linux kernel on a Gentoo GNU/Linux system. I am using Python 2.7:

#########################################
eselect python list
Available Python interpreters:
  [1]   python2.7 *
  [2]   python3.3
  [3]   python3.4
#########################################

It seems like it's trying to check my git revision. I am using version 2.0.5:
##################
git --version
git version 2.0.5
##################

Am I missing a dependency? Thank you for your help.

######################################################
scons config
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
AttributeError: 'module' object has no attribute 'check_output':
  File "/tmp/lmr/rmlint/SConstruct", line 448:
    conf.check_git_rev()
  File "/usr/lib64/python2.7/site-packages/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/tmp/lmr/rmlint/SConstruct", line 71:
    rev = subprocess.check_output('git log --pretty=format:"%h" -n 1', shell=True)
Checking for git revision... 
######################################################

######################################################
scons --prefix=/usr
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
AttributeError: 'module' object has no attribute 'check_output':
  File "/tmp/lmr/rmlint/SConstruct", line 448:
    conf.check_git_rev()
  File "/usr/lib64/python2.7/site-packages/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/tmp/lmr/rmlint/SConstruct", line 71:
    rev = subprocess.check_output('git log --pretty=format:"%h" -n 1', shell=True)
Checking for git revision... 
######################################################

Here is the config.log:

######################################################
file /tmp/lmr/rmlint/SConstruct,line 441:
        Configure(confdir = .sconf_temp)
scons: Configure: Checking whether the C compiler works
.sconf_temp/conftest_0.c <-
  |
  |int main()
  |{
  |    return 0;
  |}
  |
^[[94mCompiling ^[[95m==> ^[[93m.sconf_temp/conftest_0.c^[[0m
scons: Configure: yes

scons: Configure: Checking for git revision...
#####################################################

**Comment by sahib** [comment]
Hi,

This is a bit weird. ```subrocess.check_output``` should be there in Py27.
Do you get the same error message when issuing ```python2 -c 'import subprocess; subprocess.check_output'```?

The git version is not important here, since it doesn't even get so far.  
Maybe your installation is somewhat outdated/broken?

**Comment by esseks** [comment]
Also make sure you are actually import Python's `subprocess.py` and you don't have a file with such name in `PYTHONPATH`.

**Comment by youknowwho** [comment]
Hello Sahib,

Thank you for the advice. I thought it was a bit weird also because i have never had a problem using scons. Entering "python2 -c 'import subprocess; subprocess.check_output'" on the command line produces an empty result, but opening a python shell produces a hex string when I enter the commands:


###############################################
$ python2 -c 'import subprocess; subprocess.check_output'
[returns shell prompt]
###############################################

For the python interpreter shell:
###############################################
python2
Python 2.7.9 (default, Dec 28 2014, 18:18:21) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.check_output
<function check_output at 0x7ff007fb2b90>
>>> quit()
###############################################

So does that help us? Should it also definitely return something on the shell command line also?

Oddly enough, I just compiled two other lengthy programs that use scons, including ioDoom3 and GTKRadiant. Both compiled up successfully.

Thank you again for your thoughts on it.

**Comment by youknowwho** [comment]
Hi Esseks,

So I didn't have a pythonpath variable set. If I set it to /usr/lib64/python2.7, I still get the same result. 

echo $PYTHONPATH
/usr/lib64/python2.7/
$ scons config
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
AttributeError: 'module' object has no attribute 'check_output':
  File "/tmp/lmr/rmlint/SConstruct", line 448:
    conf.check_git_rev()
  File "/usr/lib64/python2.7/site-packages/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/tmp/lmr/rmlint/SConstruct", line 71:
    rev = subprocess.check_output('git log --pretty=format:"%h" -n 1', shell=True)


Thank you again for your thoughts.

**Comment by esseks** [comment]
Again, just a thought, try changing the shebang in `SConstruct` from `/usr/bin/env python` to `/usr/bin/python2`. I am not very familiar with Gentoo, but it might just be that `python` is a symlink to a wrong version of Python.

**Comment by youknowwho** [comment]
Hi esseks,

Thank you for the idea and your advice. If I enter just a flat "python" on the command line, I end up in the python2 shell. But I still wanted to try your idea, so I did:

############################################################
$ scons config
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
AttributeError: 'module' object has no attribute 'check_output':
  File "/tmp/lmr/rmlint/SConstruct", line 448:
    conf.check_git_rev()
  File "/usr/lib64/python2.7/site-packages/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/tmp/lmr/rmlint/SConstruct", line 71:
    rev = subprocess.check_output('git log --pretty=format:"%h" -n 1', shell=True)
Checking for git revision... 
$ grep python2.7 SConstruct 
#!/usr/bin/env python2.7
############################################################

I am pretty puzzled by this because I have never had an issue with using scons.

Thank you again for your thoughts and ideas. If you can think of anything else then please don't hesitate to let me know.

**Comment by youknowwho** [comment]
Hi Folks:

I found the problem. I entered the accept keyword for the scons package [/etc/portage/package.accept_keywords]:

#################################################
#TRYING LATEST VERSION OF SCONS FOR COMPILE PROBLEM WITH RMLINT.
dev-util/scons ~amd64
#################################################

In short, what this does is installs the latest version of scons. I had version 2.3.0 installed before, and this change installed version 2.3.4, which corrected the problem.

Many kind thanks. This looks like an excellent program! I will certainly give it my regard after testing it.

Thank you again for your thoughts and your help.

Best regards,

YouKnowWho

**Comment by youknowwho** [comment]
I wanted to write a follow up message.
This tool is FAST! And you should know that it's FAST! And just in case you thought the developers were kidding, you can be assured that they were NOT kidding, and you should know that this tool is FAST.
May kind thanks to the developers who are working on this project. This is a great tool and I wanted to thank the developers and maintainers who are working on this project.
Kind thanks again for your work!

Best Regards,

You_Know_Who

**Comment by sahib** [comment]
Thanks, glad you like it :smiley: 

A short note: a new version (*2.2.0 Dreary Dropbbear*) will be released in a few days. It will contain some new optimisation, making it even faster (no kidding this time either) and greatly reduced memory footprint. You can even try it out right now in the sahib/develop branch. You can also watch the changes in the [Changelog](https://github.com/sahib/rmlint/blob/develop/CHANGELOG.md).

Remember: You can always help out by writing/fixing documentation, testing or translating!
