### ISSUE TITLE
Dockerise rmlint

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#106]
Anyone interested in creating a DockerFile for rmlint, primarily for testing purposes?

**Comment by sahib** [comment]
Easy enough...

```
$ git pull && git checkout docker
$ cd pkg/docker
$ docker build -t sahib/rmlint .  # get a coffee or two.
$ docker run -i -t sahib/rmlint
> rmlint --version
```

It's based on ArchLinux.

**Comment by esseks** [comment]
Dockerizing rmlint is fun for fiddling with Docker, but aren't we taking it a bit too far? I mean, it's a 200kB application with few, stable and reliable dependencies, not a multi-tiered, 200-pound Java application.

**Comment by sahib** [comment]
Or fiddling with rmlint inside of that when trying out the sh script or similar stuff. 
I would never upload the container or use it as distribution media though.
