### ISSUE TITLE
Request: Quote/clean filenames for unusual chararacters, windows filenames (spaces etc)

### ISSUE THREAD

**Issue by timoc** [sahib/rmlint#107]
If i run rmlint on a filesystem that has windows filenames in it and create a shell script, it breaks because the filenames are not quoted properly.

It would also be nice to be able to do bulk filename replace/rename to remove unusual characters from the whole filesystem.

**Comment by sahib** [comment]
There's some info missing.

- What do you mean by broken?
- Can you give an example of a broken filename?
- What would you define as correct quoting of it?
- Which version did you use?
- Did you check if the bug persists in the develop branch?

Modifying filenames in bulk should be more easily done via ```find / iconv / mv / etc.```
That's not rmlint's job (which is rather for deleting or stripping stuff, therefore *rm*lint)

**Comment by timoc** [comment]
my rmlint is pretty recent, so i have not checked devel.
version 2.0.0 compiled: Feb 27 2015 at [18:03:41] "Personable Pidgeon" (rev 35b8b87)
compiled with: -mounts -nonstripped +fiemap +sha512 +bigfiles +intl 

1- Broken behaviour
With the duplicate filename "Hello Kitty.txt", rmlint generates unquoted filenames.
```
rm Hello Kitty.txt
ls Hello Kitty.txt
```
it should be quoted as per (ba)sh filename quoting rules.
```
rm "Hello Kitty.txt"
ls "Hello Kitty.txt"
```
or
```
rm Hello\ Kitty.txt
ls Hello\ Kitty.txt
```

The filename feature i mentioned is to delete/strip linty stuff from *filenames* in the lint search tree (which requires rename/mv) therefore i believe also _rmlint_. 

rmlint reads all the filenames in a filesystem tree as part of the lint search. This feature would be to allow me to match (regexp) filenames with embedded unicode, or beginning with spaces, containing spaces, and all sorts of other non standard filename annoyances. rmlint could then add them commented out/or prefixed with ls, to the lint script you generate as those meeting the lint criteria, so that i can manually deal with them once and in one place.

**Comment by sahib** [comment]
Regarding 1:

Uh. I have to ask this: We are talking about the pretty printed output rmlint prints on stdout?
Spaces and quotes should be escaped in the script - at least I checked in ```master``` and ```develop```.

Copy&Paste from both:

```
master:

echo  '/tmp/H a b' # original
rm -f '/tmp/H x d' # duplicate
```

```
develop:

echo 'Keeping: ' '/tmp/H a b' # original
remove_cmd '/tmp/H x d' # == /tmp/H a b # duplicate
```

Also as a general note: Please also test always ```develop``` to see if the broken behavior persists.

Regarding 2:

I don't believe rmlint would be a good interface for this. As mentioned above, there is ```iconv(1)``` and ```find(1)``` which should do the job with a tiny bit of work quite well.

rmlint would just duplicate the interface to these both, which doesn't apply well to the unix philosophy in my opinion.

Also: Some people even *want* (well, not me) to have different encodings in their filesystem.

Regarding regular expressions: (Very) Old versions had a feature for limiting the search by a inclusion or exclusion regex. I removed this for the same reasons, since you can always do ```find -type f -iname '*.jpg' | rmlint -``` (or put a ```grep``` in between for an actual regex).

**Comment by timoc** [comment]
Regarding 1- 
You're right, i am wrong. i was piping stdout through grep -v to exclude some dupe matches from the script.

Regarding 2-
I'm not looking for find functionality, I'm not looking for rmlint to process the file contents in any way. i'm looking for something like fslint's "bad filename" feature, where i can specify the bad filename with a glob/regexp or similar. rmlint would then create a line in the script like:
```
echo "Badfile: <badfilename>
# rm "<quoted bad-filename>"
```
or 
```
echo "Badfile: <badfilename>
# mv "<quoted bad-filename>" "<quoted bad-filename>"
```
This is almost the opposite feature of point 1.

**Comment by sahib** [comment]
Regarding 2:

I didn't mean to use ``iconv(1)`` for changing the file's encoding, but rather to do something like this:

    # fix path encoding, assuming it came from windows.
    mv $filename $(echo "$filename" | iconv -f latin1 -t utf8)   

``fslint`` is just doing a find and filters files with invalid encoding (!utf-8):

https://github.com/pixelb/fslint/blob/master/fslint/findu8

If you're saying you want to check if a filename is bad by a regex, you want to check for certain characters that you usually don't expect in filenames? I guess you will have a hard time checking for invalid path encoding with a regex if you want that additionally.

The only point ```rmlint``` can do here for you, is quoting and inserting the filename into a uniform script. Apart from that it would just limit the user by hiding the finding between tons of other options and weird ways of specifying what to do with the command. Additionally this makes ``rmlint`` (even) bigger, which I'd like to avoid.

If you really want to inject those bad filenames into the other lint handling you can always the hackable python script that comes along with it:

    $ rmlint -o py:file.py
    $ # add more json entries to ./.rmlint.json with new type "bad_filename"
    $ # add new type and handling to file.py
    $ python file.py

I can't see right now what you could with ``rmlint``, what you couldn't do with normal unix tools.
If you don't come up with something breath-taking I feel inclined to close this issue. :smirk:

**Comment by timoc** [comment]
IMHO Unix tooling is to do one thing and do it well.  I guess I'm just missing what you consider rmlint vs unix tools is  good for or not. I mean the lint features in rmlint can also be managed by oneliner scripts etc. e.g. 
```
# find duplicate files in a tree based on hash
md5deep -r * | uniq -Dw15 | awk '{print "rm "$2} > myfile.sh
# find empty directories.
find . -empty -print0 | xargs -0 echo > myfile.sh
```
The greatest thing about rmlint for me, is the "No interactivity." This is the thing it does so well. It is that it does the hard work using all the best practice that i normally have to do by hand when "grooming" folders on multiple filesystems. 

My usual best practice is:
```
- Create find command(s) (like above) to do things like rmlint and pipe output to file.
- process the file with an editor, and add processing commands such as move. delete etc.
- run script
- repeat until done.
```
The limitation i'm trying to address is that it only finds files it thinks are interesting when generating the script. Not breathtaking, just about expanding the feature that i think makes rmlint unique and valuable.

**Comment by sahib** [comment]
Im still rather wondering what your feature would actually do. 

Assume rmlint would have this feature, how would the usage look like? 
How does it handle the problem of "I don't know what do with a bad filename" (which is very user-defined?)

**Comment by timoc** [comment]
Of course this rmlint feature can be used for creating ad hock maintenance type scripts, but I'll give two grooming use cases, where i would normally have to do this kind of thing by hand, and rmlint would save me a heap of time.

Groom my mp3's in a podcast folder of a podcast archive that does not have a standardised episode format. Mark for processing every filename that does not have the new EPxx prefix.
```
# normal lint search plus mark as bad for processing only mp3s that do not start with EP01_
rmlint -b .mp3 -good "EP[0-9][0-9]_.*" -exec "mv -i $$ $$"
# generates an example bad, where bad does not meet regexp.
echo "exec: badfile.mp3"
mv -i "badfile.mp3" "badfile.mp3"
```

Groom a set of source files that have camel case/upper case, and grep the source for the occurrence of the original camel case. 
```
# normal lint search plus mark as bad for processing only files that contain upper case characters
# plus grep files to see if camel case version is included somewhere else
rmlint -bad "*[A-Z]*" -exec "mv -fb $$ $$; grep -e '#include' *.[CcHh]; grep $$"
# generates an example bad, where bad meets regexp.
echo "exec: Bad File.c"
mv -fb "Bad File.c" "Bad File.c"; grep -e '#include' *.[CcHh]; grep "Bad File.c"
```

I used bash but it could just as easily be python, where $$ is replaced by the quoted filename.

**Comment by sahib** [comment]
Do you notice the similarity to ```find``` in this example?
The only difference is, ```find``` does not generate a script output. 

This is where our opinions start to differ. Your request is very specific and could be implemented on your side by writing a wrapper that extends rmlint's json output. This output can be read in by the 
python script that comes with rmlint or one that is derived from it. That's why we have this thing: To make such rather rare usecases possible.  

Implementing your idea would also add some more problems:

- Are bad files included in the lint search? Do they take precedence over other lint types?
- Doesn't delete any content. Like the ``rm`` in ``rmlint`` is supposed to.
  (Note taken that you have a different view here.)
- I consider passing embedded shell commands to be somewhat impractical (Okay, we have ```-c sh:cmd```).

All in all there are too many problems for me. Sorry, closing therefore.
