### ISSUE TITLE
The progress bar is not working right

### ISSUE THREAD

**Issue by vvs-** [sahib/rmlint#111]
Hmm...
Still no luck here. No warnings this time, but no duplicates either. The interesting part is that without progressbar it finds the duplicate. Also, with `-o fdupes` it shows progress bar without duplicates but outputs the right pretty output and summary in the end. Something is not working in progress bar code. It's cosmetic but without progress bar the scanning of millions of files is not fun :disappointed:

**Comment by sahib** [comment]
Fixed as of 50d9ac8472c2b0e9f0433240b8fcc173f8ee6d8c. It updates the progressbar now at the end of the duplicate file finding phase (internally called shreddering). The progressbar worked, just the last bit did not update correctly.

**Comment by vvs-** [comment]
Thanks!

You might want to fix traversing as well. Or maybe it's another bug because the output of traversing stage is different in `develop` and `sqlite-hash-table`.

**Comment by sahib** [comment]
True, that one broke due to the caching work. Should be as beautiful as before now: 1607e73187fada7a4325595988392df3e1a5adde.

**Comment by vvs-** [comment]
I confirm, it works now.
