### ISSUE TITLE
Feature: When traversing, show progress of number of RmFiles created

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#112]
More of an enhancement than a feature...
At the moment we show progress in terms of number of files found by the traverser.  With very large data sets (>1M files), there is a significant lag at the end of traversing, I think while the RmFile creation queue catches up.  In extreme cases (8M files) this leads to rmlint stalling for >5 minutes, during which it would be nice to see some sort of progress indicator.

**Comment by sahib** [comment]
Should be an easy fix if I understood you correctly: 73810c05b0e062ef5fcf2ef1469902b22e996051.

**Comment by SeeSpotRun** [comment]
Actually the delay I was seeing turned out to be something out of our control (see https://git.gnome.org/browse/glib/tree/glib/ghash.c#n257 and https://git.gnome.org/browse/glib/tree/glib/ghash.c#n585) but https://github.com/sahib/rmlint/commit/73810c05b0e062ef5fcf2ef1469902b22e996051 looks worthwhile anyway,

**Comment by SeeSpotRun** [comment]
Along similar lines to this, there is probably a need for shred pre-processing to report its progress.  In particular, fiemap lookup can take a long time.

**Comment by sahib** [comment]
Should be better with eb441084a5b0841f70a398022c9dd56fc3babab0.
Didn't test it yet, since I don't have a rotational disk in my laptop.

**Comment by sahib** [comment]
Tried it out and actually fixed it: a84b4d7f47726c726cb857c71cfa9c7e821992f4.

**Comment by SeeSpotRun** [comment]
Thanks.
Was thinking about an extra progressbar between preprocessing and shredding for "Mapping file fragments".  But let's wait and see where https://github.com/sahib/rmlint/issues/120 gets to first...

**Comment by sahib** [comment]
I guess most user would be slightly confused by this since the apparent difference between post-traverse-preprocessing and pre-shredder-preprocessing might not be very clear. 
However Im okay with swapping *"reducing files to %d"* to *"fiemap'd %f files"* at that stage.

**Comment by sahib** [comment]
32b13bd1175f2de4aea09c9f16245a14f06f9b2e should be more like it?

**Comment by SeeSpotRun** [comment]
Fabulous!
