### ISSUE TITLE
--basename is slow

### ISSUE THREAD

**Issue by vvs-** [sahib/rmlint#116]
Try `mkdir 1; cd 1; seq 5000 | xargs truncate -s 1; cd ..` and then `rmlint 1 -T df -b -o progressbar -o summary`. This is on `develop` branch.

**Comment by sahib** [comment]
This should be a bit better since 46cb002020d3b1a39f506b3a7239ce0a58472805. It will be still slow with ```--with-metadata-cache``` But that's rather by the nature of this option. Maybe we should add a warning to the option description...

**Comment by vvs-** [comment]
It's faster now but it didn't find any duplicates.

**Comment by sahib** [comment]
I believe that the file in your testset have all different basenames, so that would be correct. Or does it also fail to find them without ```-b```?

**Comment by vvs-** [comment]
Sorry, disregard that. I think that was my inertia :blush:

**Comment by sahib** [comment]
I added a word of warning to ```--with-metadata-cache``` in the manpage.
I guess this can be closed now.

**Comment by SeeSpotRun** [comment]
Your test case actually inadvertently creates 5000 hash table collisions, 1 for each file with same size but different basename.  A fix is at https://github.com/SeeSpotRun/rmlint/commit/aa0de0f1363c07fc95d5ab770227505712558de1.

**Comment by vvs-** [comment]
For the record, `-T df -b -pp -without-fiemap` ran for 8h 6m, i.e. about 17% faster. It found 3017736 duplicates of 1297678 originals, which occupy 484.77 GB.
