### ISSUE TITLE
Should --keep-all-tagged option also protect "other lint" in tagged dirs?

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#122]
For discussion;
The title pretty much says it all.  Currently, IIRC, rmlint will still flag "other lint" in tagged paths for deletion.

**Comment by sahib** [comment]
+1. Current behaviour may not be totally invalid, but is not following the principle of least surprise.

**Comment by sahib** [comment]
I think that's fixed by d5531b3e6f1ccbbd675f439e9ed406cc08e32fc1.
