### ISSUE TITLE
sh/py formatter: add sanity checks before destructive operations

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#125]
This is daniels idea and this issue is for tracking the progress of it.

Sanity checks would include:

1. Original file still exists.
2. If duplicate has same dev/node as original then check via stat that hardlink count > 1
3. Have a paranoid option to cmp the original and duplicate before deleting

1-2 would be enabled by default; 3 is more expensive and might need a ``--config`` option.

**Comment by SeeSpotRun** [comment]
Initial sh commit at https://github.com/SeeSpotRun/rmlint/commit/4793d0e4ac9f777de14f8fa60cc8404f5d5d841e

**Comment by sahib** [comment]
Points 2. and 3. should be done as of:

8c58d402b700b8cc1b5040be95d7ce92e079bf1e
