### ISSUE TITLE
Make output sortable by size, mtime, abc.

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#126]
Sometimes it's nice to know which files are the biggest sizesuckers. We have ``--sortcriteria`` but that sorts the groups (Argh, should have been named ``--groupby``).

The new ``--sort`` (name is to discussion) would take a similar string like *smA* to sort, in this case, by size, mtime and reverse alphabetically. This would require shredder to hold back duplicates back like it's done with ``-D`` currently. Maybe the cleanup logic needs a bit, well, cleanup here. A general "hold back all RmFiles" mechanism would be useful here.

This might be especially useful with ``--replay`` and ``--size``.

**Comment by SeeSpotRun** [comment]
Nice idea.
Regarding --sortcriteria, I don't think --groupby is appropriate either;should probably have been --rank-by.

**Comment by sahib** [comment]
Mostly done in https://github.com/sahib/rmlint/tree/feature-rankby.

**Comment by sahib** [comment]
* ``-S / --sortcriteria`` was renamed to ``-S / --rank-by`` (unfortunate, but well).
* ``-y / --sort-by`` was introduced.
