### ISSUE TITLE
Additional --sortcriteria

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#128]
I'm thinking --sortcriteria=l (keep shortest basename) or =L (keep longest basename) would address cases like http://unix.stackexchange.com/questions/201761/search-and-delete-duplicate-files-with-different-names.
Any others?
P.S. also, as per https://github.com/sahib/rmlint/issues/126, would be nice to migrate to -R, --rank-by.

**Comment by sahib** [comment]
Introduced `-l/-L` as well as `-d/-D` for the path depth.
The latter is useful if you tend to put your backups somewhere deep.

(7b52671281c72afb92fc9a0b3d7f137f10ebd95a)
