### ISSUE TITLE
Request: Broken UID/GID permissions

### ISSUE THREAD

**Issue by nogweii** [sahib/rmlint#13]
I have ran into the issue before (mostly in recovery situations, or with tarball backups with incorrect options when I created or unpacked it).

The UID or GID for a file is set to one that existed on the old system but doesn't point to a real user account on the new one. One situation I can think of is when moving from an Ubuntu to a CentOS box - Ubuntu starts at UID 1000, CentOS starts at 500.

Thanks otherwise!

**Comment by bphd** [comment]
> Added feature to find BadIDs (it's enabled by default, use --no-badids to disable) in [a26a63e](https://github.com/sahib/rmlint/commit/a26a63e8268de1e51f4daceaeda420bf38530a5e) I changed the default command to `chown $(whoami):$(id -gn)`, this is not perfect, but suitable for quite some cases.
> 
> Using the uid/gid of the parent directory would be nicer, I will remember this for the rewrite.

`ERROR: Unknown option --no-badids.`

**Comment by cebtenzzre** [comment]
> ERROR: Unknown option --no-badids.

Do you realize that this thread is nearly ten years old? Read the manpage, it mentions that you can use something like `-T "defaults -badids"` to disable the badids lint type.

**Comment by bphd** [comment]
> > ERROR: Unknown option --no-badids.
> 
> Do you realize that this thread is nearly ten years old? Read the manpage, it mentions that you can use something like `-T "defaults -badids"` to disable the badids lint type.

Haven't found any meaningful way of finding that function in manual as it's badly referenced

**Comment by bphd** [comment]
> > Haven't found any meaningful way of finding that function in manual as it's badly referenced
> 
> https://rmlint.readthedocs.io/en/master/rmlint.1.html#general-options

Never been ever to that website in my life, in Linux world manuals are managed by `man`

**Comment by cebtenzzre** [comment]
> Never been ever to that website in my life, in Linux world manuals are managed by `man`

Yes, you can of course run `man rmlint` as well, I just didn't want to make any assumptions about your installation.

**Comment by bphd** [comment]
> > Never been ever to that website in my life, in Linux world manuals are managed by `man`
> 
> Yes, you can of course run `man rmlint` as well, I just didn't want to make any assumptions about your installation.

How did you even DARED assuming that I have an internet access where I actually read and communicate with you from the future just by reading archives from what has been now deseased internet? (oh, and sorry for the spoiler, but, guys, it was pretty obvious, the stats were clears, we were sprinting right towards the ecological wall. Though, it's not so bad, on some points I mean. Like it's way much calmer, slower, and we have those archives for giggles and such, but, yeah, anyway)
