### ISSUE TITLE
Support outputting original files list

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#135]
Currently we only output original file names if they have a duplicate.  There are cases where it may be useful to get a list of all unique files, not just those with duplicates, for example when backing up a volume which contains many duplicates, particularly reflinks.

**Comment by sahib** [comment]
Isn't this basically what ``-U / --write-unfinished`` does? Well, that is only included in the json output...

**Comment by SeeSpotRun** [comment]
Pretty much, although it misses any files removed during proprocessing (eg any "other lint").  So yes `rmlint -T df --write-unfinished` does what I was looking for.  Then a small job to write a python script to do a "rmsync" ie:
* Copy originals to destination
* For duplicate files, create copies in destination which are [hard|sym|ref]-linked copies of new original in the destination.

But looking at the rsync manpages, there are already options --safe-links and --hard-links which achieve similar functionality.  Just run rmlint with `-c sh:link` first, then run rsync with `--safe-links --hard-links`.  And for reflink copies there is `btrfs send`.

I think we can close this one.
