### ISSUE TITLE
Failures if filenames contain soaces

### ISSUE THREAD

**Issue by tonywhelan** [sahib/rmlint#140]
Hi there, I just compiled rmlint on my Linux Mint 17.2 machine and ran a test on a folder full of files. It certainly is fast! But when I tried to execute the rmlint.sh script that the utility produced, I got some errors that said "Error: duplicate has disappeared - cancelling...."

Buthe duplicates had NOT disappeared. I can see that this error only occurred when the filename/path contained a space character. This is caused by not having double-quote marks around the variable names $1 and $2 in the line  < if original_check $1 $2; then > which occurs in functions cp_hardlink, cp_symlink, cp_reflink, remove_cmd,  

So the rmlint program needs to generate the shell script with double quotes in those places.

cheers

PS apology for typo in issue name - should say "spaces" not "soaces'
PPS I haven't the foggiest idea where to look to find the code and create a patch ... otherwise I would have.

**Comment by sahib** [comment]
You're absolutely right, I keep making this mistake.

This should be hopefully fixed as of 478f250e51258bfdfbc70d294f1833d41c01126a in the `develop` branch. I suppose you're using the `develop` branch, since this feature is not yet available in `master`.

Thanks for bringing this to my attention.

**Comment by tonywhelan** [comment]
Hi Chris, that was a quick reply!

The command I used was "git clone -b develop 
https://github.com/sahib/rmlint.git" so yes that was the develop branch.

I'm not very familiar with git and have no idea about programming in c 
... I stick to simple bash stuff. But looking at your fix link below, I 
now see that the code is generated in lib/formats/sh.sh which is pretty 
straightforward .. but I would never have found that bit of code without 
some guidance!

I have been collecting photos and certificates for family history for 20 
years and there are duplicate files all over the place on my disk, so 
this utility will be a great help to me.

Tony
Canberra, AUS

**Comment by tonywhelan** [comment]
I just rebuilt the utility with the above changes and its all good. Many thanks.  
PS Don't you sleep? It must be 1.30am in Germany!

**Comment by sahib** [comment]
Glad to help.

Yes, you're using the `develop` branch.
You should be aware that it breaks from time to time. `master` is where the stable software lives.

If there are directories that have been copied, you might like the ``-D`` option.
Also regarding git: I recommend learning it. It's very useful for other things than code too.

P.S: I got some sleep now. I need it once in a few weeks.
