### ISSUE TITLE
Remap root symlinks

### ISSUE THREAD

**Issue by h6w** [sahib/rmlint#144]
I apologise if this is outside rmlint's scope.

I have a use case where I have a copy of each disk in a RAID-1 set obtained using rsync and I'm trying to find discrepancies between them.  rsync's options copy the symlinks verbatim.  This is fine when a symlink is relative, however when the symlink is absolute, rmlink sees the symlink as pointing nowhere, and it's default option is to delete it.  This is technically correct, but not my desired outcome.

I have already tried building a script that searches for these symlinks and prefixes the new root, but things go wrong easily.  I think it would be much nicer if we could tell rmlint a new "fake root" location which it then uses for symlink lookups and avoids deleting the file.  We may have to do this separately for each path, since my two copies would have different fake roots.

Further, we could have a '--fix-symlinks' option which would remap the symlink to the new root (or change it to a relative symlink) in the situation where that would result in it pointing to a correct file.

**Comment by sahib** [comment]
Hello h6w. 

Im not yet sure what goal you are ultimatively striving for. 
If you just want to preserve the symbolic you could disable the "bad link" feature by ``-T all,-badlinks`` (or shorter ``-T all,-bl``). The symbolic link options (``-f / -F / -@``) might give some more fine-grained control what to do with them afterwards. You could for example completely ignore them and handle them separately with your own script + ``find``.

Maybe a valid approach would be to convert the absolute symbolic links to relative ones beforehand?

Im not very positive that rmlint is the right tool to handle that special case (also it might be quite bit of code needed to handle that and we have already quite eery symlink-code partly).

**Comment by SeeSpotRun** [comment]
Ideally rsync would have a --remap-symlinks option.  This has been suggested before on various forums but the standard response is "rsync has too many options already".

For fixing it up, I agree a script is a better option ("rmlint has too many options already too").

Try this one:
```
#!/bin/bash

display_usage() {
    echo Usage:
    echo "    $0 ABS_PATH ORIG_ABS_PATH"
    echo "    Finds symlinks under ABS_PATH which point to absolute paths within ORIG_ABS_PATH, and"
    echo "    re-maps them to the correspong path under ABS_PATH"
}

remap_symlinks() {
    abs_path="$1"
    orig_abs_path="$2"
    # use newline separator so we can handle paths with spaces
    local IFS=$(echo -e '\n')

    # find symlinks
    find "$abs_path" -type l -printf "%p\n%l\n" | while read symlink; do
        read target
        if [ ${target:0:1} == "/" ] ; then   # it's an absolute symlink
            new_target=${target/$orig_abs_path/$abs_path}
            if [ "$target" != "$new_target" ] ; then
                if [ -e "$new_target" ] ; then

                    # DRY RUN:
                    echo "rm '$symlink' && ln -s '$new_target' '$symlink'"

                    # UNCOMMENT THIS FOR REAL VERSION:
                    # rm $symlink && ln -s $new_target $symlink

                else

                    echo "# Warning: can't find target $new_target for $symlink; skipping"
                    echo "# (original target was $target)"

                fi
            fi
        fi
    done
}


if [  $# -ne 2 ] || [ ${1:0:1} != "/" ] || [ ${2:0:1} != "/" ] ; then
    display_usage
    exit 1
fi

remap_symlinks $1 $2
```

Note that as-is it does nothing; you can either pipe the output to another shell script to execute later (recommended), or if you are feeling bold you can uncomment the line:
```
           rm $symlink && ln -s $new_target $symlink
```

**Comment by SeeSpotRun** [comment]
Just to be clear on the above, the recommended workflow (assuming you save the above script as rebase.sh) is:
1. ```$ ./rebase.sh /path/to/backup /path/to/originals > fix_links.sh```
2. Review contents of fix_links.sh to check it look like it will do what it expected, and won't eat your cat
3. ``` $ chmod +x fix_links.sh```
4. ```$ ./fix_links.sh```
5. ```$ rm fix_links.sh```

**Comment by sahib** [comment]
Im closing this now, @h6w can still comment if he likes to.
