### ISSUE TITLE
Seldom crash on g_mutex_clear()

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#145]
Running the testsuite with...
```bash
$ RM_TS_USE_GDB=1 RM_TS_PRINT_CMD=1 RM_TS_PEDANTIC=1 nosetests -s -x tests/test_options/test_replay.py
```
... I noticed a crash that raises from an assertion (``g_mutex_clear on unitinitialised or already locked mutex``). It is pretty rare (and thus only shows with pedantic tests) and might happen on no specific command. It comes from this line:

https://github.com/sahib/rmlint/blob/develop/lib/checksum.c#L90

Since the mutex seems to be properly initialized, it appears we 
still wait in ``rm_buffer_pool_get()`` or similar somewhere else. 
A backtrace showed that another thread is still in ``rm_hasher_hashpipe_worker()`` 
when ``rm_hasher_free()`` was called - probably a bit weird.
I tried to fix it by making ``rm_buffer_pool_destroy()`` wait until all buffers are returned,
 but my fix was stupid and won't work with paranoia probably. I reverted it already.

**Comment by SeeSpotRun** [comment]
I wasn't able to reproduce the crash but hopefully https://github.com/SeeSpotRun/rmlint/commit/225d71f2862967f4a9bf96dab6d8765e33e9f621 fixes this...

**Comment by SeeSpotRun** [comment]
Hopefully this is fixed now - with hindsight it could probably have been fixed by moving one line (https://github.com/sahib/rmlint/commit/31cd32f1d41d1721a02b047f6b22518562836633#commitcomment-13455516) but hopefully #149 fixes a few other things, as well as making shredder a bit more modular.
