### ISSUE TITLE
Inconsistencies with `-x` option

### ISSUE THREAD

**Issue by phiresky** [sahib/rmlint#151]
According to the manual:

> `-x --crossdev` (default) / `-X --no-crossdev:`
 	
> Do cross over mount points (-x)? Or stay always on the same device (-X)?

But when I add the option `-x`, it stops searching cross device boundaries, and `-X` enables it. So it does the exact opposite.

Additionally, the gentle guide says `it will delete itself after it ran, except you passed the -x switch.`

**Comment by sahib** [comment]
Thanks @phiresky, should be fixed by 3b00b889140655f701fc69e1d84635f3411d468c.
``-X`` will make ``rmlint`` stop on mountpoints. The line you posted from the gentle guide refers to the option ``-x`` that you pass to the generated ``sh`` script. I added a tiny bit of explanation to that.

**Comment by sahib** [comment]
Note: As of 162976e49ad3f714b874cb3f325126c9c8024d35 ``-x`` is the "do not cross mountpoints" option (which was the original thought). It was switched to be consistent with most other utilities that use ``-x`` for this (like e.g. ``tree``).
