### ISSUE TITLE
With rmlint 2.4.0 (rev 86388d0), GUI is missing

### ISSUE THREAD

**Issue by emk2203** [sahib/rmlint#153]
After compilation of rmlint 2.4.0 (rev86388d0), a `rmlint --gui` yields `/usr/bin/python3: No module named shredder`

Environment info: Ubuntu 15.10 64-bit

After compilation on the Raspberry Pi 2, the last line before writing the list of installed files was `package init file 'shredder/views/__init__.py' not found (or not a regular file)`. Might be the problem on Ubuntu as well.

```
rmlint will be compiled with the following features:

    Find non-stripped binaries (needs libelf)             : yes
    Optimize using ioctl(FS_IOC_FIEMAP) (needs linux)     : yes
    Support for SHA512 (needs glib >= 2.31)               : yes
    Support for SSE4.2 instructions for fast CityHash     : yes
    Support for swapping metadata to disk (needs SQLite3) : yes
    Build manpage from docs/rmlint.1.rst                  : yes, using /usr/bin/sphinx-build
    Support for caching checksums in file's xattr         : yes
    Support for reading json caches (needs json-glib)     : yes
    Checking for proper support of big files >= 4GB       : yes
        (needs either sizeof(off_t) >= 8 ...)             : yes
        (... or presence of stat64)                       : yes

    Optimize non-rotational disks                         : yes
        (needs libblkid for resolving dev_t to path)      : yes
        (needs gio-unix-2.0)                              : yes

    Enable gettext localization                           : yes
        (needs <locale.h> for compile side support)       : yes
        (needs msgfmt to compile .po files)               : yes

The following constants will be used during the build:

    Version information  : 2.4.0 "Myopic Micrathene" (rev 86388d0)
    Compiler             : gcc
    Install prefix       : /usr/local
    Actual prefix        : /usr/local
    Verbose building     : no
    Adding debug symbols : no
```

**Comment by sahib** [comment]
I believe that's not a failure on ``rmlint``'s end. Ubuntu does not include ``site-packages`` in ``sys.path`` (try ``python3 -c "import sys; print(sys.path)"``). However, every ``setup.py`` script out there will still install to this path.

A quick fix would be to use something like this: 

```bash
$ export PYTHONPATH=$PYTONPATH:"/usr/lib/$(python3 -V | sed 's/Python\s*\([0-9]\.[0-9]\)\.[0-9]/python\1/g')/site-packages"
# Afterwards PYTHONPATH should contain the path to where shredder is installed.
$ echo $PYTHONPATH
:/usr/lib/python3.4/site-packages
```

This makes python find our python gui module called ``shredder``.


The warning you pointed out however isn't nice and I hopefully fixed that as of 0608f7cc47b3abbe16bceb6c7d123b0b2a4fbc24.

**Comment by sahib** [comment]
@emk2203 Did it work? Can I close this?

**Comment by emk2203** [comment]
It didn't work, but if it's an Ubuntu issue, not really suited as a rmlint
bug. So, go ahead and close this.

Chris Pahl <notifications@github.com> schrieb am Di., 13. Okt. 2015 um
17:45 Uhr:
