### ISSUE TITLE
Slow repeated runs after hardlinking

### ISSUE THREAD

**Issue by intelfx** [sahib/rmlint#166]
First of all, the filesystem is NTFS (ntfs-3g). Here is what I've done:

```
rmlint -T df --hardlinked --hidden --xattr-write -U /run/media/... -c sh:hardlink -g
```

This had a runtime of ~1.5 hours and found lots of duplicates. I ran the generated script and then said:

```
rmlint -T df --no-hardlinked --hidden --xattr-read /run/media/... -c sh:hardlink -g
```

This finished instantly and found no duplicates. Finally, I decided to search for whole duplicate subtrees:

```
rmlint -T dd --hardlinked --hidden --xattr-read /run/media/... -c sh:handler=remove -g
```

...expecting that it will take no longer than it takes to stat the whole filesystem, because all duplicates are now hardlinks. But it is now running for 0.5 hours and I suspect that it went to compare files with their hardlinks...

**Comment by SeeSpotRun** [comment]
I'm travelling at the moment but will have a look at this next week.

As I recall, the existing-hardlink-detection logic is a bit incomplete.  For example if there are 2 existing hardlinks, it still checksums one of them.  It's also possible that the --xattr logic may be interfering with the existing-hardlink-detection logic.

**Comment by intelfx** [comment]
> For example if there are 2 existing hardlinks, it still checksums one of them.

Right, this makes sense in common case, because one cannot prove beforehand if there are no other duplicates (not hardlinked) of this inode.

However, I guess that checksumming may be safely skipped in one special case: if all candidates in a group are already hardlinks of the same inode, and there are no other duplicate possibilities (i. e. no other files of same size).

**Comment by SeeSpotRun** [comment]
Correct; it's been on my to-do list for a while.

What makes it a little tricky is the case where say file A is a hardlink of B, while file C is the same size as A and has data which matches A for the first few kb and then diverges.  Ideally, once the divergence is detected, the logic should realise that there is no need to read the rest of file A.  But since this is all happening in parallel threads it's not as straightforwards as it might sound.

**Comment by intelfx** [comment]
Yeah. But, actually, in my usecase handling this corner-case is not really needed: my workload is multimedia files, which are almost always of different sizes.

(Slightly OT: how do you in fact handle partial checksumming? Do you process files group-by-group, advancing equally on each file of the currently checked group and comparing partial checksums after all files in the group have been read to the same extent?)

**Comment by SeeSpotRun** [comment]
Re partial checksumming,we create "groups" of candidate files for matching (the first generation groups are just same-size files).  Once a group has enough files (ie more than 1 file) it starts sending its files to the reading queue.

The reading queue is processed using its own optimisation logic (one thread per disk; try to read files in order of physical location on the disk).  As files get to the head of their reading queue, they have their next increment read; the first increment is 16kB and then multiplies by 8 each increment.

After the increment is read the file is added to a "child group" of its parent group.  if the increment was unique then a new child group is created; if it matches another increment then it is added to an existing child group.  Once any child group has more than one file they are sent to the reading queue to have the next increment processed.

**Comment by SeeSpotRun** [comment]
Please try again with try now with https://github.com/SeeSpotRun/rmlint/tree/feature/skip_hardlinks

**Comment by sahib** [comment]
Closing for now, since @intelfx did not respond in a long time.
Feel free to re-open if necessary.
