### ISSUE TITLE
cygwin support

### ISSUE THREAD

**Issue by SeeSpotRun** [sahib/rmlint#170]
I managed to get rmlint running under cygwin (https://github.com/SeeSpotRun/rmlint/tree/cygwin).

It would be great if someone with more cygwin knowledge than me would like to take it a bit further...

**Comment by sahib** [comment]
@SeeSpotRun: Is this still relevant? Seems like the ``cygwin`` branch has been removed.

**Comment by SeeSpotRun** [comment]
Nah close it.

If I wanted a good Windows dupe finder I'd probably write one from scratch in VS rather than trying to adapt rmlint via cygwin.  Maybe one day.
