### ISSUE TITLE
Cannot find shredder

### ISSUE THREAD

**Issue by iainrs** [sahib/rmlint#171]
I've just installed rmlint on my Linux Mint 17.3 system
(compile included 'shredder.c')

It runs from command line (apparently ?)  OK
creates rmlint.sh 

but when I run 

      ...>rmlint --gui
I get 
       /usr/bin/python3: No module named shredder

.. >rmlint --version
version 2.4.2 compiled: Feb 28 2016 at [20:26:30] "Myopic Micrathene" (rev unknown)
compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support

rmlint was written by Christopher <sahib> Pahl and Daniel <SeeSpotRun> Thomas.
The code at https://github.com/sahib/rmlint is licensed under the terms of the GPLv3.

there exists a folder :  ./usr/lib/python3.4/site-packages/shredder/
				with the expected contents
& a file              : Shredder-2.4.2.Myopic.Micrathene-py3.4.egg-info
but no entry in ./usr/lib/python3.4/site-packages as I would have expected

however my default python system is 2.7 (needed for Linux Mint)
 

But cannot run 'shredder'

**Comment by iainrs** [comment]
Sorry the above is garbled (I'm new to editing these entries)

**Comment by sahib** [comment]
We had this a few times already: https://github.com/sahib/rmlint/issues/167#issuecomment-177533739. This seems only to affect Debian based distros, as explained there. 

Short version; use this to get it started: 

```bash
# This is only temporary, put this in .bashrc if you want it persistent:
$ export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/
```

If you're a bit unlucky, you might need to do these beforehand:

```bash
$ sudo apt-get install gir1.2-polkit-1.0
$ sudo apt-get install gir1.2-gtksource-3.0
```

**Comment by gorn** [comment]
I have tried the workaround, but I am getting this

> $ rmlint --gui
Could not import colorlog
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.4/site-packages/shredder/__main__.py", line 23, in <module>
    from shredder.application import Application
  File "/usr/lib/python3.4/site-packages/shredder/application.py", line 28, in <module>
    from shredder.views.runner import RunnerView
  File "/usr/lib/python3.4/site-packages/shredder/views/runner.py", line 21, in <module>
    from shredder.chart import ChartStack
  File "/usr/lib/python3.4/site-packages/shredder/chart.py", line 19, in <module>
    import cairo
ImportError: No module named 'cairo'


I am on stable debian.

**Comment by SeeSpotRun** [comment]
try `sudo apt-get install python-cairo`

**Comment by tomtroughton** [comment]
On Xubuntu 14.04:
python-cairo, gir1.2-polkit-1.0, gir1.2-gtksource-3.0 are installed.

    $ export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.4/site-packages/
    $ rmlint --gui
    Could not import colorlog
    Traceback (most recent call last):
      File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/lib/python3.4/site-packages/shredder/__main__.py", line 23, in <module>
        from shredder.application import Application
      File "/usr/lib/python3.4/site-packages/shredder/application.py", line 28, in <module>
        from shredder.views.runner import RunnerView
      File "/usr/lib/python3.4/site-packages/shredder/views/runner.py", line 29, in <module>
        class ResultActionBar(Gtk.ActionBar):
      File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
        return getattr(self._introspection_module, name)
      File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
        self.__name__, name))
    AttributeError: 'gi.repository.Gtk' object has no attribute 'ActionBar'

**Comment by sahib** [comment]
Yes, ``Gtk.ActionBar`` was added in GTK+ 3.12 (from 2013...), we should probably document 
the dependencies clearly (which includes ``gtk+ >= 3.12``). 

I think it will be probably troublesome to update just ``GTK+`` since many packages in Xubuntu depend on it - it's likely the easiest to update your whole distro in that case. :disappointed: 

Im afraid, but we depend on ActionBar and it's a bit hard to substitute (especially since that sort of problem solves itself by waiting...).

**Comment by tomtroughton** [comment]
Thanks for the quick response. I'll just use the command line while I wait. Shouldn't be that long before the next XUbuntu LTS is out. 

Tom

**Comment by sahib** [comment]
No problem. I tried to clarify the install instructions a bit in 6f848440d6fb9df59d2a2d3cb9536a29cd9ca3d4.
Closing for now, feel free to re-open when the problem persists after the upgrade.
