### ISSUE TITLE
Option to hardlink instead of completely remove

### ISSUE THREAD

**Issue by du5tball** [sahib/rmlint#173]
I'd like to have an option to hardlink files instead of removing them completely (could be done by calling the "link" program from coreutils). There are some cases where files should exist in two places, but I still don't want the diskspace wasted.

**Comment by sahib** [comment]
We have this already.

```bash
$ rmlint -c sh:link 
```

Note that this falls back to symbolic links when the files are on different disks.
If you use ``btrfs`` or another reflink-capable filesystem it will also attempt ``cp --reflink`` first.

See also the [FORMATTERS](https://rmlint.readthedocs.org/en/latest/rmlint.1.html#formatters) section in the man page or the [gentle guide](https://rmlint.readthedocs.org/en/latest/tutorial.html#outputs-formatters).
