### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by simmac** [sahib/rmlint#175]
It would be really cool if you could submit a rmlint formula for homebrew: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

This would help us OS X users

**Comment by sahib** [comment]
> This would help us OS X users

Probably, but Im not a OS X user and could not test that.
We have to rely on the community for this sort of thing. This means... *you*!

[Google found](https://gist.github.com/zimbatm/b2edd419d8eb4b375077) a few older formulas for ``rmlint 1.x``, the only thing left to do would be to swap ``make`` with ``scons``, test it and submit that (I don't know how the last thing is done).

**Comment by simmac** [comment]
Ok, I will try it. :)

**Comment by simmac** [comment]
Hmm, I have a problem generating the formula. The usual installation via scons works, but building via `brew install rmlint` fails:
```
Compiling ==> lib/utilities.c
lib/utilities.c:906:11: error: use of undeclared identifier 'partition'
    (void)partition;
          ^
```

My current formula is attached.
Does anybody have an idea where the problem is? 

[rmlint.txt](https://github.com/sahib/rmlint/files/181374/rmlint.txt)

**Comment by sahib** [comment]
Oh, that's a compile stop that was present in 2.4.2 (showing only BSD based systems).
I pushed a new patch release, that should have this bug fixed: 

https://github.com/sahib/rmlint/releases/tag/v2.4.3

**Comment by simmac** [comment]
Ha, I just saw the new release and deleted my comment before you sent yours, sorry.
Thanks for the patch!

**Comment by simmac** [comment]
Is there any possibility to pass the build path as an argument to scons or is it only possible to define this in the SConfig-file?

**Comment by sahib** [comment]
Depends on what you mean by *build path*.
Here are the currently support [variables/arguments for scons](https://rmlint.readthedocs.org/en/latest/developers.html#buildsystem-helpers).

**Comment by simmac** [comment]
Thanks, I figured it out (the bin will be generated by rmlint in the working directory).
I just pushed my formula to homebrew ([homebrew/pull/50284](https://github.com/Homebrew/homebrew/pull/50284)).

I ran into another issue described in #176 , I PR'ed the formular nevertheless because I think it is independent from the build process.

**Comment by sahib** [comment]
Cool, thank you. Hope it gets accepted.

**Comment by vitorgalvao** [comment]
@simmac Are you still working on this?

**Comment by tomhoover** [comment]
I just pushed a [formula to homebrew](https://github.com/Homebrew/homebrew-core/pull/5669). I'll comment again if/when accepted.

**Comment by sahib** [comment]
@tomhoover: Cool! Will add a note to the installation section once it's ready.

**Comment by tomhoover** [comment]
@sahib: the [formula](https://github.com/Homebrew/homebrew-core/pull/5669) has now been accepted into homebrew.

## Installation instructions for macOS (formerly OS X):

1. If [homebrew](http://brew.sh) has not already been installed on the system, execute `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`.
2. With [homebrew](http://brew.sh) installed, execute `brew install rmlint`.

**Comment by sahib** [comment]
I've updated the [installation instructions](https://rmlint.readthedocs.io/en/latest/install.html).
Thanks for your work, @tomhoover!

**Comment by tomhoover** [comment]
@sahib, you're welcome! BTW- you should probably close this issue. 😄
