### ISSUE TITLE
rmlint --gui not working on OS X

### ISSUE THREAD

**Issue by simmac** [sahib/rmlint#176]
I installed rmlint with all dependecies (including gtk+ and PyGObject) and it works well. However, trying to start rmlints gui doesn't work for me on OS X (10.11):

```
$ rmlint --gui
/Library/Frameworks/Python.framework/Versions/3.4/bin/python3: No module named shredder
```

I have python 2.7 and python 3.4 installed, `python` points to python 2.7.

**Comment by simmac** [comment]
Should be merged with #171 , sorry, I just saw it now.

**Comment by sahib** [comment]
Might be the same problem as #171. 
Try pointing your PYTHONPATH to the location where the python packages resides:

```bash
$ python3 -c "import site; print(site.getsitepackages())"
['/usr/lib/python3.5/site-packages']  # or something else
$ export PYTHONPATH="$PYTHONPATH:/usr/lib/python3.5/site-packages"
```

By the way, you should be also able to run the gui by launching it from the source tree:

```bash
# From inside the rmlint sources:
$ cd gui && make run
```

``rmlint`` should be clever enough to use ``python3``.

**Comment by simmac** [comment]
`make run` gives me

```
mkdir: -p: File exists
make: *** [schema] Error 1
```
Yes, I removed ~/.glib-schemas ...

**Comment by sahib** [comment]
I guess your ``mkdir`` does not handle it well when ``-p`` comes somewhere after the directory to create. Moved it to the front, please try again.

**Comment by simmac** [comment]
Waah :confounded: 

```
Traceback (most recent call last):
  File "shredder/__main__.py", line 15, in <module>
    from shredder.cmdline import parse_arguments
  File "/Users/simeonmacke/Desktop/Programmieren/forks/rmlint/gui/shredder/__init__.py", line 6, in <module>
    import gi
ImportError: No module named 'gi'
make: *** [run] Error 1
```

How do I get pip to install in Python3? I already installed gi via `pip install gi`, but it always installs the packages in python2

**Comment by sahib** [comment]
You would probably use ``pip3`` for that task.

http://stackoverflow.com/a/20868669/641662

**Comment by simmac** [comment]
Ha, thanks!
Now there seems to be a problem with gi:

```
Traceback (most recent call last):
  File "shredder/__main__.py", line 15, in <module>
    from shredder.cmdline import parse_arguments
  File "shredder/__init__.py", line 6, in <module>
    import gi
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
make: *** [run] Error 1
```

**Comment by sahib** [comment]
Hmm, there's something pretty wrong here. 
``print uri`` is still Python2 syntax and not Python3 compatible - even though it appears to sit in the right path.

How did you install that package exactly?
For a portable language like python it fucks up pretty badly when it comes to package managers...

**Comment by simmac** [comment]
I installed it with `pip3 install gi` ...

**Comment by sahib** [comment]
Hmm, hard to tell without access to a machine.
If your context is the packaging of the GUI, then I would package ``rmlint`` without it for now.

I'll think of that issue when I get access to a Mac box.

**Comment by sahib** [comment]
I'm closing this, since nobody else reported this and apparently no progress was made here...
