### ISSUE TITLE
Preprocessing blocks on large amount of files (Linux Mint)

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#179]
I received a mail from a user with the following problem description:

    I compiled rmlint from source yesterday and started running it immediately.
    The set-up is Linux Mint 17, latest version, 4 GB RAM, 500 GB hard drive,
    fresh install (say, 475 GB free). I need to dedupe a 2 TB NTFS USB hard
    drive.  

    Command was: rmlint -g 
    Traversing files shows 4 085 969.
    Preprocessing shows 4 007 187.
    Preprocessing has been running overnight; I
    don't know how long it has been hung.

    Question is: what to do? If I shut down the computer
    are the "traversing" results saved? I have no idea
    what caused the hang.  This is similar to Open
    Question #109, but I have 1 million less files and 2
    GB more RAM. 

    Any suggestions?  Thank you very much.

I asked him for permission to get the mail content up here
and told him to give us the following information:

```bash
$ rmlint -vvv   &>  /tmp/rmlint.log
$ find /absolute/path -type f | wc -l
```

The rmlint version he's using appears to be 6f848440d6fb9df59d2a2d3cb9536a29cd9ca3d4 (v.2.4.4).

Any thoughts on this @SeeSpotRun?

**Comment by SeeSpotRun** [comment]
Looks like I broke something; until we see the debug log I guess all I can do is look at the preprocess code for any potential infinite loops.

**Comment by sahib** [comment]
Im closing this for now, since we likely won't get any feedback from the original reporter.
