### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [sahib/rmlint#181]
I would like to point out that identifiers like "[`_RmHasher`](https://github.com/sahib/rmlint/blob/8dddfbb96bca217f1bb3edab191db942bec7c4fe/lib/hasher.h#L52)" and "[`_RmNode`](https://github.com/sahib/rmlint/blob/0872a6861b9ee63eb2783ab3cb7100e3d38fb308/lib/pathtricia.h#L32)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by sahib** [comment]
We use the underscore variant only for struct names that one is not suppose to use directly, but only through the accompanied typedef. I.e. we don't use ``struct _RmHasher`` but ``RmHasher``.  In the case of recursive ``structs`` we sometimes explicitly reference the underscore name to be clear about this. 

The risk of name clashing should be reasonably small by the usage of the "Rm" prefix and the fact that rmlint is not a library where name collisions in the API might be a more serious problem.

Also: This is plain old C and not C++.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by sahib** [comment]
This is far from undefined behavior in practice. 
Im not accidentally breaking stuff by blindly renaming stuff, just to comply with the links you give me.

Closing.
