### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [sahib/rmlint#182]
I guess that a different program design will be needed for your function "[signal_handler](https://github.com/sahib/rmlint/blob/6f848440d6fb9df59d2a2d3cb9536a29cd9ca3d4/src/rmlint.c#L65 "Check signal handling implementation.")".
* The variable "CTRLC_COUNTER" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.").
* The function "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by sahib** [comment]
Hi there,

Im not sure if it would be enough to make CTRLC_COUNTER a ``sig_atomic_t`` (which is typedef'd to int on my system anyways) and to use ``_exit()`` instead of normal ``exit()``. 
Still there would be some log-calls inside the signal handler that might behave weirdly.

In 03dacb1ba64d3e79ddfe9100e6f7c014b40a8fac I made ``rm_session_abort/was_aborted`` independent of the session and do the actual handling in the checks that happen outside of the signal handler. This way no ``_exit()`` is needed and the use of atomic int (``g_atomic_*``) should behave sanely.

By the way, did you use some sort of static checker to find that (if so, which)?

**Comment by elfring** [comment]
1. Would you like to consider other software design options?
 * [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
 * [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
 * [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")


2. How do you think about to find any [more update candidates](https://github.com/sahib/rmlint/commit/03dacb1ba64d3e79ddfe9100e6f7c014b40a8fac#diff-3bed2fa25d5f737822b0c10923bfedc1L69 "Check signal handling implementation once more.") by working with usual search interfaces?

**Comment by sahib** [comment]
1. What's wrong about the current approach?
2. Im sorry, but I didn't understand that.

**Comment by elfring** [comment]
1. I find the current implementation of the function "signal_handler" still async-signal-unsafe.
2. GitHub provides a search interface (for example) which is working also for source code review to some degree. Are you looking for [higher level analysis tools](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis")?

**Comment by sahib** [comment]
I begin to think you're a bot... :smirk:

1. What is it that makes you assume that?
2. Huh?

**Comment by elfring** [comment]
Are function calls like "rm_session_abort" and "rm_log_error_line" questionable for the discussed function "signal_handler"?

**Comment by sahib** [comment]
I don't think so.

``rm_session_abort`` only sets an atomic integer. ``rm_log_error_line`` is only executed for the  SIGSEGV case where I really don't care anymore about being async-signal-safe.
