### ISSUE TITLE
Print original file in json

### ISSUE THREAD

**Issue by japrogramer** [sahib/rmlint#185]
Hi, I've been looking at how to output what rmlint thinks is the original file into its output. 
i know it sounds strange, but i want to know where the only copy of the file is going to be if the others are deleted.

**Comment by japrogramer** [comment]
basically i want a list of all the files that are duplicates, and the file for which they are duplicates of

**Comment by SeeSpotRun** [comment]
The json output already includes the field `is_original` which is `true` for originals and `false` for duplicates.

Can you give an example of what your desired output would look like?

**Comment by japrogramer** [comment]
i was not aware of that field, after carefully looking at the output json, i can see that it has everything i need. the twins field denotes the total number of duplicates? and they are listed in order so that if i sliced the next items, i will receive the duplicates of the original?

i want them to be grouped together
i guess i  wish they where organized so that i can do something like this

json_data['file_group'][0] # and get all duplicates in file group 1


for set_f in json_data['file_group']:
    keep = get_original(set_f])
    _, score = test(keep)
    for individual_ in set_f:
        passed, i_score = test(individual_set)
        if i_score > score:
            keep = individual_in
            score = i_score
     # write updated json with new originals if any and continue

 something like that could be included in the generated python, for advanced used cases.
for ex, where

**Comment by SeeSpotRun** [comment]
Yes they are in order. 

Note that in special cases (`--keep-all-tagged`) a group of duplicates may have more than one original.
Feel free to contribute to the python post processing code.
