### ISSUE TITLE
Statistics output

### ISSUE THREAD

**Issue by deajan** [sahib/rmlint#187]
It would be great if rmlint.sh & rmlint.json files would also have some statistics lines with:
- Number of files processed
- Number of empty files
- Number of empty dirs
- Number of dupes
- Percentage of files & dirs to potentially clean up
- Time spent for task

**Comment by sahib** [comment]
We have some of these in the footer of the ``.json`` output already (*Number of files processed, number of dupes*). Just run ``rmlint -o json`` to and look at the last few lines.

What would be *Percentage of files & dirs to potentially clean up*? Just the number dupes divided through the number of total files (in percent)? The time spent for the task might be obtained by running ``rmlint`` with a ``time`` in front, but I admit that it might be worth adding as statistics.

We don't have an explicit counter for empty files and dirs, although one could get that rather easily by parsing the json and letting your computer count. The point is, if we add a count for empties, we would need to add a counter for other lint types too (broken symbolic links etc.) for consistency. So what's your usecase here? Something that ``find -type f -empty | wc -l`` won't do?

*Note:* I'm referring to the current version of ``rmlint`` (``master``). In #186 you said that you're using 2.2.0.

**Comment by SeeSpotRun** [comment]
I started on a separate `-o stats` report  with https://github.com/SeeSpotRun/rmlint/commit/a70728d80355f7524b6a850767d6e9e089eb5628 but have not gotten back to this for a while due to life. 

This could be extended as desired to include the requested metrics.

**Comment by sahib** [comment]
I ported the changes from @SeeSpotRun to the current develop branch and extended it a little:

![stats output](https://i.imgur.com/a36OHRu.png)

If tests passes, I'll close this tomorrow. There's no number o empty files/dirs, but some other info.
(Ignore that last line of the output, I tried to be clever with the screenshot)

**Comment by deajan** [comment]
Glad to see this is comming to rmlint, thanks :)
