### ISSUE TITLE
Problem compiling on FreeNAS 9.10 jail

### ISSUE THREAD

**Issue by giox069** [sahib/rmlint#192]
I'm trying to compile rmlint on a FreeNAS 9.10 jail (it's a FreeBSD 10.3 OS), following the install guide here: http://rmlint.readthedocs.io/en/latest/install.html

But `scons config` fails with
```
root@jail1:~/rmlint/rmlint # scons config
scons: Reading SConscript files ...
Checking whether the C compiler works... yes
Checking for git revision... (cached) ff59a20
Checking for pkg-config... no
Checking for glib-2.0 >= 2.32... Error: glib-2.0 >= 2.32 not found.
```
despite I have glib installed
```
root@jail1:~/rmlint/rmlint # pkg info glib
glib-2.46.2_2
Name           : glib
Version        : 2.46.2_2
Installed on   : Sat Sep 24 11:16:36 2016 CEST
[...]
```
Any idea ?
Thank you

**Comment by giox069** [comment]
pkgconf package was missing  :(
```
pkg install pkgconf
```
Could you add it to the install page? It will save some hour of research to someone else :)

**Comment by sahib** [comment]
Hey @giox069,

I added ``pkgconf`` per 9718bcb41360c070888011a8d3bdfb683732ed0a.
Thanks for the hint.
