### ISSUE TITLE
Compile issue on Centos 6.7 

### ISSUE THREAD

**Issue by LeonClayton** [sahib/rmlint#193]
Hello All

Struggling to compile rmlint on a centos 6.7 box where this tool would be very useful. As can be seen below i get the following errors. 

Compiling ==> lib/md-scheduler.c
lib/md-scheduler.c:116: error: redefinition of typedef 'RmMDSDevice'
lib/md-scheduler.h:85: note: previous declaration of 'RmMDSDevice' was here

Full output here. Any pointers welcomed

# git clone https://github.com/sahib/rmlint.git
Initialized empty Git repository in /root/rmlint/.git/
remote: Counting objects: 14179, done.
remote: Total 14179 (delta 0), reused 0 (delta 0), pack-reused 14179
Receiving objects: 100% (14179/14179), 10.10 MiB | 1015 KiB/s, done.
Resolving deltas: 100% (10641/10641), done.
# cd rmlint/
# scons config 
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for git revision... Not allowed.
(cached) unknown
Checking for pkg-config... yes
Checking for glib-2.0 >= 2.32... yes
Checking for gio-unix-2.0... yes
Checking for blkid... yes
Checking for json-glib-1.0... yes
cc1: error: unrecognized command line option "-std=c11"
Checking for -std=c11 support...(cached) no
Checking for cygwin environment...(cached) Linux/maprdemo/2.6.32-573.el6.x86_64/#1 SMP Thu Jul 23 15:44:03 UTC 2015/x86_64/x86_64(cached) no
Checking whether blkid_devno_to_wholedisk is declared... yes
Checking for existence of /sys/block... (cached) yes
Checking for C header file libelf.h... yes
Checking for C library libelf... yes
Checking for C type struct fiemap... yes
Checking for C function getxattr()... yes
Checking for C function setxattr()... yes
Checking for C function removexattr()... yes
Checking size of off_t ... yes
Checking for C function stat64()... yes
Checking whether G_CHECKSUM_SHA512 is declared... no
Checking for C header file locale.h... yes
Checking for C header file linux/limits.h... yes
Checking whether posix_fadvise is declared... yes
Checking whether faccessat is declared... yes
Checking whether AT_FDCWD is declared... yes
Checking for C header file linux/btrfs.h... no
Checking for C header file sys/utsname.h... yes
Building rmlint
scons: done reading SConscript files.
scons: Building targets ...
Printing configuration...
Unable to find sphinx binary in PATH
Will be unable to build manpage or html docs

rmlint will be compiled with the following features:

    Find non-stripped binaries (needs libelf)             : yes
    Optimize using ioctl(FS_IOC_FIEMAP) (needs linux)     : yes
    Support for SHA512 (needs glib >= 2.31)               : no
    Build manpage from docs/rmlint.1.rst                  : no
    Support for caching checksums in file's xattr         : yes
    Support for reading json caches (needs json-glib)     : yes
    Checking for proper support of big files >= 4GB       : yes
        (needs either sizeof(off_t) >= 8 ...)             : yes
        (... or presence of stat64)                       : yes

    Optimize non-rotational disks                         : yes
        (needs libblkid for resolving dev_t to path)      : yes
        (needs gio-unix-2.0)                              : yes

    Enable gettext localization                           : yes
        (needs <locale.h> for compile side support)       : yes
        (needs msgfmt to compile .po files)               : yes

The following constants will be used during the build:

    Version information  : 2.4.4 "Myopic Micrathene" (rev unknown)
    Compiler             : gcc
    Install prefix       : /usr/local
    Actual prefix        : /usr/local
    Verbose building     : no
    Adding debug symbols : no

Type 'scons' to actually compile rmlint now. Good luck.
    
scons: done building targets.
# scons DEBUG=1 -j4
scons: Reading SConscript files ...
Checking whether the C compiler works(cached) yes
Checking for git revision... Not allowed.
(cached) unknown
Checking for pkg-config... (cached) yes
Checking for glib-2.0 >= 2.32... (cached) yes
Checking for gio-unix-2.0... (cached) yes
Checking for blkid... (cached) yes
Checking for json-glib-1.0... (cached) yes
cc1: error: unrecognized command line option "-std=c11"
Checking for -std=c11 support...(cached) no
Checking for cygwin environment...(cached) Linux/maprdemo/2.6.32-573.el6.x86_64/#1 SMP Thu Jul 23 15:44:03 UTC 2015/x86_64/x86_64(cached) no
Checking whether blkid_devno_to_wholedisk is declared... yes
Checking for existence of /sys/block... (cached) yes
Checking for C header file libelf.h... yes
Checking for C library libelf... yes
Checking for C type struct fiemap... yes
Checking for C function getxattr()... yes
Checking for C function setxattr()... yes
Checking for C function removexattr()... yes
Checking size of off_t ... yes
Checking for C function stat64()... yes
Checking whether G_CHECKSUM_SHA512 is declared... no
Checking for C header file locale.h... yes
Checking for C header file linux/limits.h... yes
Checking whether posix_fadvise is declared... yes
Checking whether faccessat is declared... yes
Checking whether AT_FDCWD is declared... yes
Checking for C header file linux/btrfs.h... no
Checking for C header file sys/utsname.h... yes
Building rmlint
scons: done reading SConscript files.
scons: Building targets ...
build_config_template(["lib/config.h"], ["lib/config.h.in"])
Compiling ==> lib/checksums/cfarmhash.c
Compiling ==> lib/checksums/city.c
Compiling ==> lib/checksums/murmur3.c
Compiling ==> lib/session.c
Compiling ==> lib/xattr.c
Compiling ==> lib/file.c
Compiling ==> lib/pathtricia.c
Compiling ==> src/rmlint.c
Compiling ==> lib/shredder.c
Compiling ==> lib/treemerge.c
Compiling ==> lib/traverse.c
Compiling ==> lib/replay.c
Compiling ==> lib/cmdline.c
Compiling ==> lib/cfg.c
Compiling ==> lib/md-scheduler.c
lib/md-scheduler.c:116: error: redefinition of typedef 'RmMDSDevice'
lib/md-scheduler.h:85: note: previous declaration of 'RmMDSDevice' was here
Compiling ==> lib/utilities.c
scons: *** [lib/md-scheduler.o] Error 1
scons: building terminated because of errors.

**Comment by sahib** [comment]
Hey @LeonClayton,

I think that error indicates an ancient compiler (I'm curious: ``gcc -v``?).
Please try again with c29f420 (i.e. do a``git pull`` before compiling again).

**Comment by LeonClayton** [comment]
Thanks @sahib 

Had forgot to update the compiler. Very sry. Upgraded this with the following steps and all good. 

$ wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo -P /etc/yum.repos.d
$ sh -c 'echo "enabled=1" >> /etc/yum.repos.d/devtools-1.1.repo'
$ yum install devtoolset-1.1
$ scl enable devtoolset-1.1 bash
$ gcc --version
# gcc --version
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
Copyright (C) 2012 Free Software Foundation, Inc.
