### ISSUE TITLE
GUI Cannot Start - "Could not import colorlog"

### ISSUE THREAD

**Issue by FluxCapacity** [sahib/rmlint#194]
Hi.

>[f@l gui]$ rmlint --gui
>Could not import colorlog
>09:27:42 INFO     [__init__.py: 42] root: Starting up.
>
>(shredder:2654): Gtk-WARNING **: Failed to get the GNOME session proxy: The name >org.gnome.SessionManager is not owned
> 
> (shredder:2654): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
> 
> (shredder:2654): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
> 09:27:42 INFO     [application.py:102] application: Loading resources from: /home/f/rmlint/gui/shredder/resources/shredder.gresource
> 
> (shredder:2654): Gtk-WARNING **: Theme parsing error: <data>:67:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> Traceback (most recent call last):
>   File "/home/f/rmlint/gui/shredder/application.py", line 110, in do_startup
>     load_css_from_data(css_data.get_data())
>   File "/home/f/rmlint/gui/shredder/util.py", line 53, in load_css_from_data                                                        
>     style_provider.load_from_data(css_data)                       
> GLib.Error: gtk-css-provider-error-quark: <data>:67:10not a number (1)                                                              
> Traceback (most recent call last):                                
>   File "/home/f/rmlint/gui/shredder/application.py", line 91, in do_activate                                                        
>     self.win.present()                                            
> AttributeError: 'NoneType' object has no attribute 'present'

Fails on GNOME and LXQT w/bspwm.  Arch x86_64, two different machines, both up to date.

Let me know if anything else is needed like `pacman -Q` output.

edit: formatting

**Comment by sahib** [comment]
The line  ``Could not import colorlog`` is not your problem here, it's just a warning that the log messages
won't be very colorful. Which version of GTK are you using?

**Comment by FluxCapacity** [comment]
@sahib `gtk3 3.22.1+69+ga1115c0-1` and `gtk2 2.24.31-1`

**Comment by sahib** [comment]
Should be working again as of 4ba4a31.
Was "just" a GTK deprecration *warning* that caused an exception in the program
(which actually is not what warnings should do...).

**Comment by sahib** [comment]
Also added a note that explains that ``colorlog`` is not necessarily needed.

**Comment by FluxCapacity** [comment]
I just cloned the code and compiled it.

> [f@d rmlint]$ rmlint --gui
> Could not import colorlog. This is not an error.
> You just will not have colors in the logging output...
> 14:28:45 INFO     [__init__.py: 42] root: Starting up.
> 14:28:45 INFO     [application.py:102] application: Loading resources from: /usr/lib/python3.5/site-packages/shredder/resources/shredder.gresource
> 14:28:45 DEBUG    [application.py:148] application: Instancing views.
> 14:28:45 INFO     [locations.py:301] locations: Refilling location entries
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/shredder/application.py", line 150, in do_startup
>     self.win.views.add_view(LocationView(self), 'locations')
>   File "/usr/lib/python3.5/site-packages/shredder/views/locations.py", line 250, in __init__
>     self.refill_entries()
>   File "/usr/lib/python3.5/site-packages/shredder/views/locations.py", line 339, in refill_entries
>  Gio.FILE_ATTRIBUTE_FILESYSTEM_SIZE)))
>   File "/usr/lib/python3.5/site-packages/shredder/views/locations.py", line 370, in add_entry
>     entry = LocationEntry(name, path, icon, fill_level)
>   File "/usr/lib/python3.5/site-packages/shredder/views/locations.py", line 171, in __init__
>     percent = int(used / total * 100)
>ZeroDivisionError: division by zero

It gives a blank, gray window and the output hangs there; `CTRL+C` does not kill it, only `pkill python` does.  If I use alt+tab I can see the Shredder broom icon for the window.

**Comment by sahib** [comment]
Thanks for the hint, that was another bug (although I wonder which filesystem of yours has a total size of 0). Should be fixed as of f27498d. You can do a ``git pull`` to update the code and just need to recompile/reinstall the program. No need for a fresh clone.

**Comment by FluxCapacity** [comment]
It works!  Thanks.
