### ISSUE TITLE
rmlint remote files

### ISSUE THREAD

**Issue by gorn** [sahib/rmlint#199]
It would be really great, if it is somehow possible to use rmlint over ssh. Sometimes there is a rather big collection of files on local and remote computer. It would be great if rmlint can asssist in such cases. Not necesarilly "out of box" with an simple option, but to give me for example chance to run rmlint on remote computer (and generate json file) and than replay it on local computer (i.e. taking info about remote files from json file and gathering more info about local files locally) to find out what are the duplicates which can be removed or maybe what are the non duplicates which needs to be transferred. 

Again - I am not asking for options which would cover every imaginable case, I would leave this to competent user, but only to help with the duplicates recognition. OR if this is already solvable by existing options it would be great to explain it in documentation. 

Thanks for great software anyways

**Comment by sahib** [comment]
That's not in the reach of ``rmlint``, but you will most likely want to use something like ``sshfs``:

```bash
# Mount the remote filesystem locally over ssh:
$ sshfs -o rw user@host:/path/to/mount /path/to/mountpoint
# Run rmlint as usual on the mounted (remote) and local files:
$ rmlint /path/to/mountpoint /some/local/files
```

**Comment by sahib** [comment]
I guess this can be closed, feel free to re-open if the original issue was not resolved.

**Comment by gorn** [comment]
Thanks for an idea, but this does not solve the issue (and BTW I use it exactly how you are suggesting it). However this makes all remote files to be transferred over network to calculate the hash everytime rmlint is run which makes it very very slow.

My idea was if one could run rmlint remotely to generate json file (which contains all necessarry info about remote files) and than supply it ti rmlint instead of the files.

**Comment by sahib** [comment]
> However this makes all remote files to be transferred over network to calculate the hash everytime rmlint is run which makes it very very slow.

I'm not sure how you expect us to be much faster than sshfs at this point. :smirk:
The other alternative would be to tell another computer to run rmlint locally,
which sounds like a very bad idea to me from a security perspective.

However, you can use ``--replay`` for this (not tested):

```bash
# remote machine:
$ rmlint your-remote-files
# copy the rmlint.json to your computer as rmlint-remote.json.
```

Then, on your local computer:

```bash
$ rmlint your-local-files
$ mv rmlint.json rmlint-local.json
# Fix the root of the rmlint-remote.json paths.
# They still have the path prefix of the remote machine.
# You might to play a bit around to get this work:
$ sed -i 's#path: /remote/root/path#path: /path/to/sshfs#g'
$ rmlint --replay rmlint-local.json --replay rmlint-remote.json
```

The last command should replay the results from your previous runs.
``rmlint`` is designed to work well with other tools. Implementing the complete workflow might solve your usecase, but adds tons of complexity and might be too specialized for other workflows.

**Comment by gorn** [comment]
Yes, I  was looking for something like this solution. To run the rmlint on the remote machine and only transfer .json. I am fine with playing around with pather within the file, that is not problem and understandable. What I am however missing is somthing like this (pseudocode):

`rmlint /path/to/local/files // --replay rmlint-remote.json
`
which would find the local files which are identical to something from remote directory. If it is possible with the current script it might be good to add it to documentation.

**Comment by sahib** [comment]
> rmlint /path/to/local/files // --replay rmlint-remote.json

No, it's not yet possible to do this (i.e. mixing ``--replay`` and non-replay runs).
This has a reason: You can pass paths to a ``--replay`` run that can be used for interactive re-runs:

```bash
$ rmlint ./
$ cd ./music                              # go to a small subdirectory
$ rmlint --replay ../rmlint.json          # only shows the contents of  the files under ./music
$ rmlint ../music/sub --replay --size=10M # only shows files from "sub" with size >= 10M
```

The possibility of giving more than one json file to ``--replay`` is documented in the manpage, but not in the online documentation. To be honest, I thought it would be a rather esoteric usecase, but our users continue to surprise me. Might add a short note.

Does ``--replay`` solve your problem?

**Comment by gorn** [comment]
Not really, because I want to make sure I am only removing the files which are local duplicates of remote files and not local files which are duplicates of local files, neither remote files which are duplicates of remote files (which is easily filtered out).

My pseudocode was just to tell the idea, so perhaps something like

`rmlint --replay rmlint-local.json // --replay rmlint-remote.json` 

or even

`rmlint --replay rmlint-local.json // rmlint-remote.json` 

Or generally - how to use replay with the // capability.

I understand that everyone uses rmlint in another way (which means that is is a great tool), but I do not think that this usage is very esoteric. Whenever you have large amout stored remotely and you need to merge them with something local, you need to minimize the transfer of large amout of files either way. But I can imagine this can sound esoteric to someone :)

**Comment by SeeSpotRun** [comment]
It's a reasonable idea but it's not particularly compatible with the optimisation strategy of rmlint, which tries to improve speed by only reading part of each file and then comparing that and moving on.  And it's potentially risky if a remote file is also mapped locally as an nfs/sshfs/samba mount.

With that said, it should be possible to encode something like your suggested
```
rmlint --replay rmlint-local.json // rmlint-remote.json
```
This could also be useful in other usecases.

**Comment by gorn** [comment]
this would be really great

**Comment by sahib** [comment]
I agree with @SeeSpotRun, placing a ``//`` between several ``--replay`` files might prove useful.

A necessary change would be to make ``--replay`` take no arguments and take all ``.json`` files
as replay arguments. The the option parser can't currently handle more than one argument to an option (i.e. ``--replay 1.json 2.json``) and therefore we're not able to match the ``//`` to the actual position where it's supposed to be. The reason that I'm mentioning this detail is just that it might break compatibility
very slightly - but I guess it's within the scope and justified in this case.

> I understand that everyone uses rmlint in another way (which means that is is a great tool), but I do not think that this usage is very esoteric

Might be, but we already had users that considered a dataset of 5 million files as perfectly normal. :smile:

**Comment by sahib** [comment]
As of b591113 and d701c29 the following is now possible:

```bash
$ mkdir a b
$ echo x > a/1; echo x > a/2; echo x > b/1; echo x > b/2
$ rmlint a/ -o json:a.json
$ rmlint b/ -o json:b.json
$ rmlint a/ b/ --replay a.json // b.json
INFO: Loading json-results '/home/sahib/dev/rmlint/a.json'
INFO: Loading json-results '/home/sahib/dev/rmlint/b.json'

# Duplicate(s):
    ls '/home/sahib/dev/rmlint/b/1'
    rm '/home/sahib/dev/rmlint/b/2'
    rm '/home/sahib/dev/rmlint/a/1'
    rm '/home/sahib/dev/rmlint/a/2'
...
```

I think this should (finally) solve your usescase together with the aforementioned copying of the remote json.

**Comment by gorn** [comment]
I am confused about the syntax. Should not // mean that the files in b/ are always preserved? Also would not be something like `rmlint a/  --replay a.json // --replay b.json` more descriptive. Maybe we are talking about different usages, so let me reformulate what you are saying, so I am sure I understand the feature as it should work now (and can be tested + added to docs). Suppose that I have files on a remote server and I have a local copy on my notebook where I make changes (I understand that this scenario might need other tools than rmlint, but this is for illustration only).

I.e. at some point I made a copy of files like this
```sh
server$ cd /home/user/myfiles
server$ ls 
directory1   directory2   directory3   directory4
server$ rsync -a directory1 notebook:/home/user/
```
than I work on a notebook for a month, while other people continue to use the server files. Now I am back on very slow internet (or the files are large) and I want to find out which files are on my notebook which are not on server so I can transfer them (via the slow connection).

To be carefull, I first copy all files to another directory and prepare json inside it
```sh
notebook$ cd /home/user
notebook$ mkdir transfer
notebook$ cp -r directory1 transfer/
notebook$ cd transfer
notebook$ rmlint .
```
Thank I ssh to remote machine to retreive the json file. 
```sh
server$  cd /home/user/myfiles
server$  rmlint .
```
I copy the rmlint.json file over internet to my notebook and name it rmlint-server.json. On the notebook I now can issue the final command
```sh
notebook$ cd /home/user/transfer
notebook$ rmlint . --replay rmlint.json // rmlint-server.json
```
which generates ./rmlint.sh which removes averything from current direcotry (transfer) with exception of files which are NOT on server. Than I can maybe transfer these files or so. The syntax feels little confusing to me, here are some options whic are IMHO more descriptive, but I do not know the glory details of rmlint syntax, so I might be suggesting somethign wrong. What about 

`rmlint . --replay rmlint.json // --replay rmlint-server.json`

or even

`rmlint --replay rmlint.json // --replay rmlint-server.json`

or even making the rmlint.json unnecessary altogether by allowing

`rmlint .  // --replay rmlint-server.json`

Thank you very much and let me know if I am getting anything wrong.

**Comment by sahib** [comment]
> I am confused about the syntax. Should not // mean that the files in b/ are always preserved? 

No. It just means that files from **b/** should be preferred as original over files in **a/**.
If you want to make sure that you keep all files in **b/** you need to specify ``-k`` (``--keep-all-tagged``).
In this case he will print this:

```
$ rmlint a/ b/ --replay a.json // b.json -k
# Duplicate(s):
    ls '/home/sahib/dev/rmlint/b/1'
    ls '/home/sahib/dev/rmlint/b/2'
    rm '/home/sahib/dev/rmlint/a/1'
    rm '/home/sahib/dev/rmlint/a/2'
```

Regarding the syntax: ``--replay`` is now a normal option. It does not take any arguments anymore, it will just take all files ending with ``.json`` passed on the commandline and tries to parse them. The ``//`` between two is recognized similar to the way directories are passed to ``rmlint`` in normal mode.

> Maybe we are talking about different usages, so let me reformulate what you are saying, so I am sure I  understand the feature as it should work now (and can be tested + added to docs). 
> [...]

Thanks for the more exact explanation, I think we have about the same idea of the workflow.

> [...] which generates ./rmlint.sh which removes averything from current direcotry (transfer) with exception of files which are NOT on server. Than I can maybe transfer these files or so.

If you want to preserve the files pointed to by ``rmlint-server.json`` you might want to add ``-k``.
I understand correctly that ``transfer/directory1`` should only contain the "diff" to the one on the server?

> What about
>
>      rmlint . --replay rmlint.json // --replay rmlint-server.json
>
> or even
>
>      rmlint --replay rmlint.json // --replay rmlint-server.json

Both are possible if you like that variation. ``--replay`` can be specified more than once without doing harm. Your confusion really stems from the change that ``--replay`` doesn't take an argument anymore.
This way it's backwards compatible and allows you to specify ``.json`` files on the commandline similar
to normal directories. If no directory is given (i.e. no ``.``), then the current working directory is assumed implicitly.

> or even making the rmlint.json unnecessary altogether by allowing
> 
>     rmlint . // --replay rmlint-server.json

This won't work, since ``rmlint`` in ``--replay`` mode does not do any real IO, which would be required for this to work. Note that you still need to edit (with ``sed`` for example) ``rmlint-server.json`` in order to
fix the prefix of the paths as explained further up.

**Comment by gorn** [comment]
Ok, thanks for the explanation, it think it is clear to ME now, hopefully this will be to others. I was particuraly confused by 
  - the fact that althought you put directories in the command, once there is a replay, it does not read any filesystem. 
  - the fact the --replay does not take any argument (it was my wrong mental impression that it does)

you may want to make sure that this is clarified in documentation (but maybe it is just me).

I omitted -k wrongly in effort to simplify, I am using it in praxis.

Thanks for your great tool, I think it is very underpromoted. In fact I was trying to set up something similar by hand for years (just for myself to clean up my stuff), but as you know very well, it is not easy eround the edges so I never really finished it up. Now thanks to your rmlint I am able to finally tidy up all the data mess I accumulated over 20 comps of so during years. THANKS

**Comment by sahib** [comment]
> Ok, thanks for the explanation, it think it is clear to ME now, hopefully this will be to others. I was particuraly confused by

Might need some more examples indeed.

> the fact that althought you put directories in the command, once there is a replay, it does not read any filesystem.

I explained the *Why* in https://github.com/sahib/rmlint/issues/199#issuecomment-263573610.
The manpage actually does not state that very clearly to be honest, so it might need a clarifying sentence.


> the fact the --replay does not take any argument (it was my wrong mental impression that it does)

That was changed only recently due to your feature request. It's a direct consequence of how our commandline parser works. You can of course still pretend it takes an argument, it won't hurt. :smile:

> Thanks for your great tool, I think it is very underpromoted. In fact I was trying to set up something similar by hand for years (just for myself to clean up my stuff), but as you know very well, it is not easy eround the edges so I never really finished it up. Now thanks to your rmlint I am able to finally tidy up all the data mess I accumulated over 20 comps of so during years. THANKS

Thanks. Then go out and give us some promotion.
Or even better get us into the debian packages or talk to someone who can. :smirk:

**Comment by sahib** [comment]
Added a bit more explanation in 0445049. Closing since everything else should have been handled.

**Comment by lockywolf** [comment]
> `--replay` is now a normal option

Doesn't seem to hold in 2.20.1:

```
root@server:~/2020-12-18_sorting_hdd-running-rmlint-seagate-vs-wd/pi# /root/rmlint-2.10.1/rmlint --replay -mkgr -T dd /mnt/SEAGATE/ //  2021-01-04_big-hdd.json
WARNING: Can't open directory or file "-mkgr": No such file or directory
INFO: Loading json-results `/root/2020-12-18_sorting_hdd-running-rmlint-seagate-vs-wd/pi/2021-01-04_big-hdd.json'
WARNING: Error: JSON data must be UTF-8 encoded
WARNING: Loading /root/2020-12-18_sorting_hdd-running-rmlint-seagate-vs-wd/pi/2021-01-04_big-hdd.json failed.
ERROR: No valid .json files given, aborting.
```

Apparently, `--replay` sees `-mkgr` as an argument, or something like that.

**Comment by SeeSpotRun** [comment]
Hey sorry I didn't respond earlier.

> Apparently, --replay sees -mkgr as an argument, or something like that.

Yes, the next argument after `--replay` needs to be the name of the json file from the previous run.  So you would need:
```
$ rmlint -mkgr -T dd /mnt/SEAGATE/ // --replay  2021-01-04_big-hdd.json
```

**Comment by SeeSpotRun** [comment]
Actually that won't work.

See discussion at https://github.com/sahib/rmlint/issues/329#issuecomment-810576164
