### ISSUE TITLE
Option to create rmlint.sh that asks for each file

### ISSUE THREAD

**Issue by claell** [sahib/rmlint#202]
I tried fdupes and liked the option `fdupes -d` where the user is asked what file should be preserved.
Is it possible to create a modified version of rmlint.sh that has similar functionality?

**Comment by sahib** [comment]
I didn't like that and decided to write ``rmlint`` as completely non-interactive tool. :smile:
But I recognize that my opinion is not useful to everyone, so it's easily possible to swap the command that is executed on deletion. Just write a shell script like this and put it in your PATH:

```bash
#!/bin/sh
# This script gets the duplicate file path as $1
# and the respective original file path as $2.

read -r -p "Delete $1? [y/N] " response

case $response in
    [yY][eE][sS]|[yY]) 
        echo "Removing $1 since it was an duplicate of $2... Bye."
        rm -rf $1
        ;;
    *)
        echo "Keeping $2!"
        ;;
esac
```

Then just execute ``rmlint`` like this:

```bash
$ rmlint -c 'sh:cmd=your-script-name.sh "$1" "$2"'
```

 You can pretty much go anywhere from here. You can even color the output yourself. :smirk:

**Comment by claell** [comment]
Alright, thanks for the script.
