### ISSUE TITLE
rmlint should not change permissions of output sh file

### ISSUE THREAD

**Issue by phemmer** [sahib/rmlint#211]
rmlint attempts to change the permissions of the output sh file to 0700. rmlint should only set the permissions on the file when it creates it, not if it already exists.

This can result in really bad behavior, as if you run the command as root, with an output file of `/dev/null`, it will actually change the permissions of `/dev/null`. This behavior persists even if you output to stdout, and stdout has been redirected to `/dev/null`.

For example, both these commands will try and change the permissions of `/dev/null`

    rmlint -o sh:stdout > /dev/null
    rmlint -o sh:/dev/null

This is observed with Version 2.2.0

**Comment by sahib** [comment]
I completely agree that this should not happen. Will be fixed soon.

**Comment by sahib** [comment]
Should be fixed as of 330c92c.

**Comment by sahib** [comment]
Closing, re-open when problems persists.
