### ISSUE TITLE
Is rmlint able to find files of similar names?

### ISSUE THREAD

**Issue by rieje** [sahib/rmlint#214]
Is rmlint able to find files of similar names (and names only, not taking into account size or content)? For example, "The Red Bear Hugging Tree.mp4" and "The Blue Bear Hugging Tree.mkv". I tried the `-b` option but it is far too strict for my purposes.

Also, does it support excluding subdirectories or files containing a particular string? For example, I have lots of videos named "VTS_02_1.VOB" and lots of images named "001.png" (of course, they are in different directories) and I don't want them to be counted as duplicates unless they are the exactly same file in terms of content.

Lastly, I must have missed the option for specify location of rmlint.sh--how can I do so?

Thank you. I will close this immediately if it is frowned upon, but I haven't found a place to ask these types of questions where I can get some answers.

**Comment by sahib** [comment]
> Is rmlint able to find files of similar names (and names only, not taking into account size or content)? For example, "The Red Bear Hugging Tree.mp4" and "The Blue Bear Hugging Tree.mkv". I tried the -b option but it is far too strict for my purposes.

No. See below.

> Also, does it support excluding subdirectories or files containing a particular string? For example, I have lots of videos named "VTS_02_1.VOB" and lots of images named "001.png" (of course, they are in different directories) and I don't want them to be counted as duplicates unless they are the exactly same file in terms of content.

Also no. By adding those feature we would get more and more like the right utility for jobs like this: ``find``. Instead we simply offer the ability to read files from stdin:

```bash
$ find -iname '*.png' | rmlint -
```

``find`` should solve your second problem, for your first problem you need to find a good tool.
The first step would be to find out what you need. *Similar filenames* is a very wide term.

> Lastly, I must have missed the option for specify location of rmlint.sh--how can I do so?

```bash
$ rmlint -o sh:/path/to/rmlint.sh
```

> Thank you. I will close this immediately if it is frowned upon, but I haven't found a place to ask these types of questions where I can get some answers.

No problem. Asking on [r/linux](http://reddit.com/r/linux) might be worth it, there are some ``rmlint`` users on there - including me.
