### ISSUE TITLE
Wrong permissions on the compiled binary and manpage

### ISSUE THREAD

**Issue by McBane-TO** [sahib/rmlint#216]
After compiling and installing the current master branch on Ubuntu 14.04 LTS without any errors, permissions on the binary were 750 (instead of 755), and permissions on the manpage were 640 (instead of 644). As a result, I was unable to run the binary or read the manpage until fixing the permissions.

Awesome program, btw!

**Comment by sahib** [comment]
Hi @McBane-TO,

I'm having some trouble to reproduce the behaviour you are describing. If I install rmlint the binary has a permission of 755 (rwxr-xr-x) and the manpage a permission of (rw-rw-r--). I also tried to run scons on Ubuntu 14.04 LTS, which is the operating system travis (our CI server) runs on. [Same result there.](https://travis-ci.org/sahib/rmlint/jobs/217844438#L789)

If you can reproduce the problem, I need some more information:

- Exact output and invocation of scons.
- What umask do you have set?
- ...anything else you think is worth to note.

**Comment by McBane-TO** [comment]
You are right - my umask is 0007, which must be the cause of the issue. Root's umask is still 0022, but doesn't seem to get transferred on "sudo".

As a suggestion, to cover all use cases, it might be worth adding a line to force permissions to 755/644 at the end of the install script.

Thanks for a great program, by the way!

**Comment by sahib** [comment]
> You are right - my umask is 0007, which must be the cause of the issue. Root's umask is still 0022, but doesn't seem to get transferred on "sudo".

[This actually seems to be the default behaviour of sudo.](https://unix.stackexchange.com/questions/265497/set-sudo-umask-apart-from-the-user-calling-it)
Well, learning about linux never stops...

> As a suggestion, to cover all use cases, it might be worth adding a line to force permissions to 755/644 at the end of the install script.

This is actually a good idea. Implemented as of 1e3c972.

> Thanks for a great program, by the way!

Noted, thanks. :smirk:

**Comment by SeeSpotRun** [comment]
Wouldn't it be better to warn rather than force the permissions?  Are there any cases where a different umask is desired behaviour?

**Comment by sahib** [comment]
Yes, some users might want to have a different umask for their user. It's however rather inconvenient for those cases that this umask also gets propagated when using sudo (and thus when installing e.g. binaries).
[Many PKGBUILDs e.g.  ](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/0ad#n50) enforce the permissions too by the way.
