### ISSUE TITLE
Weird NULL bytes in generated rmlint.json and rmlint.sh files

### ISSUE THREAD

**Issue by kholia** [sahib/rmlint#223]
I ran rmlint (built from the latest source) as,

```
$ ./rmlint /tank/movies /media/user/disk/movies
```

However, the generated `rmlint.json` and `rmlint.sh` files are not correct. They have NULL bytes at the start which is very weird. I am attaching a truncated version of the `rmlint.json` file, `rmlint.sh` is similarly affected.

[rmlint-bad.json.zip (has weird NULL bytes at the start)](https://github.com/sahib/rmlint/files/923421/rmlint-bad.json.zip)

It is hard for me to imagine how this could have happened.

**Comment by sahib** [comment]
Hey, @kholia.

Yes, that's definitely very weird, never had that issue. Two questions to clarify:

- *Latest source* means what branch? ``develop`` or ``master``?
- Is that happening always or only occasionally? Can you reproduce it?

**Comment by kholia** [comment]
I am using the `master` branch. I cannot reproduce the problem. Subsequent runs of `rmlint` worked just fine.

After filing this bug, I realized that the free disk space on the drive where `rmlint` was storing its output was close to zero. Maybe this can explain the weird behavior I saw during that particular run of `rmlint`.

Overall, I think that this issue can be closed.
