### ISSUE TITLE
rmlint.sh: "syntax error near unexpected token `}'" when there is nothing to do

### ISSUE THREAD

**Issue by alexbarton** [sahib/rmlint#230]
When there are no files to delete, the generated shell script (`-o sh:`) is invalid:

```
303: …
304: process_lint() {
305: }
306: …
```

which results in the following error message:

```
/tmp/rmlint.sh: line 305: syntax error near unexpected token `}'
/tmp/rmlint.sh: line 305: `}                                              '
```

The empty function body isn't allowed here.

This could be solved by always include a _no op_ like `:` or `true` into this function, regardless of other operations to perform, like this:

```
303: …
304: process_lint() {
305:         :
306: }
307: …
```

**Comment by sahib** [comment]
Thanks for finding this. Should be also fixed as of 6bd739b50da3305c405b109e877d37252b6f04dd.

**Comment by alexbarton** [comment]
Thanks for this super-fast fix, I'll give it a try!

**Comment by sahib** [comment]
We reverted to a state before the ``process_lint`` function due to #236, so this issue can be closed.
