### ISSUE TITLE
Characters not properly escaped or quoted in path

### ISSUE THREAD

**Issue by cwinebrinner** [sahib/rmlint#241]
> remove_cmd '/home/user/mnt/usb/Backup/Desktop [20110731]/Documents/Java Documentation & Books/JDK 6 Docs/jre/api/security/smartcardio/spec/package-list' '/home/user/mnt/usb/Backup/Desktop [20110731-alt]/Documents/Java Documentation & Books/JDK 6 Docs/jre/api/security/smartcardio/spec/package-list' # duplicate

> [  3%] Deleting:  /home/user/mnt/usb/Backup/Desktop [20110731]/Documents/Java Documentation & Books/JDK 6 Docs/jre/api/security/smartcardio/spec/package-list
> ls: cannot access '[20110731]/Documents/Java': No such file or directory
> ls: cannot access 'Documentation': No such file or directory
> ls: cannot access '&': No such file or directory
> ls: cannot access 'Books/JDK': No such file or directory
> ls: cannot access '6': No such file or directory
> ls: cannot access 'Docs/jre/api/security/smartcardio/spec': No such file or directory

**Comment by sahib** [comment]
Thanks for that report, but something is weird here. We *do* quote our commands. You can actually see that 
in the command you posted. Manually pasting that command will actually work fine.

You also forgot to tell us which version you are using, which operating system you're running and which shell you're using. Also the ``rmlint.sh`` in question would be helpful.

**Comment by cwinebrinner** [comment]
I am away from home and don't have access to an actual computer, so I am
going by memory here... I didn't include version information because, iirc,
the functionality was just added in v2.6.1.  Also, (again, going by memory
here), the issue seemed pretty obvious when I looked at the code, so I
didn't think information about my specific setup would be all that useful.
The $DIR passed to ls was NOT quoted .  Instead, the entire result of the
command was quoted.  If you need additional information, I can add it when
I return home.  The resulting rmlint.sh is 153MB, by the way.  >.>;

**Comment by cwinebrinner** [comment]
I just found the code using my phone and I believe the relevant bit is:

while [ ! "$(ls -A $DIR)" ]; do

I am by no means an expert in shell scripting, but it appears to me that $DIR isn't quoted there.

**Comment by sahib** [comment]
Sorry then, I also only had a quick look at your example; I should have spotted the ``ls``.
You appear to be right in all points otherweise. This code was added in the latest release also.

I'll push a fix tomorrow and a testcase for that (we have one, but that one didn't trigger...)

**Comment by SeeSpotRun** [comment]
Should be fixed by #242

**Comment by sahib** [comment]
Thanks for the PR @SeeSpotRun, had to make a small comment there, but looks good to me otherwise.

> It will only trigger if rmlint.sh is run with -c option

Right. Not my brightest hour.

**Comment by sahib** [comment]
Should be closed as of c9f5eaae8488fb5d62ab13911f6774c4406981c0 (and the followup commits).
