### ISSUE TITLE
RM_LINK_NO_DATA not defined in lib/utilities.h

### ISSUE THREAD

**Issue by adcosta** [sahib/rmlint#252]
when compiling from source... on non-linux systems that don't have HAVE_FIEMAP defined, line 1252 of utilities.c gives an error on RM_RETURN(RM_LINK_NO_DATA) because  RM_LINK_NO_DATA is not defined in lib/utilities.h

**Comment by sahib** [comment]
Thanks for the report; should be hopefully fixed by 124c776b256e398b61a79433235c077cfae89899.
Out of curiosity: What system are you running?

**Comment by adcosta** [comment]
macOS Sierra, but I use MacPorts instead of Homebrew and there is yet no port available, so I tried compiling from source... and I succeeded by defining RM_LINK_NO_DATA... blindly. 
Thanks for your prompt reply!
