### ISSUE TITLE
"ERROR: BUG: Number of remaining bytes is 18446744073709534538 (not 0)."

### ISSUE THREAD

**Issue by RyanMcCarl** [sahib/rmlint#256]
```
==> Note: Please use the saved script below for removal, not the above output.
==> In total 889473 files, whereof 135 are duplicates in 135 groups.
==> This equals 90.00 MB of duplicates which could be removed.
==> Scanning took in total 5m 23.567s. Is that good enough?

Wrote a sh file to: /Users/ryan/Dropbox/rmlint.sh
Wrote a json file to: /Users/ryan/Dropbox/rmlint.json
ERROR: BUG: Number of remaining bytes is 18446744073709534538 (not 0). Please report this.

```

Output of rmlint --version (installed with Brew on latest OSX):

```
version 2.6.1 compiled: Jun 16 2017 at [00:21:36] "Penetrating Pineapple" (rev unknown)
compiled with: -mounts -nonstripped -fiemap +sha512 +bigfiles +intl -replay +xattr -btrfs-support
```

**Comment by sahib** [comment]
Hello @RyanMcCarl,

thanks for the report.

Apparently one of the statistics counter underflowed (thus the very big number which is close to 2^64). 
For now, I think it's not a critical bug that will destroy your data, but we will look into it as soon as possible.

**Comment by SeeSpotRun** [comment]
It's almost certainly a mis-count related to a hardlinked file or xattr checksum pre-match.  `rmlint` doesn't count these in number of bytes remaining to process, but it's possible that it incorrectly subtracts the file size from the remaining bytes in some circumstances.  The question is which particular combination?

@RyanMcCarl any particular comments on your test case?  Does it contain hardlinks?  Are you using --xattr  options at all?  Anything else unusual?

**Comment by SeeSpotRun** [comment]
I don't think changing file sizes can generate this error; `rmlint` only tries to read to the end of the original file size.
There's a bug at https://github.com/sahib/rmlint/blob/812e9b48b23394165b8d247006d822080e07160d/lib/hasher.c#L211 that could cause over-reporting but only for `rmlint --buffered-read`.
Also there's a non-threadsafe (I think) counter update at https://github.com/sahib/rmlint/blob/812e9b48b23394165b8d247006d822080e07160d/lib/hasher.c#L211 but that's only the stats counter so can't cause this error.

**Comment by sahib** [comment]
> I don't think changing file sizes can generate this error; rmlint only tries to read to the end of the original file size.

Thinking of it, you're probably right. At least not this particular error. But the count might still be a small number, bigger than zero - which would still trigger this error/warning.

I'll have a look at your hasher PR soon. :+1:

**Comment by sahib** [comment]
We can also close this for now I think. Original issue probably was resolved by @SeeSpotRun,
although it couldn't be reproduced exactly.
