### ISSUE TITLE
Add support for "helper" apps

### ISSUE THREAD

**Issue by tomhoover** [sahib/rmlint#264]
rmlint does a great job of identifying true duplicate files; however, it cannot identify files that differ only in their metadata (e.g. Music files that are identical except for their ID3 tags, or Photos that are identical except for their exif data). It would be handy if rmlint could (optionally) pipe the file data thru a "helper" app (that would strip the metadata) before calculating the file hash. This would allow one to identify duplicate Music/Photo files that have had metadata inadvertently added by various "viewer" programs.

The following command will strip metadata (ID3 tags) from a Music file, and pipe the output to STDOUT:

    ffmpeg -loglevel 8 -i "$file" -map_metadata -1 -f wav -

The following command will strip metadata (exif data) from a Photo file, and pipe the output to STDOUT:

    exiftool -all= -o - "$file"

Would anyone else find this useful?

**Comment by sahib** [comment]
Hello @tomhoover,

I kinda like the idea, but would implement it a bit different.

In your current proposal it would be more of a pre-processing step. Every file that ``rmlint`` would hash
would be stored in a temporary solution until being processed - involving a lot of additional disk space.
You could also implement the helper program in a way that it returns a hash-value which is then picked up ``rmlint``. In your case we'd strip tags and then compute the ``sha256`` hash of the file, which is then written to ``stdout``. Same could be done to compute e.g. the [Soundex Hash](https://en.wikipedia.org/wiki/Soundex) or even [AcoustID](https://acoustid.org/). This would also open possibilities to compare images...

I think this would be more or less fit into our general architecture. ``hasher.c:rm_hasher_task_hash`` would "simply" call a user-defined command on the path and returns the size of the file as read bytes.

Any further thoughts on this @SeeSpotRun?

**Comment by SeeSpotRun** [comment]
Yes I like the idea.

It doesn't really fit with the current preprocess.c (match file sizes) and shredder.c (hash files in increments) algorithms.  So it would require a modified preprocess (only remove path doubles) and then a new helper.c session which hashes all files found by traverse.c and sorts them into groups.

**Comment by tomhoover** [comment]
@sahib, @SeeSpotRun,

I'm willing to help, but am a little rusty at C (it's been almost 20 years--the last thing I wrote in C was [HisWord Palmtop Bible](http://www.hisword.net/hisword/)). If you'd like to me to give it a whirl, would one of you give me a "high level" overview of rmlint's processes, and where would be the best place to plug in the new capability (this will save me from having to read thru the entire source). With a little help pointing me in the right direction, this is a good excuse for me to brush off the C skills again. :-)

**Comment by sahib** [comment]
@SeeSpotRun:

Oh, damn. Right, I totally forgot that those files do not need to have the same size anymore.

@tomhoover:

That would be certainly appreciated! More people knowing to change things in ``rmlint`` is always a good idea. The *usual* workflow of ``rmlint`` looks something like this:

0) Parse the commandline. Involved, but straight-forward. (``lib/cmdline.c``). The ``main`` is ``rm_cmd_main``.
1) Traverse all files given on the commandline (``lib/traverse.c``).
2) Files are being pre-processed and filtered (``lib/preprocess.c``).

     * Remove path doubles (e.g. files that were contained more than once on the commandline)
     * Remove files that have a unique sizes.
     * Remove files that are lint for a different reasons (e.g. broken symbolic links)
     * Filter files due to one of our many options.
     * (Pre-)sort files according to ``--sortcriteria``.
     * Bundle hardlinks (i.e. files with the same device/inode) into a single ``RmFile`` struct.
     * (...a few other things I do not remember top of my head...)

3) Files are now actually being read and hashed incrementally (``lib/shredder.c``). Actual algorithm is very efficient but also quite complex. At the top of the file you'll find a description.
4) Optional step if ``--merge-directories`` is given: Check if any of the traversed directories consist of
    duplicates only, and if so output them correctly (Not sure if your feature would work with this).
5) Pass the found files to the output module (``lib/formats.c``) which takes care of formatting the results on the terminal, as json, as shell script etc. 

In your feature you probably need to skip the size check of ``2``, make ``3`` do one large increment (?) with a specially purposed hash function (see ``lib/checksum.c``). Also some modifications in ``0`` will be required of course.

That was very high-level, so a lot of source code reading will still be needed. The code is mostly okay-ish readable, but we have a lot of options that require support for this new feature. You will most likely see a lot of broken unittests initially. :smile:

Those two pages of our documentation might also be useful:

* http://rmlint.readthedocs.io/en/latest/developers.html
* http://rmlint.readthedocs.io/en/latest/cautions.html

**Comment by z5tron** [comment]
I used -q and -Q to skip the mp3 tags information, e.g. -q 2048 -Q 0.9

**Comment by sahib** [comment]
I will close this for now due to lack of input. Feel free to reopen when any additional work here was done.
