### ISSUE TITLE
rmlint spams syslog when running with "-r" for btrfs clone deduplication

### ISSUE THREAD

**Issue by olifre** [sahib/rmlint#271]
Running the created `rmlint.sh` script, my syslog is flooded with lines like:
```
Dec 30 02:11:04 localhost sudo: pam_unix(sudo:session): session opened for user root by root(uid=0)
Dec 30 02:11:05 localhost sudo: pam_unix(sudo:session): session closed for user root
Dec 30 02:11:05 localhost sudo:     root : TTY=pts/23 ; PWD=/mnt/btrfs_backup ; USER=root ; COMMAND=/usr/bin/rmlint --btrfs-clone -r file_a file_b
Dec 30 02:11:05 localhost sudo: pam_unix(sudo:session): session opened for user root by root(uid=0)
Dec 30 02:11:05 localhost sudo: pam_unix(sudo:session): session closed for user root
```
and so on. 
It seems, even though I am running the script from a superuser shell, `sudo` is wrapped around each single invocation of `rmlint`, which does not only spam logfiles, but is also somewhat inefficient. 
Of course, that's the safest approach when being called without su / sudo, but is completely unnecessary when privileges are elevated anyways. 

A look in the created script reveals:
```
    if [ -z "$DO_DRY_RUN" ]; then
        if [ -n "$DO_CLONE_READONLY" ]; then
            sudo $RMLINT_BINARY --btrfs-clone -r "$2" "$1"
        else
            $RMLINT_BINARY --btrfs-clone "$2" "$1"
        fi
    fi
```
Maybe that could be changed to drop the `sudo` in case the `uid` is already `0`?

**Comment by sahib** [comment]
Hello @olifre,

surely a rather cosmetic issue to me, but fixing it doesn't break anything else.
Should be fixed as of e1b3e21. Can you verify it works for you?

**Comment by olifre** [comment]
Hi @sahib,
yes, I can confirm the issue is resolved with the `develop` branch, many thanks for the quick fix! 

I initially became aware of this problem due to the strange CPU load on my machine (that's why I would not call it cosmetic): Several percent of load from rsyslog an an i7 is unusal (I ran `rmlint.sh` on an SSD). In my case, I had several thousand of lines being written to syslog each second (three lines per file being deduped). 
Now, without invoking `sudo` each time and invoking the logging, it's also "feels" faster (did not do any measurements). 

Thanks a lot! 😄

**Comment by sahib** [comment]
> Now, without invoking sudo each time and invoking the logging, it's also "feels" faster (did not do any measurements).

Interesting. My gut feeling told me that it's probably not a big deal. Turns out I was wrong.
I ran this script once with and once without sudo, timings included:

```sh
$ cat /tmp/sudo.sh
#!/bin/sh

SUDO_COMMAND="sudo"
if [ "$EUID" -eq 0 ]
then
  SUDO_COMMAND=""
fi

for i in $(seq 0 10000); do
    $SUDO_COMMAND echo "Hello" > /dev/null
done
$ time sudo sh /tmp/sudo.sh 
sudo sh /tmp/sudo.sh  0,05s user 0,03s system 99% cpu 0,082 total
$ time sh /tmp/sudo.sh    # wtf.
sh /tmp/sudo.sh  45,13s user 23,10s system 99% cpu 1:08,64 total  
```

Today I learned. If I have a bit more time I'll see where the time goes...

**Comment by olifre** [comment]
> Edit: I'll close the issue for now since the original problem was solved.

Sure!

> Today I learned. If I have a bit more time I'll see where the time goes...

I just had a very quick look with:
```
strace -cf sudo echo "Hello" > /dev/null
```
(has to run as root). I get:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 57.12    0.004355           2      2313           lseek
  6.40    0.000488           3       154        10 open
  4.77    0.000364           3       142           mmap
```
the `lseek` appears to be a seeking through `/etc/group`, in which I have 156 groups on my system. 
Not sure why so many calls are needed there, it looks rather pathological in `strace`. One would probably have to read the sources of `sudo` (or maybe even `pam`) to find out whether that's really intended and necessary.
