### ISSUE TITLE
`-0` accept `NUL` byte as path item separator

### ISSUE THREAD

**Issue by sanmai-NL** [sahib/rmlint#273]
When GNU coreutils `find` prints paths with spaces, the input cannot be piped into `rmlint`. `find -print0` can represent paths with spaces unambiguously. Similarly to many other command line utilities, `rmlint` should have an option to accept a `NUL`-byte separated list of paths on standard input.

**Comment by SeeSpotRun** [comment]
I presume you mean `find -print0`?

I'm not aware of any utilities other than xargs that have a `-0` switch but that's not to say that rmlint shouldn't.  So you would want something like:
```
find -name "x*" -print0 | rmlint -T df -0
```
... where `rmlint -0` acts the same as `rmlint -` except that filenames are null-separated?

**Comment by sanmai-NL** [comment]
Yes and yes. :slightly_smiling_face:

**Comment by sahib** [comment]
This is merged to develop as of ce14289662793e7be4d79616f94cd69bb3d7f8d1.
