### ISSUE TITLE
MacOS: "cp: illegal option -- -" when trying to replace files with hardlinks

### ISSUE THREAD

**Issue by PeterDruckerPD** [sahib/rmlint#275]
When rmlint is set to replace duplicates with hardlinks, it shows the following error:

[  0%] Hardlinking to original:  /Volumes/Folder/File
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

My guess: The difference between the BSD (OSX) and GNU (Linux) implementation of the cp command. 

Any ideas?

**Comment by SeeSpotRun** [comment]
> My guess: The difference between the BSD (OSX) and GNU (Linux) implementation of the cp command.

Correct.  We use `--remove-destination` which is not implemented in [BSD](https://man.openbsd.org/cp.1)

We could rewrite from:
```
cp --remove-destination --archive --link "$2" "$1"
```
to
```
rm "$1"
ln "$2" "$1"
```
... but if the hardlink operation fails then the target file is deleted.

**Comment by aried3r** [comment]
Another option would be to detect this and ask people to install `coreutil` via Homebrew and then use `$(brew --prefix coreutils)/bin/gcp`. `gcp` might not be available if people use popular git aliases (this was the case for me, `gcp` is `git cherry-pick` on my machines).

**Comment by hsg777** [comment]
I ran "(brew --prefix coreutils)/bin/gcp. gcp" on terminal and gave me following error: nate@mac:~/gsrc$ $(brew --prefix coreutils)/bin/gcp. gcp
-bash: /usr/local/opt/coreutils/bin/gcp.: No such file or directory

I am using Mac OS High Sierra.

**Comment by sahib** [comment]
``rmlint.sh`` now longer uses ``--remove-destination`` since #290 is merged. This should solve this issue.
