### ISSUE TITLE
Dealing with cloud storage

### ISSUE THREAD

**Issue by vrossum** [sahib/rmlint#279]
Hi
rmlint is rather dangerous on cloud storage directories such as dropbox or owncloud.
It can delete files there, which will infuriate the people you share them with.

Can they be ignored by default, or can it there be a priority to keep the cloud files?

**Comment by SeeSpotRun** [comment]
You can protect them using `--keep-all-tagged`:
```
$ rmlint --types=duplicates --keep-all-tagged ~/dir1 ~dir2 // ~/dropbox
```
Paths after `//` are 'tagged'.

**Comment by sahib** [comment]
I think this can be closed since we wouldn't have a way to properly detect (all) cloud sync folders anyway.
In any case, this can be considered as a user error where ``rmlint`` could only help you partially.
