### ISSUE TITLE
feature request: resumable

### ISSUE THREAD

**Issue by checktravis** [sahib/rmlint#280]
I found [this](https://github.com/sahib/rmlint/issues/25) which might be what I am looking for but not sure. I am new to rmlint, but it seems like there is a use case for resuming the the initial rmlint command for given directory.

I try to work in small batches but I am going through several TBs of media files to find dups. My session ssh session crashed at around 160 GB of 2000 and when I went back it started over.

I am thinking of rsync, for example, that can resume interrupted transfers, can we resume interrupted rmlint sessions?

**Comment by sahib** [comment]
Hello @checktravis,

> I try to work in small batches but I am going through several TBs of media files to find dups. My session ssh session crashed at around 160 GB of 2000 and when I went back it started over.

Lesson learned: Use something like ``screen`` or ``tmux``. :smirk:
About what order of runtime are we talking about here?

> I found this which might be what I am looking for but not sure. I am new to rmlint, but it seems like there is a use case for resuming the the initial rmlint command for given directory.
> 
> I am thinking of rsync, for example, that can resume interrupted transfers, can we resume interrupted rmlint sessions?

We ended up implementing the suggesting in your link (via a sqlite database), but decided to remove it again later. The speed benefits were not big enough to justify the additional complexity in the software/workflow. However we have (sort of) three caching strategies for different needs:

- Write timestamp file and only check files with modtime newer than that timestamp.
- ``--replay``: Re-run based on the ``.json`` file ``rmlint`` outputs. This can be used to refine the results in subdirectories by using different options. This allows a somewhat interactive workflow.
- Saving checksums to the xattrs of a file. Second run will read them from there (See ``--xattr-write / --xattr-write). This is probably the closes to what you want.


Hope that helps.

**Comment by checktravis** [comment]
Since you mentioined timestamps, I searched the rtfd docs and found a great [example](http://rmlint.readthedocs.io/en/latest/rmlint.1.html?highlight=timestamp#examples) that looks promising. Thanks for the reply, this does help.

**Comment by ShapeShifter499** [comment]
I have a question about this. Is there any reason why one couldn't use the outputted rmlint.sh file to remove the already found duplicates and then run the rmlint again to find the rest of the files when rmlint was interrupted?

**Comment by sahib** [comment]
> I have a question about this. Is there any reason why one couldn't use the outputted rmlint.sh file to remove the already found duplicates and then run the rmlint again to find the rest of the files when rmlint was interrupted?

Sure, that will work. Doesn't save you from scanning (potentially big) files that are no duplicates again though.

**Comment by ShapeShifter499** [comment]
Ah I had not thought about large files, but at least it's good to know all the progress isn't entirely lost.
