### ISSUE TITLE
Docs: clone operation works on XFS too

### ISSUE THREAD

**Issue by jcharaoui** [sahib/rmlint#282]
One of the nice things about reflinks, compared to hardlinks, is that the file metadata can be independent for each instance. In my case, I'd like to deduplicate files belonging to many different users who are (mostly) all working on the same project, while the project's files remain 99% the same for all users.

As it's currently implemented, the `cp_reflink` function would probably wreck havoc to the project file's ownership and permission metadata which may differ for otherwise identical files.

**Comment by SeeSpotRun** [comment]
Hmmm I thought we already did that but I see the only metadata we preserve is `mtime`.

The clone option does preserve all metadata and so is probably what you want.

**Comment by jcharaoui** [comment]
Indeed, the clone option works. I'm using an XFS mount so I thought the option wouldn't work, even though I recompiled with XFS reflink support. The manpage (and docs) should probably be updated to add XFS (and OCFS2 maybe?) to the filesystems that support the clone opration.

**Comment by sahib** [comment]
Should be done as of #283.
