### ISSUE TITLE
Misaligned progress indicator in shell script

### ISSUE THREAD

**Issue by jokuNimi** [sahib/rmlint#289]
When running the ```rmlint.sh``` shell script, the percentage of progress is shown to the right of the %-sign and brackets. ```[  0%] 14Keeping:``` is shown instead of ```[  14%]Keeping:``` The issue is fixed for me by changing ```printf "${COL_BLUE}[% 3d%%]${COL_RESET} $PROGRESS_PERC"``` to
```printf "${COL_BLUE}[% 3d%%]${COL_RESET}" "$PROGRESS_PERC"``` in ```rmlint.sh```.

```rmlint --version``` outputs
```
version 2.7.0 compiled: Apr 26 2018 at [15:00:20] "Toothless Taipan" (rev unknown)
compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support

rmlint was written by Christopher <sahib> Pahl and Daniel <SeeSpotRun> Thomas.
The code at https://github.com/sahib/rmlint is licensed under the terms of the GPLv3.
```

**Comment by sahib** [comment]
Hello @jokuNimi,

this issue was already fixed in this PR: https://github.com/sahib/rmlint/pull/288
The fix will be in the next version. Until then a freshly compiled version from source will have the fix already.
