### ISSUE TITLE
Run the hash checker on two file systems in parallel

### ISSUE THREAD

**Issue by sqwish** [sahib/rmlint#291]
I don't know anything about the internals of rmlint but I am searching for duplicates on two external USB 2.0 drives and by watching the activity lights (and by monitoring on nmon) only one drive is being read at a time for an average throughput of 25-28MB/s read speed. That will double the amount of time vs. diff which can access both drives simultaneously when comparing files. I assume files are being hashed and their hashes compared so would it be possible to hash files on both drives simultaneously to further cut down the read times?

**Comment by SeeSpotRun** [comment]
The algorithm should read both drives simultaneously, provided you have at least as many cpu cores as disks.
I'm away from main PC at the moment but will get you to post some debugging info when I get back in a couple of days.

**Comment by sahib** [comment]
Additional note: You can find some docs on how ``rmlint`` works internally [here](https://github.com/sahib/rmlint/blob/master/lib/shredder.c#L47) in the meantime.

**Comment by SeeSpotRun** [comment]
Sorry for the delay on this.
My first guess is that maybe `rmlint` isn't picking up the fact that the two USB's are different physical disks.  Can you check the output of:
```
rmlint -T none --max-depth 0 -vv
```
In amongst all the debug output there should be a couple of lines identifying the mountpoints of your USB drives, similar to:
```
DEBUG: 08:49                      /run/media/username/FLASH DRIVE -> 08:48 /dev/sdd1    (underlying disk: sdd; rotational: yes)
```

If it's not picking up the fact that they are separate disks, you can force it by using an undocumented debugging/testing option:
```
rmlint --fake-pathindex-as-disk /path/to/usb1 /path/to/usb2
```

**Comment by sahib** [comment]
Closing due to lack of input. Feel free to reopen.
