### ISSUE TITLE
Please cache ETA (estimated time)

### ISSUE THREAD

**Issue by braian87b** [sahib/rmlint#292]
Please cache for a few seconds the ETA (estimated time) and avoid re-calculating for each update on screen, that will avoid that strange flickering/dancing on the text.

![preview](https://user-images.githubusercontent.com/6067040/42412219-542baa54-81de-11e8-87c2-1bafb2f6e790.gif)

I am using:

    rmlint -gvkm -q 100 -Q .05 /duplicates-to-be-deleted/ // /originals-to-be-preserved/

**Comment by sahib** [comment]
Interestingly you can fix this already by specifying ``-c progressbar:update_interval=250``.
What is it that's unpleasant to you? The rapidly changing number or the resizing of the line?

**Comment by braian87b** [comment]
The unpleasant is the back and forth dancing of the line... It just does not make sense to have an status upgrade faster than the eye can actually read, even worse to have the eye to follow it, hehehe.

**Comment by sahib** [comment]
@braian87b: Please try out 7a22e24b. ETA time display is now only updated every 500ms. Additionally, the display format includes a few more padding spaces to reduce the line noise.

**Comment by braian87b** [comment]
Thanks!
