### ISSUE TITLE
wish: should recognize maildirs

### ISSUE THREAD

**Issue by GregorZattler** [sahib/rmlint#298]
It would be helpfull if rmlint would recognize [maildir](https://cr.yp.to/proto/maildir.html) and [maildir++](http://www.courier-mta.org/maildir.html) directories as such.  This would mean (to me at last):

rmlint should not remove empty directories ./tmp or ./new or ./cur, and also not to link or merge them with other directories or treat them as duplicates of other directories, iff . contains the directories temp, new and cur.

As a result rmlint should handle maildirs as directories, but not their cur, new, tmp subdirectories.

Thanks for considering this wish and thanks for rmlint.

**Comment by sahib** [comment]
From my perspective this far too specialized and would require ``rmlint`` to have domain knowledge. With the same argument, you could implement logic for dozen of other programs / storages.

It's not possible for you to run ``rmlint`` only on the subdirectories you want it to run on?
If you need to run it on the whole maildir you can also tell ``rmlint`` to preseve (i.e. disallow modifications) on certain directories.

**Comment by GregorZattler** [comment]
Hi Chris,
* Chris Pahl <notifications@github.com> [2018-08-14; 00:50]:
> From my perspective this far too specialized and would require
> ``rmlint`` to have domain knowledge. With the same argument,
> you could implement logic for dozen of other programs /
> storages.
--text follows this line--
Email is especially wide spread, but OK thanks for
considering this.

> It's not possible for you to run ``rmlint`` only on the
> subdirectories you want it to run on?

I want to hardlink duplicate emails in my mail store.

> If you need to run it on the whole maildir you can also tell
> ``rmlint`` to preseve (i.e. disallow modifications) on certain
> directories.

I came up with:

find ~/Mail/ -type d | egrep -av "/tmp$|/cur$|/new$" | rmlint // ~/Mail/.notmuch/ -k  -T "all,-ed,-ef" -p  -c sh:handler=hardlink,symlink

but this does not find any lint, while

rmlint ~/Mail // ~/Mail/.notmuch/ -k  -T "all,-ed,-ef" -p  -c sh:handler=hardlink,symlink

finds

In total 1001600 files, whereof 28078 are duplicates in 27429 groups.

Ciao; Gregor
-- 
 -... --- .-. . -.. ..--.. ...-.-
