### ISSUE TITLE
error appeared during directory scan; "GLib.Error: g_convert_error: Invalid byte sequence in conversion input"

### ISSUE THREAD

**Issue by stonelike** [sahib/rmlint#303]
I had Shredder open via "rmlint --gui" in console, started a scan on two large directories (1TB each), and came back later to find;

> 
> 17:55:55 INFO     [tree.py:508] tree: Adding pack: 195/500
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/shredder/runner.py", line 282, in on_io_event
>     line, _ = source.read_line_finish_utf8(result)
> GLib.Error: g_convert_error: Invalid byte sequence in conversion input (1)
> 17:56:00 INFO     [tree.py:508] tree: Adding pack: 46/500
> 

...in the console output.  Shredder seems to have stopped processing the target directories (progress bar claims "running" but is empty, CPU usage is negligible), although it has not hung otherwise.  There were lots of "tree.py" notifications before the above text, and then none.  I am running a recently updated install of Arch Linux with i3 in an otherwise minimal Xorg install.  Both directories are on ZFS pools if that matters.

Thanks for your work on this very useful tool!

**Comment by sahib** [comment]
Hello @stonelike,

thanks for that report.

The output should contain the actual ``rmlint`` command that is being run in the background. Can you post this and try to run it standalone to see if it hangs? 

>  I am running a recently updated install of Arch Linux with i3 in an otherwise minimal Xorg install. Both directories are on ZFS pools if that matters.

Probably not.

**Comment by sahib** [comment]
Closed due to lack of input. Re-open if needed.
