### ISSUE TITLE
Empty directories are deleted whether or not -c is set

### ISSUE THREAD

**Issue by ieffedmybffjill** [sahib/rmlint#304]
just a minor issue :)

**Comment by sahib** [comment]
I was unable to reproduce this issue, are you using the latest ``develop`` branch?
If it still happens there, do you have an example to reproduce this?

**Comment by sahib** [comment]
I'm closing this, since it's not reproducible for me and no other input came.

Feel free to re-open if it happens again.

**Comment by ieffedmybffjill** [comment]
> I was unable to reproduce this issue, are you using the latest `develop` branch?
> If it still happens there, do you have an example to reproduce this?

Sorry for the delay!

I am not using the latest develop branch, I'm using latest stable branch. 

Is it recommended to use develop branch instead?

Thanks

**Comment by sahib** [comment]
> Is it recommended to use develop branch instead?

Not in the general case. If there are know bugs (which yours then probably yes) then using ``develop`` is preferable though. I usually ask this to see if we already fixed the bug which happens frequently.

In any case, the fix should arrive in stable after some time anyways.
