### ISSUE TITLE
Don't overwrite output files (rmlint.json, rmlint.sh, ...)

### ISSUE THREAD

**Issue by stloewen** [sahib/rmlint#306]
First: Thanks for writing, maintaining and publishing such an awesome tool!

While working with rmlint it already happened to me multiple times:
1. I ran a long-running rmlint job that gave me a rmlint.json and a rmlint.sh
2. I ran a `rmlint --is-reflink /file/A /file/B` or any other rmlint command and that  overwrote both `rmlint.*` files without confirmation thereby deleting hours of "work".

It would be really great if this behavior could be changed.
I think rmlint should either auto-increment a counter in the filename, backup the previous files or something similar. But overwriting the previous file no questions asked is, well... annoying.

**Comment by sahib** [comment]
You have a point there. Here's what I would do:

- Move old files to ``$name.<timestamp>``.
- Log a message whenever doing that. Warning includes hint to option to disable that.
- Implement option ``--no-backup`` to keep old behavior.

**Comment by sahib** [comment]
I've implemented this as of f4cd3af5. Please give it a try.

**Comment by sahib** [comment]
> Using current time as the timestamp is a little confusing. Maybe the files' mtime is a better fit?

``mtime`` might also be confusing since it might change. I see the timestamp more as a way to make sure the filename is unique and old files get sorted before new files. Semantic wise it's the time when the backup was made. I think a unique counter would tell you less.

> Keeping the file extension intact would be nice. Maybe $name.$timestamp.$ext

Good point. I was too lazy to do the required string manipulation yesterday. Will do. :)

> The test produced rmlint.json.2018-09-22T17:12:17.722494Z and rmlint.sh.2018-09-22T17:12:17.721248Z. The difference in the timestamps is confusing. Since these files are from one run they belong together; the filename should express that. Same would apply for mtime, I guess. Maybe a simple incrementing counter would be the better solution after all?

Hmm, yes. The different timestamps can be easily fixed, so I will probably go this way.

**Comment by stloewen** [comment]
> `mtime` might also be confusing since it might change. I see the timestamp more as a way to make sure the filename is unique and old files get sorted before new files. Semantic wise it's the time when the backup was made. I think a unique counter would tell you less.

true

> Good point. I was too lazy to do the required string manipulation yesterday. Will do. :)

No pressure. You're doing this for fun :wink:.

> Hmm, yes. The different timestamps can be easily fixed, so I will probably go this way.

Sounds great

**Comment by sahib** [comment]
Fixed as of f0fd64fa. If there's no more to add in the next few days, this issue will be closed.
