### ISSUE TITLE
question: does deduplication on read-only snapshots break incremental send/receive

### ISSUE THREAD

**Issue by stloewen** [sahib/rmlint#308]
I'm using btrbk to do regular btrfs snapshots and send them to another disk.
Unfortunately btrfs-send seems to break up reflinks so that my target snapshot is far bigger than my source snapshot.

rmlint allows deduplicating read-only snapshots with the `-r` option of the `rmlint.sh` script.
After doing so, btrbk will happily continue incremental backups of snapshots but I'm afraid there could be something broken in the background that I don't notice.

So my question is:
Does deduplicating read-only snapshots (subtly) break incremental send/receive?

**Comment by sahib** [comment]
@SeeSpotRun: Do you have an answer to this? You know more than me about ``btrfs``.

**Comment by SeeSpotRun** [comment]
It shouldn't break anything but, as you've seen, there are some efficiency losses via reflinks not being replicated on the receiving end.  There was a kernel problem prior to kernel 4.3 (https://github.com/markfasheh/duperemove/issues/50) but that should be fixed now.

From some limited reading, `btrfs-send` has (or at least had at some point) some limitations in terms of working out which source blocks are reflinks and how to apply them to the destination.  If two source files are reflinks before their first send then I understand that `btrfs-send` will send this information and the destination files will also be reflinks.  But if two already-sent are subsequently reflinked then I don't think it's guaranteed that send-receive will pick this up.

But I don't use send-receive so i haven't really had a play with it.

**Comment by stloewen** [comment]
I think you misunderstood my question. Let me try to rephrase it.

**Situation:**
I have a source HDD with a subvolume. I dedupe this subvol using rmlint to reflink duplicate files. Then I snapshot this subvol and btrfs-send the snapshot to my target HDD. Unfortunately the snapshot takes up far more storage on the target (756G on source; 834G on target), so obviously the btrfs-send did not transfer the reflink relationship. I'm not yet sure whether this is a bug in btrfs-send/receive.

So the snapshot on the source HDD is deduplicated but the same snapshot on the target is not deduplicated anymore. So I ran `rmlint.sh -r` on the target snapshot to deduplicate that as well (although in read-only mode). This seems to have worked and I can use this snapshot as a parent in follow-up btrfs-sends (using `-p`).

**My question:**
Is this safe to do and will it lead to consistent snapshots on the target in the long run?

I'm asking this because of the following experiment I ran:
I tried setting the target subvol (B) RW, modifying a file (X) and setting (B) to RO again, then using (B)'s source counterpart (A) as a parent for an incremental btrfs-send (A' -> B') and that worked without any errors, suggesting that the source (A') and the created target snapshot (B') are the same. However file (X) in the source snapshot (A') obviously did not have my introduced changes, while (B') had them (it inherited the change from (B)).

I'm just wondering whether maybe `rmlint.sh -r` makes changes to the snapshots metadata that will corrupt future incremental sends without btrfs-send noticing.


I know this is a very specific question, but maybe you (or anyone reading this) have some useful insights on this.

**Comment by SeeSpotRun** [comment]
All `rmlint.sh -r` does is ask the kernel to deduplicate pairs of files using the kernel's `FIDEDUPERANGE` ioctl (previously called `BTRFS_IOC_FILE_EXTENT_SAME`).  That in turn calls code written by the btrfs developers (https://github.com/torvalds/linux/blob/be65e2595b4c1fbeceba336d8ee83406726b1d8d/fs/btrfs/ioctl.c#L3630) which checks that the files are actually identical before changing one of the files to reference the data of the other.

All the cloning/deduping work is done by code written by the btrfs team.  It should therefore be safe to use but you might be well advised to check with them (https://btrfs.wiki.kernel.org/index.php/Btrfs_mailing_list).

**Comment by sahib** [comment]
Can this be considered to be resolved?

**Comment by SeeSpotRun** [comment]
Probably yes, in the sense that `rmlint.sh -r` doesn't break anything *per se*.  Breakage, if any, would only be due to flaws in the btrfs code, which is best reported elsewhere.
