### ISSUE TITLE
Comparing and removing specific files

### ISSUE THREAD

**Issue by p1839251** [sahib/rmlint#312]
Hello,
This is not a bug or a feature request, I just couldn't find a better way to reach you.
I've been thinking about this for weeks without any results.

If I have a directory tree like this: (Hopefully it won't collapse)

Root/
├── Subdirectory1
│   ├── file1.jpg
│   ├── file1.jpg.bak
│   ├── file2.jpg
│   └── file3.jpg
├── Subdirectory2
│   ├── file1.ogg
│   ├── file2.ogg
│   ├── file2.ogg.bak
│   └── file3.ogg
└── Subdirectory3
    ├── file1.mkv
    ├── file2.mkv
    ├── file3.mkv
    └── file3.mkv.bak

Can I compare only the *.bak files with the corresponding files so as not to remove any jpg, ogg or mkv files? Namely, I'd like to only remove file1.jpg.bak, file2.ogg.bak and file3.mkv.bak if they match with file1.jpg, file2.ogg and file3.mkv files. But I don't want to remove any ordinary files (like file1.jpg and file2.jpg) even if they match.
I wouldn't even compare the bak files, but I assume that's not possible.
If they were in separate folders I would tag the not bak files.

Thank you

**Comment by sahib** [comment]
There are ways to do that. The instructions below can be also used as more general tutorial.
The simplest way to do that is to create another directory, that has symbolic links to the files you want to deduplicate. One directory there will have only the backup files (``bak``) and one only the original files (``orig``). 

```bash
$ tree /tmp/root 
/tmp/root
├── sub1
│   ├── file1.jpg
│   ├── file1.jpg.bak
│   ├── file2.jpg
│   └── file3.jpg
├── sub2
│   ├── file1.ogg
│   ├── file2.ogg
│   ├── file2.ogg.bak
│   └── file3.ogg
└── sub3
    ├── file1.mkv
    ├── file2.mkv
    ├── file3.mkv
    └── file3.mkv.bak

3 directories, 12 files
$ mkdir /tmp/view && cd /tmp/view
# Copy all backup files to a directory called "bak":
$ mkdir bak && find /tmp/root -type f -iname '*.bak' -exec cp -r --symbolic-link --parents {} bak  \;
# Copy all other files (note the "!") to "orig":
$ mkdir orig && find /tmp/root -type f ! -iname '*.bak' -exec cp -r --symbolic-link --parents {} orig  \;
# Run rmlint and tell him that the preferred files live in orig and that we want to keep them (-k):
$ rmlint -f bak // orig -k -m
# Duplicate(s):
    ls '/tmp/root/sub3/file3.mkv'
    ls '/tmp/root/sub3/file2.mkv'
    ls '/tmp/root/sub3/file1.mkv'
    ls '/tmp/root/sub2/file3.ogg'
    ls '/tmp/root/sub2/file2.ogg'
    ls '/tmp/root/sub2/file1.ogg'
    ls '/tmp/root/sub1/file3.jpg'
    ls '/tmp/root/sub1/file2.jpg'
    ls '/tmp/root/sub1/file1.jpg'
    rm '/tmp/root/sub3/file3.mkv.bak'
    rm '/tmp/root/sub2/file2.ogg.bak'
    rm '/tmp/root/sub1/file1.jpg.bak'
# The script really contains only the removal commands for all backup files:
$ cat rmlint.sh | grep 'remove_cmd '
remove_cmd '/tmp/root/sub3/file3.mkv.bak' '/tmp/root/sub1/file1.jpg' # duplicate
remove_cmd '/tmp/root/sub2/file2.ogg.bak' '/tmp/root/sub1/file1.jpg' # duplicate
remove_cmd '/tmp/root/sub1/file1.jpg.bak' '/tmp/root/sub1/file1.jpg' # duplicate
```

You sadly need the latested ``develop`` branch for this to work because there was a bug related to handling/following symbolic links that was fixed. You can find guides on how to compile yourself in the documentation.

**Comment by p1839251** [comment]
Thank you very much for your help.
I haven't tried it yet, I've been just trying to interpret it and it seems to be a very good idea!
This will remove file3.mkv.bak and file2.ogg.bak if they happen to be the same, won't it?
I was thinking of using --match-with-extension but I'm afraid file3.mkv and file3.mkv.bak don't have the same basename. I guess, it should be file3.bak to work.

I'm currently using rmlint 2.7.0-2. Do you think this version is also affected?

I going to try it in a couple of days and I'll let you know how it worked.

**Comment by sahib** [comment]
> This will remove file3.mkv.bak and file2.ogg.bak if they happen to be the same, won't it?

Yes, only if they're equal. You can also use this recipe to create more complex "views" of your data without creating (lots of) additional storage space.

> I was thinking of using --match-with-extension but I'm afraid file3.mkv and file3.mkv.bak don't have the same basename. I guess, it should be file3.bak to work.

That would not have worked since ``rmlint`` sees the extension as ``.mkv`` and ``.bak``. Also, you'd still have the problem of deciding which file should be deleted and which not.

> I'm currently using rmlint 2.7.0-2. Do you think this version is also affected?

Yes, it is. Don't worry [compiling it yourself is not very hard](https://rmlint.readthedocs.io/en/latest/install.html#compilation).

**Comment by p1839251** [comment]
So here's the PKGBUILD that you created : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rmlint-git
This wouldn't work either as you mentioned because I need the latest develop branch.
Since I'm not much of a git person; is it enough to change the 

`git describe master --long --abbrev=6 | sed 's/^v//;s/-g[0-9a-z]\+$//g;s/-/.r/g'`

line to

`git describe develop --long --abbrev=6 | sed 's/^v//;s/-g[0-9a-z]\+$//g;s/-/.r/g'`

or I need to insert `-b develop` somewhere?

**Comment by sahib** [comment]
No, that's only the part that determines the package version.
Please compile from source as described in the docs. It's the quickest way and once the change is in master, you will be able to use the version from ``pacman`` again.

**Comment by p1839251** [comment]
It worked like a charm.
With this technique I'm able to do even more complex tasks. It was really helpful.
Thank you for your help!
