### ISSUE TITLE
Add support for env opts: AR, NM, RANLIB

### ISSUE THREAD

**Issue by fedan** [sahib/rmlint#316]
Hi.
I build rmlint with link-time optimization and use gcc-ar, gcc-nm, and gcc-ranlib.
Added strings to SConstruct:
```
diff --git a/SConstruct b/SConstruct
index 2d1d8aeb..eda0b27a 100755
--- a/SConstruct
+++ b/SConstruct
@@ -608,6 +608,17 @@ if 'LDFLAGS' in os.environ:
     conf.env.Append(LINKFLAGS=os.environ['LDFLAGS'])
     print(">> Appending custom link flags : " + os.environ['LDFLAGS'])
 
+if 'AR' in os.environ:
+    conf.env.Replace(AR=os.environ['AR'])
+    print(">> Using ar: " + os.environ['AR'])
+
+if 'NM' in os.environ:
+    conf.env.Replace(NM=os.environ['NM'])
+    print(">> Using nm: " + os.environ['NM'])
+
+if 'RANLIB' in os.environ:
+    conf.env.Replace(RANLIB=os.environ['RANLIB'])
+    print(">> Using ranlib: " + os.environ['RANLIB'])
 
 # Support museums or other debian flavours:
 conf.check_c11()

```

**Comment by fedan** [comment]
Reduces size, drop unused code.
See [https://gcc.gnu.org/onlinedocs/gccint/LTO.html](https://gcc.gnu.org/onlinedocs/gccint/LTO.html)
[https://gcc.gnu.org/wiki/LinkTimeOptimization](https://gcc.gnu.org/wiki/LinkTimeOptimization)

I'm using Gentoo, I have half the distribution with LTO assembled.

**Comment by sahib** [comment]
Okay, thanks. I've added it to ``develop`` as of 070d7c14.

Here's one example how I tried to enable it:

```bash
$ CC=clang LDFLAGS='-flto -fuse-ld=gold' CFLAGS='-flto' AR='llvm-ar' NM='llvm-nm' RANLIB='llvm-ranlib' scons -j4
$ du -hs rmlint
248K rmlint
$ CC=clang scons -j4 && du -hs rmlint
268K rmlint
```

As you can see, only the binary size changed slightly. Speed did not improve.
([Background](https://wiki.gentoo.org/wiki/Clang#Link-time_optimizations_with_Clang))

**Comment by fedan** [comment]
By the way, for clang it is better to use '-flto=thin'
