### ISSUE TITLE
Python2 or Python3 (dict' object has no attribute 'iteritems')?

### ISSUE THREAD

**Issue by oldschoolBavarianReferenceSystem** [sahib/rmlint#320]
I'm currently trying to pack rmlint for [Guix](https://gnu.org/s/guix) and stumbled upon a little problem:

I'm not sure if rmlint uses Python2 or Python3.

The test suites are using P3, they explicitly search for `python3-nosetests` in the SConscript and you suggest installing P3 packages on the [Installation page](https://rmlint.readthedocs.io/en/latest/install.html). Furthermore, the `gui/setup.py` explicitly searches `#!/usr/bin/env python3`

However, when I use the python3-scons package, I get the following error message:

```
starting phase `build'
scons: Reading SConscript files ...
AttributeError: 'dict' object has no attribute 'iteritems':
  File "/tmp/guix-build-rmlint-2.7.0.drv-0/rmlint-2.7.0/SConstruct", line 453:
    for key, value in COLORS.iteritems():
```

This looks like being a Python2-construct. And indeed, when I use the scons-python2 package, the build works well (besides of tests, but that is I think a dependency issue I have to work on).

Furthermore, if I patch it (s/iteritems/items/), it works well with scons (Python3).

To me, this looks like a forgotten artifact from a switch from Python2 to Python3, right? Is it save to patch it away? The header in SConstruct is `#!/usr/bin/env python` which could be python2 or python3, depending on the distribution. The "items" seams to be generally save for both 2 and 3 versions (see for example [here](https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems)).

Thanks,

Björn

**Comment by sahib** [comment]
Hi @oldschoolBavarianReferenceSystem,

this is indeed an oversight. I fixed this as of 4a1a43c9. Please tell me if there are other problems with Py3, which is indeed the preferred python version.

**Comment by oldschoolBavarianReferenceSystem** [comment]
Hi @sahib,
thanks for this quick fix! I already applied exactly this patch and it went through. I'm not finished with the tests yet, but until now it looks fine. If there is anything else, I will inform you.

Thanks!

**Comment by PatelAshish1** [comment]
As you are in python3 , use dict.items() instead of dict.iteritems()

iteritems() was removed in python3, so you can’t use this method anymore.

Take a look at Python 3.0 Wiki Built-in Changes section, where it is stated:

Removed dict.iteritems(), dict.iterkeys(), and dict.itervalues().

Instead: use dict.items(), dict.keys(), and dict.values() respectively

Founded At [Icetutor](https://icetutor.com/question/error-dict-object-has-no-attribute-iteritems/)
