### ISSUE TITLE
feature request : read file system from json

### ISSUE THREAD

**Issue by michaelcinquin** [sahib/rmlint#322]
Hi
I would like to request the --replay option is pushed further, so that rmlint gets the ability to use cache files to read the filesystem, this would give rmlint:
- the ability to do deduplication using an offline directory as a reference
- the ability to do deduplication accross (very) slow network connexions

Let's call this new option tree-cache

usage scenario is :
`rmlint --tree-cache c /media/someHardDrive/path/to/dirA`
-->  ~/Desktop/rmlint-tree-cache.json would have a listing of every file/dir in /path/to/dirA, complete with  relative path, depth 4, inode, disk_id, mtime ; as an extra option, it would also hold the hash of every file)

unmount someHardDrive, and run

`rmlint --keep-all-tagged --must-match-tagged --read-tree-cache /path/to/dirB //  ~/Desktop/rmlint-tree-cache.json

--> rmlint would do its work as if it had just read /media/someHardDrive/path/to/dirA, even though it was not online

hope you will be able to look into this!

**Comment by sahib** [comment]
> unmount someHardDrive, and run

Can you please elaborate how this fits in your usecase? i.e. why do you need to unmount and how is this useful compared to alternatives?

> --> rmlint would do its work as if it had just read /media/someHardDrive/path/to/dirA, even though it was not online

The current ``--replay`` feature only is able to run on cached files. It is not possible to mix this with "live" data for good reasons, both design and command line wise. It gets especially dirty when files changes on disk, while the cache is out of date. ``--replay`` can handle this to a certain degree, a new ``--read-tree-cache`` would introduce tons of complexity to the code base for little worth.

I feel like you have a problem that should have a different solution other than ``rmlint``.

**Comment by michaelcinquin** [comment]
Never mind, I'm working on my own-solution. Thanks for the great work anyway.
