### ISSUE TITLE
Delete during scan feature

### ISSUE THREAD

**Issue by braian87b** [sahib/rmlint#330]
**Hi, Can you add a flag to make the deletions during scan?**

to avoid running later `./rmlint.sh -cd`

Currently I have to add it as `rmlint [command flags] ; ./rmlint.sh -cd` but is annoying to wait until a big .sh file is generated as waste, even during so much time the filesystem could have many changes that could make the file useless/outdated.

I tend to compare 2 different folders of about 1tb that have almost each file equally except for some. (backup archiving)

**Comment by SeeSpotRun** [comment]
I think it's a good idea.  It does go against the `rmlint` philosophy of a non-destructive run followed by [opportunity for] manual check followed by destructive batch file.  So Chris may not like it.  But there are probably plenty of users (like you) who bypass the manual step anyway.  So why not make it a feature?

I suspect there will be slight speed gain too, since the metadata of the duplicate file is probably already in RAM when the delete command is called, and the (potentially large) `rmlint.sh` file doesn't have to be written.

Possible implementation syntax:
```
$ rmlint --execute -o pretty
> Warning: this will:
> * delete duplicate files, empty files, empty dirs, bad symlinks
> * strip non-stripped binaries
> * attempt to repair bad user, group ID's
> Type Y to confirm?  Y
ls a.txt
rm b.txt
...
```

... and a silent option:
```
$ rmlint --execute --nowarn -o pretty
ls a.txt
rm b.txt
...
```

**Comment by SeeSpotRun** [comment]
Haha beaten to it.  And I was correct, Chris doesn't like it.

**Comment by sahib** [comment]
> Haha beaten to it. And I was correct, Chris doesn't like it.

You know me too well, old friend. :joy: 

> [...] So why not make it a feature?

Mostly because it is possible already. And to not hurt my german security-loving soul. :stuck_out_tongue: 

> I suspect there will be slight speed gain too, since the metadata of the duplicate file is probably already in RAM when the delete command is called, and the (potentially large) rmlint.sh file doesn't have to be written.

It might even get a bit slower since deletes are writes, and writes mess with the file system cache.
Also, the file metadata should be (mostly) cached also after the ``rmlint`` run. But yeah, only speculation without any numbers.

Let's see what @braian87b says.

**Comment by SeeSpotRun** [comment]
Sigh, philosophical differences.  No wonder forks happen.  And no, that's not a threat (haha bet you wish it was!).

> It might even get a bit slower since deletes are writes, and writes mess with the file system cache.

Yes I didn't really think that through.  Unless fs and mount options allow for delayed metadata writes (which seems unlikely).

> Let's see what @braian87b says.

It's probably pertinent to see how many other users post here saying they'd also like to see this 'feature'.

**Comment by braian87b** [comment]
Ok, I wil write down my comment here and before that read all the comments...
I'ts not the rmlint responsibilty to avoid auto-inflidged injuries of users... then, why rm command exists at all?... add a interactive question to the user when him ask with --delete-during and --force-delete-during to avoid that question...
even rsync have MANY deletes flags, to delete during, after, at the end, etc... 
if you use a tool specifically to delete duplicated files it is a good thing to add a feature tu be able to delete them when needed (sometimes is really useful to delete during and not in an after process)

People have to have backups, even more than one backup that is the only thing to avoid screw ups...

Anyway, Thanks! for this great piece of software that I use almost every day! and for worrying about your users!

**Comment by braian87b** [comment]
Ok, I read it all... 
we could also have a `delete-during-rmlint` command, and users will have to write that entire binary name that describes the terrible thing that will do and read it on loud on their minds muajaja.

**Comment by sahib** [comment]
I've slept over a (few) night(s) now over it... and I still don't like it.

> I'ts not the rmlint responsibilty to avoid auto-inflidged injuries of users ... then, why rm command exists at all?.

No, but it's a good thing to make it harder to shoot yourself. Does your car have airbags? It still exists. :smirk: Also even ``rm`` will stop and ask back when doing ``rm -rf /``.

So, to sum up: This feature request would add a new option to ``rmlint`` (which has a huge amount of options already and I'd much more prefer to remove some of them than adding more) that would add something that is already possible (see my first comment) **and** is probably not reasonably faster than
``rmlint [options] && ./rmlint.sh -dc`` **and** would take quite a bit code to add (writing the ``sh`` output into memory and execute in parallel and crossing fingers that this does not affect the parallel run).

That's a no from me.

> People have to have backups, even more than one backup that is the only thing to avoid screw ups...

You have a point there and I wish it would apply. Sadly, the reality is often different and having to restore a backup is annoying itself. Also thanks for reminding me to start my backups.


> we could also have a delete-during-rmlint command aside rmlint, and users will have to write that entire binary name that describes the terrible thing that will do and read it on loud on their minds muajaja.

I'd prefer solving a sphinx' riddle or some sort of calculus. :smile:

> Anyway, Thanks! for this great piece of software that I use almost every day! and for worrying about your users!

Thanks for taking the time to write us!

**Comment by vvs-** [comment]
Yet another argument against it: if such destructive code would exist in rmlint then it would be another reason to be paranoid about bugs which could destroy your data. Right now I'm at least pretty sure that no matter how many bugs are there it wouldn't corrupt my data in any case :stuck_out_tongue:
