### ISSUE TITLE
Better document how to use --xattr-* flags, and more detail on what they do

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#336]
I've read pretty much every reference to --xattr-write, --write-unfinished, and --xattr-read ever written on the internet. I think I know how to use it, but am not sure, and considering how robust (complex) rmlint is, I'm a little hesitant to start running it on 10tb of data, for example what other options should I include with --xattr-write, to prevent deleting duplicates? (Which I very much don't want to do.) I could set up a test bench to figure it out, but it would be great--for other users too I think--if the documentation were more clear, and included at least one real-world examples. Rmlint has legendary great documentation, these features are strangely lightly glossed over.

This my current understanding for deduping a large Btrfs data set, is this about right?

First run:
rmlint --xattr-write --write-unfinished --algorithm=sha256 --no-followlinks --hidden --output=summary /mnt/btrfs/array

Second run (generate script to dedup Btrfs):
rmlint --xattr-read --types="duplicates" --rank-by=pHma --sort-by=snmpa --no-followlinks --hidden --output=summary --output=rmlint.sh --config=sh:handler=clone,reflink --progress /mnt/btrfs/array

Several uncertainties I have, e.g.:

- Will the first run, by default, delete duplicates or do any other default actions? Or just calculate and store hashes?
- Can the reading and writing flags be combined on one command invocation? (So that unhashed files will be hashed and stored in xattrs and otherwise processed as usual, but files with existing xattrs won't have to be hashed again. In other words, does it really require two separate steps?)

And about the detail of what the flags do. For example, I'm assuming (and think I read somewhere) that the files' mtimes are also stored xattrs along with the hash, at the time of hashing? (Which also seems to be confirmed in xattr.c.) Obviously it has to be stored somewhere, otherwise how would rmlint know, quickly, if the file changed and should be rehashed? (At least in a filesystem-agnostic way.) And since one of the main benefits of storing the hash in file xattrs is that the hashes can survive copying to other volumes, etc. Is anything else stored?

**Comment by sahib** [comment]
> - Will the first run, by default, delete duplicates or do any other default actions? Or just calculate and store hashes?

It will not do any destructive action. It will write the calculated checksums to the xattr of all files it processed. You could as well use the output (``rmlint.sh``) of the first ``rmlint`` run to actually delete your files.

> - Can the reading and writing flags be combined on one command invocation? (So that unhashed files will be hashed and stored in xattrs and otherwise processed as usual, but files with existing xattrs won't have to be hashed again. In other words, does it really require two separate steps?)

Yes. You don't actually need a multi pass run. You can specify ``--xattr-read`` and ``--xattr-write`` at the same time. I agree that the documentation on this is a little sparse and needs to be improved with a more detailed example.

> Is anything else stored?

Beside the hash (and the type of hash), only the modification time, which is used as a safe guard for identifying outdated checksums. You can check those attributes via ``getfattr``:

```bash
$ getfattr -d <path>
user.rmlint.blake2b.cksum="edfc1e2c01521aef084144363c9a7a1e7ab868f098724a716fefe6a2dff731842714ab6558b135c91009e0ac8e14c3dd8b69ebad9ae015341f31aeb41eb1fc94"
user.rmlint.blake2b.mtime="1499027028,707885504"
```

**Comment by jim-collier** [comment]
Fantastic, thanks.
