### ISSUE TITLE
Is --xattr-* and --cache really slightly risky, for the use case of Btrfs deduplication?

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#337]
I understand that these flags could be risky for, say, the use case of deleting duplicates on an ext4 filesystem. As the documentation states, if a particular file satisfies the following criteria, a false positive could result, and a unique file could be deleted:

1. The file's checksum has been precomputed either with --xattr-write or --cache.
2. The file's content changes, but not its mtime. (I know of at least one Linux program that purposely does this [optionally], a photo EXIF editor. It explicitly resets the mtime to what it was before.)
3. rmlint is run again, with --xattr-write or --cache, to delete duplicates.

But in the case of deduplicating Btrfs, I believe the only risk is just some extra cycles by the kernel in trying to deduplicate files that aren't actually duplicate. But no actual data loss would occur. (I think.) This is because the relevant kernel-level Btrfs ioctl actually performs binary comparison before deduplicating a block, and won't if they don't match.

If this understanding is correct, that could be an extremely useful to be clearly documented!

**Comment by sahib** [comment]
> But in the case of deduplicating Btrfs, I believe the only risk is just some extra cycles by the kernel in trying to deduplicate files that aren't actually duplicate. But no actual data loss would occur. (I think.) This is because the relevant kernel-level Btrfs ioctl actually performs binary comparison before deduplicating a block, and won't if they don't match.

I will have a second look at this, but I believe that you are correct on this.

> If this understanding is correct, that could be an extremely useful to be clearly documented!

Agreed.

**Comment by sahib** [comment]
At least [here](http://man7.org/linux/man-pages/man2/ioctl_fideduperange.2.html) there is no mention of any dangers regarding "too many" calls. I deem it safe and added a comment to the manpage for that (4241b9ac).
