### ISSUE TITLE
Clarify documentation: Does just moving a file invalidate it's entry in --cache file?

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#339]
For example, if you are only storing something along the lines of:

- Fully qualified real path
- Relative path
- Filename
- mtime
- ctime
- File size
- Computed hash

Then everything but the hash is really just metadata in the end, and if any one changes, including just the path, then it stands to reason that its hash would have to be recalculated, if not treated as a new file entry outright.

This could make moving or renaming a top-level directly extremely expensive for subsequent runs with the --cache flag, essentially nullifying its benefits at least for that run (and turning a potentially minutes-long run into a days-long run).

But maybe there's additional information you are storing? Or could store. For example:

- inode
- Existing Btrfs csum

Adding those into the mix, you could very reliably consider a file to be the same, if inode, csum, ctime, and size are all the same, regardless of file name and path. (And the lookup in the cachefile itself would then be done on some concatenation of ctime, filesize, inode, and csum; rather than filespec.)

This would involve low risk. A false positive would mean not deduplicating a file that was in fact a true candidate. A false negative would mean unnecessarily hashing it again. But even though the Btrfs csum is only 32-bits with higher odds of collision, combined with mtime and filesize would make for very low odds of either false outcome happening.)

And as mentioned in a previous issue, the risk of data loss in sending files to the kernel clone ioctrl that aren't actually duplicates, is low since Btrfs won't dedupe blocks that aren't actually binary duplicates.

**Comment by sahib** [comment]
I'm slightly confused on this one: What ``--cache`` flag are you talking about? Could it be that you are using an outdated ``rmlint`` version? We had a SQLite based ``--cache`` option quite some time ago, but removed it due to the small benefit, high complexity and notoriously silly edge cases.

**Comment by jim-collier** [comment]
I actually have no idea how or where I got that idea! For some reason I thought you had a "--cache" option to read and write filnames, metadata [e.g. mtime], and checksums to a json file. I have v2.6.1 on this machine, but am pretty sure I'm on 2.8.0 on the machine with the big Btrfs array to dedup. In my defense it was very late and I was bleary :-/

This could be a useful feature though, so I'll create a new feature request. (With a differentiating idea that is hopefully useful enough that it's not a rehash [no pun intended] of your previously dropped sqlite3 cache feature.)
