### ISSUE TITLE
Feature - non-fragile hash cache that user can locate on an SSD.

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#340]
I know you had a sqlite3 cache database feature in an earlier version, that was yanked.

But hear me out, this is hopefully different, and in principle could increase performance and longevity by avoiding read/write thrashing on spinning disks when calculating and storing checksums in extended attributes. (If the user locates the persistent cache file on a different disk, particularly an SSD, and as compared to storing checksums in extended file attributes.)

But more importantly, with this idea, the whole point of storing hashes in a separate persistent cache file (for the same reasons you'd do so with xattrs) doesn't break just because the user renames or moves a folder in between runs.

Duperemover, for example, has a "--hashfile" flag (also in a sqlite3 db), but it's index is the full file path/name of each file. Which seems like a sensible design choice, but it makes the solution pretty brittle. For example, just renaming a high-level directory on a large volume, would invalidate much of the cache, and turn the next "incremental" run from a potentially minutes-long affair, to potentially days-long.

So the index needs to be something quickly and easily readable from each file, that doesn't involve the path or filename, and that results in a fairly unique fingerprint. (It doesn't have to be perfect, just outweigh the costs. But I think it would be perfect.)

The path and filename are therefore irrelevant and don't even need to be stored.

(BTW, I suggested also including "Btrfs csum" as a stored attribute in an earlier issue, but that's not actually a thing. As you probably know it's (informally?) known as "crc32", a 32-bit checksum. But it's calculated and stored at the block level, not file, so not relevant in this case. The CRC is meant to be fast, not robust, as the kernel performs more expensive checks for uniqueness later, if it first passes through the rough crc filter.)

The sqlite3 schema might look something like:

```
fingerprint TEXT PRIMARY KEY  /* In form of "filesize_mtime_inode" */
hash_type INTEGER
hash BLOB
```
Where 'fingerprint' is the magic: It could just be a simple delimited string concatenation of easily readable file attributes, such as filesize, mtime, and inode number.

Alternatively, 'fingerprint' could be some binary concatenation of those values, but given the low entropy relative to max field size needed for each of those three items (they'd have to be bit-aligned to fixed widths), that doesn't seem like it would efficient. (Unless that binary concatenation is then itself hashed to a smaller datatype. Now we're getting meta.)

Specifically for the Btrfs use-case, it's OK if 'index' is not super-robust, it just needs to allow for higher performance than the cost of the (presumably) very low odds of false positive or negative matches. But at least to my understanding of inode numbers, this could actually be pretty robust.

The cost of a false positive match would just be submitting files to the kernel for deduplicating, that it tries but can't deduplicate because the blocks aren't actually the same.

The cost of a false negative would be that no cached match is found (and the existing entry presumably discarded at some point), a new entry is created, and the file is hashed again unnecessarily.

**Comment by sahib** [comment]
> But hear me out, this is hopefully different, and in principle could increase performance and longevity by avoiding read/write thrashing on spinning disks when calculating and storing checksums in extended attributes. (If the user locates the persistent cache file on a different disk, particularly an SSD, and as compared to storing checksums in extended file attributes.)

Sadly, your proposal has a fundamental issue: Proposals should first identify a problem, then figure out some valid use cases where this problem is a pain and then outline a solution. You jumped directly to building a solution (in great detail!) without stating the exact problem that you want to solve.

Don't get me wrong, I appreciate long, well written texts and food for thought. I just see some issues here.

> But hear me out, this is hopefully different, and in principle could increase performance and longevity by avoiding read/write thrashing on spinning disks when calculating and storing checksums in extended attributes. (If the user locates the persistent cache file on a different disk, particularly an SSD, and as compared to storing checksums in extended file attributes.)

This part does not really state what problem you're going to solve is. I guess you're going for higher speed while reading duplicates. While this is a good goal in general, you should always check first if you actually have a problem that needs to be optimized away. Do you have any speed issues? Over the course of years I learned that people often underestimate the general performance of file systems and linux' file system cache, while they overestimate the performance of caches they've built themselves. Remember what some famous engineers said about [premature optimization](http://wiki.c2.com/?PrematureOptimization).

> But more importantly, with this idea, the whole point of storing hashes in a separate persistent cache file (for the same reasons you'd do so with xattrs) doesn't break just because the user renames or moves a folder in between runs.
> 
> So the index needs to be something quickly and easily readable from each file, that doesn't involve the path or filename, and that results in a fairly unique fingerprint. (It doesn't have to be perfect, just outweigh the costs. But I think it would be perfect.)

Tracking renames is notoriously hard. I tried myself and found this to be hard quite in my [side project brig](https://github.com/sahib/brig/blob/master/catfs/vcs/mapper.go). Especially if you want to do it a way that does involve false mapping of matches. Your argument here is that it does not need to be perfect, since double deduplication does not hurt in case of ``btrfs``. That's right, but ``rmlint`` is more than ``btrfs`` and that rename tracking would need to happen in code paths that do not involve ``btrfs``.

> The sqlite3 schema might look something like: [...]

Regarding using a combination of mtime/size/inode as key: The inode is not highly relatable, especially for caching purpose. Any FUSE based filesystem (for example) might give out non-unique inodes or whatever it feels like this day. Especially file systems like NFS might give you different inodes for the same file between remounts (not sure if they fixed that already). Also, you'd also need a ``device_id`` since inodes are only (usually) unique on the same filesystem (i.e. a file in ``/tmp`` might have the very same inode as in ``/home``).

So, in total: No. Those kind of issues are the reasons why we removed ``--cache``.

**Comment by jim-collier** [comment]
Thanks for the feedback, thoughtfulness, and your time!

> Sadly, your proposal has a fundamental issue: Proposals should first identify a problem, then figure out some valid use cases where this problem is a pain and then outline a solution. You jumped directly to building a solution (in great detail!) without stating the exact problem that you want to solve.

... 

> This part does not really state what problem you're going to solve is. I guess you're going for higher speed while reading duplicates. While this is a good goal in general, you should always check first if you actually have a problem that needs to be optimized away. Do you have any speed issues? Over the course of years I learned that people often underestimate the general performance of file systems and linux' file system cache, while they overestimate the performance of caches they've built themselves. Remember what some famous engineers said about [premature optimization](http://wiki.c2.com/?PrematureOptimization).

Fair enough. The benefits of --xattr-* surely outweigh the costs (time will tell), but there _are_ costs. (And philisophically, even unfairly perceived costs can be worse for any product or service, even free/libre ones; and most people still want their efforts to be appreciated and improve lives in some way.) First, I do want to be clear that I'm grateful for your efforts, and for rmlint existing, and that its so robust. And also, that --xattrs-* is a brilliant idea. Portably storing hashes with the files, is genius. Files can be moved, folders renamed, and rsync -X'ed to completely different hosts, without ever having to be rescanned.

And to backtrack a bit first, some thoughts on the term "caching". Storing checksums (arguably) isn't "caching". It's persistent data storage, used potentially over the span of years, to drastically cut the grinding on HDDs from days or weeks--down to minutes or hours. I can see how the argument could be made that it's a form of caching, but I think that's stretching the definition to the point where it could be argued that _any_ computer storage and filesystem metadata could also be considered "caching". (Most filesystem design effort, research, and decisions, goes into making IOPS and throughput remotely tolerable. Which often involves computing things only once when something changes, and storing the results as metadata somewhere.) I'm not suggesting that a "hash cache" be called something else, just that it doesn't serve the same purpose as a general-purpose OS disk caching. And while I wholeheartedly agree about premature optimization and unnecessarily redundant caching schemes, domain-specific storage architectures are often a specific and necessary requirement when it comes to the performance of highly iterative, long-running tasks that stress hardware.

But on to specific costs. First, writing data to each and every file--millions upon millions of them--has a "disconcerting" factor to it. Even if it's only extended attributes and not the data itself, and even if, say, an array scrub essentially does the same thing regularly. (Most fears are unfounded--or at least inconsistent with same or greater risks in other areas of life--if you really inspect closely.)

Secondly, for my 10tb net storage yield (from 20tb raw), it takes a _week_ to dedup the whole thing, and stresses the hell out of the hardware. The disks get extremely hot, even with robust housing and cooling. Any time I do days-long stuff like this (over 20 years), the disk failure rate skyrockets. Not only does it get expensive, any operation like that puts my data at significant risk. (And restoring 10tb from cloud backup is an "inconvenience" to put it mildly.) And in my experience, sustained writes overwhelmingly cause more HDD failures than sustained reads. I have stacks and stacks of dead hard drives just from the last few years, waiting to be turned into windchimes by my kids. (If I kept them in total from the last 20 to 30 years, they could have provided enough metal to build a space station.)

I have the same issues with other arrays, including a ~30tb [raw storage] ZFS server in a 20-bay 4U server chassis with jet-engine-like fans. It's just the nature of it, and the whole reason for redundant storage. It's why that ZFS server is a stripe of 3-way mirrors. I can't tell you how many times that saved my neck, when it literally came down to multiple drive failures on the stress of a resilver or other hours or days-long writes, including multiple occasions of two failures on the same mirror. (Yikes! Multiple times. But so far, knock on wood, not yet three on any one mirror.) With that many drives and that much redundancy, you can imagine that even with a pretty robust replacement/upgrade regime, some of the disks are pretty ancient. (But brand-new ones run a higher risk of sudden failure upon being stressed. They weed themselves out quickly, and if they last more than several months, usually make it 5 more years easily, and then die with lots of complaining and warning. Backblaze and Google data seem to confirm my less objective observations.)

I've conceivably gone through 1,000 HDDs, I'm not sure. Even if it was half that, the one trend I've noticed is that if they are going to fail, more often than not it's with lots of writes, and heavy random seek thrashing. But mostly writes. I can't tell you how many times I've limped along indefinitely on highly damaged arrays in read-only mode, while I use it to build a new array...which keeps failing repeatedly due to disks dying under heavy write loads while not yet having enough redundant mirrors to survive.

So, ANY reduction in I/O, particularly and especially writes--however tiny--adds up in a significant way when it stacks up over millions of files and TBs of data. (Which is on track to becoming close to a petabyte by 2020 of highly redundant data.)

If reads and writes can be isolated and separated to different media (even if not an NVMe SSD) and parallelized, big performance wins are pretty much guaranteed, disk caching or not. I once wrote a program to copy a bunch of sequential data from one drive to a different staging directory on the same drive. (Which was a thing I had to often do a while ago for a specific use case.) Rather than copy to and from the same disk, I first copied it to a _different_ spinning disk, then "moved" [copied then deleted] it from that disk back to the same original disk. (There are or at least were other third-party GUI programs that you could configure to do that for same-disk copies, in a more generic way. But this had to be scripted.) Objective testing showed over a 8x improvement or more, depending on fragmentation levels, for that specific use case. And that was with ~14GB RAM for disk caching which was insane at that time. (The dawn of 64-bit computing.) Generalized OS-level disk caching is typically not designed nor tuned for days-long sustained combination of massive reads and not insignificant quasi-random writes, and doesn't necessarily optimize the queue of read and writes in that scenario, especially when perpetually full.

Granted, that's all speculative...but highly informed speculation from what could easily be considered "a leading expert on spinning metal & magnets-based data storage". (In my mind :-D ) I know that's not low-enough hanging fruit for someone working a day job and doing this for free (or even if I were a valued paying customer). And some random guy's opinion that differs from yours--who hasn't even contributed to the code--ultimately will never matter THAT much. But, if and when the opportunity comes to think more about it, maybe that implanted idea will stick. "Inception." I realize I could implement the idea myself. But for someone who hasn't programmed in C in 30 years and doesn't understand the modern paradigms used--nor is familiar with the existing code base--that's not a realistic option.

> Regarding using a combination of mtime/size/inode as key: The inode is not highly relatable, especially for caching purpose. Any FUSE based filesystem (for example) might give out non-unique inodes or whatever it feels like this day. Especially file systems like NFS might give you different inodes for the same file between remounts (not sure if they fixed that already). Also, you'd also need a `device_id` since inodes are only (usually) unique on the same filesystem (i.e. a file in `/tmp` might have the very same inode as in `/home`).

I was thinking (implicitly) of only a single-volume use case. E.g. one hash cache per volume, left up to user to define on command line. I know you need to consider more but I hadn't even thought of FUSE. (In fact since you mentioned it, I realize I could do some serious deduping of several FUSE-based filesystems I regularly use--encFS specifically.) And NFS--that's insane! Is that even a thing, deduping over NFS? I think the program should purposely segfault just to teach the user a lesson or at least not clog up the network. But an NFS use case would be even more reason to "cache" hashes locally, if that were possible in a non-brittle way with consistent "inodes". (Not only did I not know NFS doesn't present consistent inodes, I didn't even know NFS presented inodes at all. I figured network storage was far more abstract than that.)

But even with non-unique (but at least not arbitrarily changing) inodes, they wouldn't have to be highly unique--any more than mtimes and filesizes would have to be unique. Just "unique enough" so that the combination of all three, would be "pretty unique". (And also not arbitrarily changing.) There'd be some threshold of uniqueness, obviously below which the cost wouldn't be worth the payoff. I'd wager the combination of all three would be far and away above that threshold. Especially for Btrfs and Ext4 volumes. Again, speculation. The code could detect filesystems and compare to a list of those know to have crappy inode design, e.g. FUSE if that's the case, and suggest against it. Dropbox only works on ext4 now--maybe for similar reasons. (And having certain features of a tool limited to certain capabilities based of a user's host configuration--even arbitrarily with no immediately obvious reason--is nothing new.)

Anyway. I'm not trying to change your mind or be unappreciative of your outstanding work. Just maybe planting the kernel of an idea. (Just don't go sticking your head on a train track.) No need to respond to all this in kind.

**Comment by jim-collier** [comment]
I thought of a way to test the performance of storing hashes with the files, vs. on a separate physical volume e.g. SSD. Slightly roundabout, but should yield objectively valid results. I've done stuff like this before, so I'm confident it would work. Unfortunately I don't think the payoff would be remotely worth it (writing to extended attrributes isn't the end of the world), but if any other readers are curious, here's the basic steps:

1. Prerequisites: A) >-500gb spinning HDD, with or without data, that your main OS doesn't use for itself. B) An unused SSD. C) Enough space on your main OS drive to create a small Linux virtual machine [a few GB].
2. Attach the HDD and SSD to your computer, ideally via SATA, or less ideally but still valid, eSATA, Thunderbolt, USB3, etc.
3. Create a new Linux virtual machine. (With any OS as host including Linux.) Make sure to enable APIC-IO, AHCI chipset, SATA/AHCI controllers, at least 2 CPUs, etc.
4. During VM creation, put the main virtual drive file on your regular host OS disk. Also, be sure to NOT enable "Use host I/O cache" on the virtual disk controllers.
5. Mount one or more real spinning HDDs as raw [a] VMDK[s] (commands to do so are well documented for VirtualBox), and attach that to your VM.
6. Start the VM.
7. If the HDD[s] isn't already a volume with data on it, create a volume and put lots of mixed-use data on it that is typical of your use case, at least 500gb or so for testing validity, formatted natively for Linux--ideally either as ext4 or Btrfs. (Or as each in turn for multiple test pass comparison.)
8. Compile rmlint in the VM.
9. Shut down the VM.
6. Using the VirtualBox command line tools, set the raw volume to be immutable.
7. Start the VM up again, then back down. A differencing file (that stores "writes" to the immutable disk) should have been created. That can and should be moved to the unused SSD. (VB docs don't make that obvious how, but with some googling it can be done.)
8. Start the VM up again. Construct a test script to write xattrs to all files on the raw disk and output the ET between start and finish.
9. Run the test script. The files will be hashed read-only on the raw HDD, but the extended attributes will be written to the differencing file located on the spare SSD. (Essentially, VirtualBox intercepts writes and redirects them to a different disk. This is the magic sauce to test the benefit of not writing to the HDD being hashed.) 
10. Write that ET down, and close the VM.
11. Modify the raw HDD again, this time removing the immutable attribute.
12. Start the VM again, and run the test again. Compare the timing.

Writing to a virtualized HDD file, even located on an SSD, will be significantly slower than writing to a real SSD (as would be the case if an SSD-based "hash cache" were implemented). But that time differential can also be tested with other types of tests, and (imperfectly) factored away out if desired. I'd wager that the time difference between writing hashes to the virtual file on an SSD, and to the spinning HDD, would still be significantly better.

**Comment by jim-collier** [comment]
To answer some of your question:

> Thanks, but I can't even take credit for that, the idea came from some other duplicate finder. I forgot though what the name of that thing was. Shame on me.

Good artists copy, great artists steal, etc.

> Side note: In one of your other issues you had a `-a sha256` option. If you experience performance problems, [try switching the checksum algorithm](https://i.imgur.com/PAsfDK6.png?1).

Yeah, that was me not appreciating the default blake2b hashing function, or really the pros and cons of various modern hash algorithms (other than knowing what's ancient and bad, and that sha-2 not being the cat's meow for security purposes). Also I was under the mistaken impression that hardware-accelerated sha-256 would outperform anything else. Glad I googled it.

> Maybe it is already enough to batch writes? Currently `rmlint` will write the `xattr`hashes directly after finishing hashing a file (and while still reading other files). If this is really a pain point, we could defer the writing to the very end of the run and write it in one batch. Not sure if this really an improvement, but it sounds like it might work. Needs numbers to prove it definitely. This would make a lot more sense to me than building yet another cache implementation (and is also easier to implement...)
> 
> Does that make sense to you?

Yes, that would accomplish the same goal, in theory. But unless there was some kind of transaction and state store, to be able to pick back up where left off in case of an unexpected end to processing (essentially back to the sqlite db), I'd rather get as many xattrs written as possible as it goes, to be safe. I know that sounds contradictory to this feature request, but to implement "write at the end" more safely, seems like it would require essentially implementing this first, then copying the values to xattrs. :-D

> That would be a a bit annoying to the user - since `rmlint` has no notion of volumes in its user interface otherwise.

I see, that's a hard point to overcome.

> We already blacklist some of the [more malicious cases](https://github.com/sahib/rmlint/blob/master/lib/utilities.c#L616).

Evil fs types. Love it.

**Comment by jim-collier** [comment]
As a user, agreed. :-)

**Comment by sahib** [comment]
Closing then for now. Re-open if there are some numbers.
