### ISSUE TITLE
Passing --xattr-write --write-unfinished should only write hashes, not also scan for duplicates

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#341]
At least, that's what I'm expecting based on the docs, and seems to make logical sense. At least, when no other linting options are also passed.

For example, this command, intended as a first of three passes to just scan and write hashes:

`rmlint "/mnt/btrfs/array-f7" --no-crossdev --no-followlinks  --hidden -o progressbar -o summary --no-with-color --xattr-write --write-unfinished --algorithm=blake2bp`

Produces this output:

`Traversing (1356014 usable files / 0 + 0 ignored files / folders)`
`Preprocessing (reduces files to 981552 / found 10596 other lint)`
`Matching (101780 dupes of 44754 originals; 7115.07 GB to s^Cn in 809126 files, ETA:  1d 29m 43s)`

But I don't want (or expect) it to scan for dupes or match anything with those flags, I'd hope it would just show "Traversing ..." and something like "Writing extended attributes".

Which also brings up the question, is it doing extra (and redundant) work to find duplicates, that I'll have it do in other steps?

The reason I'd like to do deduping in three steps (write hashes, then find dupes, then processes dupes)--with the first step just writing hashes to extended attributes for new/changed files as needed--is because I have so far at least two scripts that first update the hashes, then do different things. (In one case, log duplicate directories. In another, reflink duplicate files.)

I should note that also passing `--types=duplicatedirs` produces the same output to stdout.

**Comment by sahib** [comment]
> At least, that's what I'm expecting based on the docs, and seems to make logical sense. At least, when no other linting options are also passed.

Can you quote the part that made you think that?

> But I don't want (or expect) it to scan for dupes or match anything with those flags, I'd hope it would just show "Traversing ..." and something like "Writing extended attributes".

He first has to calculate checksums for that. That's 99% of the work of matching duplicates.

> Which also brings up the question, is it doing extra (and redundant) work to find duplicates, that I'll have it do in other steps?

Only some filtering, hash table lookup and other "management" stuff that you probably won't even notice.
And writing output files, but you can disable that by specifying no outputs.

> The reason I'd like to do deduping in three steps (write hashes, then find dupes, then processes dupes)--with the first step just writing hashes to extended attributes for new/changed files as needed--is because I have so far at least two scripts that first update the hashes, then do different things. (In one case, log duplicate directories. In another, reflink duplicate files.)

Subsequent runs will pickup the xattrs of previous runs. There shouldn't be a lot of duplicate work. Imho, it would be easier if you pass the same xattr options all the time (or the new  ``--xattr`` option as of 85c2b7186138594ae98150f2b5dacfa88f7428d6).

**Comment by jim-collier** [comment]
> > At least, that's what I'm expecting based on the docs, and seems to make logical sense. At least, when no other linting options are also passed.
> Can you quote the part that made you think that?

Probably not, it was just my general impression after repeated readings of various (and ultimately all) parts. :-)

> Subsequent runs will pickup the xattrs of previous runs. There shouldn't be a lot of duplicate work. Imho, it would be easier if you pass the same xattr options all the time (or the new `--xattr` option as of [85c2b71](https://github.com/sahib/rmlint/commit/85c2b7186138594ae98150f2b5dacfa88f7428d6)).

Fantastic!
