### ISSUE TITLE
CTRL+C doesn't propagate to calling bash script

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#342]
For example, given this script:

#!/bin/bash
set -e
rmlint "/mnt/btrfs/array-f7" --xattr-write --write-unfinished
echo "If you pressed CTRL+C above, you shouldn't see this."
rmlint "/mnt/btrfs/array-f7" -D
echo "Or get to that."

If you press CTRL+C once during the first call to rmlint, you shouldn't see anything else after that (other than rmlint messages related to cleaning up).

Presumably, the exit status is 0 (but should be >0), though I haven't confirmed this with echo $?.

I'm guessing that was a design decision, and I'm guessing that pressing CTRL+C twice (which rmlint shows as a "hard" break), would. But for scripting, the assumption and convention is always that a single CTRL+C will propagate up and prevent any further script processing.

If changing that would break existing scripts or entrenched expectations, the at least a flag to exit with >0 for a single CTRL+C, would be useful for scripting.

Edit: I do see that Issue #23 notes something similar. This issue is a little different, it's pointing out that this is unexpected behavior for scripting. The first time I saw my script continuing, I had a moment of mild panic, and assumed I forgot to "set -e".

So it's either a "bug" report, or a feature request, depending on how you look at it. :-D

**Comment by sahib** [comment]
> Presumably, the exit status is 0 (but should be >0), though I haven't confirmed this with echo $?.

It is indeed. I agree that something ``!= 0`` should be the right exit status here.

> I'm guessing that was a design decision, and I'm guessing that pressing CTRL+C twice (which rmlint shows as a "hard" break), would. But for scripting, the assumption and convention is always that a single CTRL+C will propagate up and prevent any further script processing.

Since ``rmlint`` is normally run interactively, it is our way to stop soon but still produce a working script output. A single CTRL+C should already quit it, but it might take a bit time.

**Comment by jim-collier** [comment]
Thank you!
