### ISSUE TITLE
ERROR: lib/xattr.c:118: getxattr: Too many levels of symbolic links

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#344]
Within a few 5 - 10 seconds of running:

`rmlint "/mnt/btrfs/array-f7" --no-crossdev --no-followlinks  --hidden -o summary --no-with-color --merge-directories --xattr-read --rank-by=pHMLDa -o csv -o json -o sh -o py`

I receive the following error:

`ERROR: lib/xattr.c:118: getxattr: Too many levels of symbolic links`

It didn't abort execution. Is this normal? Note that the `--no-followlinks` option was specified.

Version info:

`rmlint --version`
`version 2.8.0 compiled: Jan 24 2019 at [23:31:58] "Maidenly Moose" (rev b4f1a33c)`
`compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support`

I'm currently logging a run with "-vvv" for upload, in case that helps. I can also run and log with gdb and valgrind if necessary. But I'm guessing this isn't a problem per-se, above and beyond a curiosity that it happened with "--no-followlinks"?

**Comment by jim-collier** [comment]
I'm currently logging a run with "-vvv" for upload, in case that helps. I can also run and log with gdb and valgrind if necessary.

**Comment by sahib** [comment]
This can count as bug. ``getxattr`` seems to follow links by default - which is surprising. There seems to be a linux specific call (``lgetxattr``) that doesn't have this quirk though. Yet another layer of silly ``#ifdefs``. It shouldn't have noticeable effect on your run otherwise though, except from a xattr not being picked up.

> It didn't abort execution. Is this normal?

I changed the log level to a warning. This is not a fatal error.

**Comment by jim-collier** [comment]
In this case, it seems to have been a problem with my filesystem having a circular symlink. Specifically, I had a file that was a link to itself. Something like "dumbfile" which was a symlink to "./dumbfile". I found it by executing `find -L /mnt/btrfs/array-f7 -mindepth 32`.

That, combined with the fact that you changed the log level to warning, seems to wrap this up?
