### ISSUE TITLE
"ERROR: Something went wrong reading [file]; expected 5931 bytes, got 2474; ignoring"

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#345]
The specific error with the actual filename:

`"ERROR: Something went wrong reading /mnt/btrfs/array-f7/0-0/common/exec/setup/microsoft/win32/OS/updates/Windows XP Service Pack 3 [KB936929-SP3-x86-ENU]/i386/kbdpash.dl_; expected 5931 bytes, got 2474; ignoring"`

Version info:

`rmlint --version`
`version 2.8.0 compiled: Jan 24 2019 at [23:31:58] "Maidenly Moose" (rev b4f1a33c)`
`compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support`

I'm currently logging another run with -vvv for upload, which will take an hour or two before it hits the segfault error again (and includes this error). I can also run and log with gdb and valgrind if necessary. Could this have happened from one of the several times hitting CTRL+C twice when working out command-line switches?

(Why this file exists on my filesystem is a question I can't really answer. Alot of ancient cruft exists that surprises me. At least it didn't betray the stuff I have going back to DOS 2.0.)

**Comment by sahib** [comment]
This kind of error usually happens when a file is being modified while reading. In this case, the file might have had ``5931`` according to stat, but was truncated for some reason to 2474 bytes.

> Could this have happened from one of the several times hitting CTRL+C twice when working out command-line switches?

Yes, this could also happen in theory, if you hit CTR+C on the run that produced this message.
I also changed this to a warning level, since rmlint will sort out suspicious files like these itself.

**Comment by jim-collier** [comment]
OK, I'll see if it happens again on the current debug run. FYI there's close to zero chance that file was modified during the run though, or any time since its mtime of 2008. I didn't even know I still had SP3 update for Windows XP  still laying around :-). I don't have any other daemons running that [should] modify data on that volume.

**Comment by SeeSpotRun** [comment]
I'm going to assume this was a once-off and close the issue.
