### ISSUE TITLE
Feature request: browse files within archives (zip, rar, tgz)

### ISSUE THREAD

**Issue by jose1711** [sahib/rmlint#355]
it would be nice if `rmlint` gains the ability to peek into archives and report on duplicate files within them (e. g. `fileXY` already contained in `backup.tgz`)

**Comment by sahib** [comment]
This would be very hard to implement and would cause heavy workload on most machines it's being run on. Especially when it comes to modifying those archives to remove a certain file (you could also have read only support for that, but that would be incomplete support, which somebody else would complain about). 

If you really need this kind of behavior, you can use something like ``archivemount`` to mount the ``.tgz`` as ordinary directory and run ``rmlint`` on top of that. This is of course also a hack, but it is about as good as it gets, even if we'd implement the insane amount of archive files ourselves.

**Comment by PanosFirmpas** [comment]
What about calculating the checksum of the raw content of single zipped files?       
So if rmlint encounters somefile.txt.gz I would like it to calculate the checksum of the .txt not the zipped.
       
I have a lot of huge zipped files and I'm sure I'm missing some duplicates because they were duplicated and then zipped separately.

**Comment by sahib** [comment]
> What about calculating the checksum of the raw content of single zipped files?
So if rmlint encounters somefile.txt.gz I would like it to calculate the checksum of the .txt not the zipped.

That's more or less equally hard to implement as the original proposal. So: no.

**Comment by vk496** [comment]
I am also interested in this feature. It will help a lot to, at least, detect them.

Most of the formats have headers with crc32 of each file (uncompressed)
