### ISSUE TITLE
reflink discrepancy

### ISSUE THREAD

**Issue by tlhonmey** [sahib/rmlint#356]
https://rmlint.readthedocs.io/en/latest/tutorial.html#outputs-formatters
This lists -c sh:reflink as an output option, however when I attempt to use it I get:
```
$ rmlint  -o sh:rmlint.sh -c sh:reflink .
ERROR: Invalid key `reflink' for formatter `sh'.

```

The other dedupe methods (hardlink, symlink, etc) seem to work fine.
The code to perform reflink dedupes is in the generated .sh file, so I can work around this by just using hardlink or symlink and then editing the script to swap the commands.

If reflink behaviour is supposed to be subsumed in some other dedupe type, then the documentation needs updating.

If -c sh:reflink is supposed to work, then there's a bug.

**Comment by sahib** [comment]
> If -c sh:reflink is supposed to work, then there's a bug.

Actually it's not. It's a typo in the documentation and the option you were looking for is/was ``-c sh:link``. I'd agree this is a little inconsistent though, so I added ``sh:reflink`` as an alias as of e65ecd0db256d6ff3a7c166decebcee5397a8d52.
