### ISSUE TITLE
rmlint is not working on a SSHFS mount due to "other suspicious item(s) found" error

### ISSUE THREAD

**Issue by def-bs** [sahib/rmlint#360]
Dear rmlint developers,

I am trying to use rmlint to search for duplicate directories on a SSHFS mounted directory.

I am getting issue because the files and directory are not read correctly with a generic other suspicious item(s) found.

In the output message I got this:
==> Note: Please use the saved script below for removal, not the above output.
==> In total 122268 files, whereof 0 are duplicates in 0 groups.
==> This equals 0 B of duplicates which could be removed.
==> 122268 other suspicious item(s) found, which may vary in size.
==> Scanning took in total  2m 49,143s.

And all the elements are show as:
chown root:root '/all the path'

is there a way to fix this problem?

Thank you a lot.

Best Regards.

**Comment by sahib** [comment]
Hello @def-bs,

this is because ``rmlint`` tries to find other issues with your files first. This is a feature, not a bug. You should make ``rmlint`` only search for duplicate files and directories by specifying ``-T df,dd``. See also the man page for more details.
