### ISSUE TITLE
Ideas to improve the duplicatedirs feature

### ISSUE THREAD

**Issue by pkonow** [sahib/rmlint#361]
Hi, I found rmlint while looking for a tool that could help me to find duplicate directories. So far I've been very impressed with all the things that you have already implemented, as you often worked around pitfalls that I didn't consider in the tools that I wrote for myself. I noticed some things that could be improved (version 2.8.0):

1. Add an option to limit the search to duplicate directories that have the same or a similar basename. Right now, `rmlint . --merge-directories -T "none +duplicatedirs" --match-basename` does not seem to have the expected effect. It would be great to have an option to restrict it to directories that either have the same name or that have a prefix-match (e.g. Documents and Documents-backup)

2. Some inconsistencies in the docs that I found (not sure which of them are bugs and which are not):
    * I noticed that `rmlint . -T "none +duplicatedirs"` also traverses hidden directories, but the docs only mention this to be enabled for `-D` or `--merge-directories`
    * The man page says that `-D` enables `--partial-hidden`, while https://rmlint.readthedocs.io/en/latest/tutorial.html states that it implies `--hidden`. Also the man page says that this can be overridden by follow-up arguments. It seems like `-D` always includes hidden directories (including .git), regardless of whether `--partial-hidden` is appended or not.

3. The tutorial says the following:

    > rmlint finds duplicate directories by counting all files in the directory tree and looking up if there’s an equal amount of duplicate and empty files.

    This sounds a little fragile to me (maybe the implementation is more robust?). What if directory A has files 'x', 'y' and additional 3 duplicates with directory B, and directory C has file 'z', 'w' and additional  3 duplicates with D? Now A and C have the same number of files and have an equal amount of duplicates, but are completely different. ;)
    Maybe you could consider using a hash tree (https://en.wikipedia.org/wiki/Merkle_tree) to decide if two directories are equal or not. That should be pretty scalable because you're calculating the hash sums of individual files anyway. This should leave an option about whether folder contents also need have the same names (so that the two folders are EXACTLY the same), or just have matching hash sums (following the global rules for matching duplicate files)

Unfortunately, like you said in the tutorial, matching folders is non-trivial and there are so many different use cases for different scenarios. I might still end up writing my own custom tool for it, but if you would include these thoughts & features into your product as well that might be useful for others. Since there are so many different options to consider when matching directories, maybe it would make sense to move directory matching into its own tool to avoid option cluttering? Such two tools could easily complement each other by running duplicatedirs first, and duplicatefiles second to find remaining individual files if necessary.

**Comment by sahib** [comment]
> Hi, I found rmlint while looking for a tool that could help me to find duplicate directories. So far I've been very impressed with all the things that you have already implemented, as you often worked around pitfalls that I didn't consider in the tools that I wrote for myself. I noticed some things that could be improved (version 2.8.0):
> 
> 1. Add an option to limit the search to duplicate directories that have the same or a similar basename. Right now, `rmlint . --merge-directories -T "none +duplicatedirs" --match-basename` does not seem to have the expected effect. It would be great to have an option to restrict it to directories that either have the same name or that have a prefix-match (e.g. Documents and Documents-backup)

``--match-basename`` currently works only on duplicate files. I.e. it would work if two directories only have duplicates with matching base names. This would need to be an separate option (``--match-dir-basename`` or something).

> 2. Some inconsistencies in the docs that I found (not sure which of them are bugs and which are not):
>     * I noticed that `rmlint . -T "none +duplicatedirs"` also traverses hidden directories, but the docs only mention this to be enabled for `-D` or `--merge-directories`
>     * The man page says that `-D` enables `--partial-hidden`, while https://rmlint.readthedocs.io/en/latest/tutorial.html states that it implies `--hidden`. Also the man page says that this can be overridden by follow-up arguments. It seems like `-D` always includes hidden directories (including .git), regardless of whether `--partial-hidden` is appended or not.

I need to look that up on the weekend. The logic is a bit more complicated than I would like.

> 3. The tutorial says the following:
> 
>     > rmlint finds duplicate directories by counting all files in the directory tree and looking up if there’s an equal amount of duplicate and empty files.
> 
>     This sounds a little fragile to me (maybe the implementation is more robust?). What if directory A has files 'x', 'y' and additional 3 duplicates with directory B, and directory C has file 'z', 'w' and additional  3 duplicates with D? Now A and C have the same number of files and have an equal amount of duplicates, but are completely different. ;)
>     Maybe you could consider using a hash tree (https://en.wikipedia.org/wiki/Merkle_tree) to decide if two directories are equal or not. That should be pretty scalable because you're calculating the hash sums of individual files anyway. This should leave an option about whether folder contents also need have the same names (so that the two folders are EXACTLY the same), or just have matching hash sums (following the global rules for matching duplicate files)

The documentation shortens the algorithm in a way that made it unclear. The actual algorithm actually uses a Merkle tree, you can find some more in-depth explanation [here](https://github.com/sahib/rmlint/blob/master/lib/treemerge.c#L26). Beware that there is a special option called ``--honour-dir-layout`` that makes this a bit more difficult.

> Unfortunately, like you said in the tutorial, matching folders is non-trivial and there are so many different use cases for different scenarios. I might still end up writing my own custom tool for it, but if you would include these thoughts & features into your product as well that might be useful for others. 

Why not improve ``treemerge.c``? :smirk:

> Since there are so many different options to consider when matching directories, maybe it would make sense to move directory matching into its own tool to avoid option cluttering? Such two tools could easily complement each other by running duplicatedirs first, and duplicatefiles second to find remaining individual files if necessary.

In this case we would loose the possibility to calculate duplicate dirs in parallel, which can be expensive in large file sets. Also making it an separate tool would duplicate a lot of options and I would probably get a lot of feature requests to add options if I would remove one. :smirk:

I see points for both sides, but I don't consider the effort worth it for now.

**Comment by sahib** [comment]
> I noticed that rmlint . -T "none +duplicatedirs" also traverses hidden directories, but the docs only mention this to be enabled for -D or --merge-directories

Okay, it indeed [traverses hidden files](https://github.com/sahib/rmlint/blob/master/lib/cmdline.c#L657). Maybe this needs a bit more checking.

> The man page says that -D enables --partial-hidden, while https://rmlint.readthedocs.io/en/latest/tutorial.html states that it implies --hidden. Also the man page says that this can be overridden by follow-up arguments. It seems like -D always includes hidden directories (including .git), regardless of whether --partial-hidden is appended or not.

There seems to be two bugs there indeed:

```bash
# 'x' files always have the content 'x'
# 'y' files always have the content 'y'
$ tree -a
.
├── a
│   ├── .x
│   └── y
├── b
│   ├── x
│   └── y
├── .x
└── .y

$ rmlint . -T 'df,dd' --hidden

# Duplicate Directorie(s):
    ls -la '/tmp/ui-master/xxx/b'
    rm -rf '/tmp/ui-master/xxx/a'

# Duplicate(s):
    ls '/tmp/ui-master/xxx/b/x'
    rm '/tmp/ui-master/xxx/.x'
    ls '/tmp/ui-master/xxx/b/y'
    rm '/tmp/ui-master/xxx/.y'

# The output of this should be the same for both commands:
$ rmlint . -D  --hidden       

# Duplicate Directorie(s):
    ls -la '/tmp/ui-master/xxx/b'
    rm -rf '/tmp/ui-master/xxx/a'
```

The other bug: The documentation of ``--partial-hidden`` seems to imply that it leaves out directories in its results that start with a dot. This needs to be fixed for consistency reasons. This shows for the example above:

```bash
$ mv b .b
# '.b' should not have been included:
$ rmlint -D --partial-hidden

# Duplicate Directorie(s):
    ls -la '/tmp/ui-master/xxx/.b'
    rm -rf '/tmp/ui-master/xxx/a'
```

**Comment by sahib** [comment]
As of bb1d10717ff0cfca107a3d52ccfa842628ffc888 the faulty behavior in my last comment should be fixed. The rest of this issue was the possible addition of something like ``--match-dir-basename``, which I still need to think about.
