### ISSUE TITLE
How to prevent output of default files to current directory?

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#362]
When I run the following command:
```
rmlint "/mnt/btrfs/array-f7" --no-crossdev --see-symlinks --hidden --xattr -vvv -o summary --no-with-color --types=duplicatedirs --rank-by=pHma -o csv:/tmp/rmlint_20190610-091138.csv -o json:/tmp/rmlint_20190610-091138.json
```

(I'm not creating an sh script because I'm only interested, in this case, in finding duplicate directories.)

It also creates `rmlint.json` and `rmlint.sh` in my user home directory. (I did run the command from my home directory, which I'm guessing is why they are created there.) These start stacking up, with apparently auto-renamed older versions such as `rmlint.2019-06-10T01:29:48.684029Z.sh`.

Is there a way to prevent those from being created, while not interfering with the output files I did specify?

**Comment by sahib** [comment]
> Is there a way to prevent those from being created, while not interfering with the output files I did specify?

Yes, use ``--no-backup``. I seem to have forget to mention it in the man page. Will add later.

**Comment by jim-collier** [comment]
Great, thanks
