### ISSUE TITLE
Passing --threads=1 doesn't seem to be honored, or just confusing debug output

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#364]
When I execute the following command:

```
rmlint "/mnt/btrfs/array-f7" --xattr-clear --no-crossdev --see-symlinks --hidden -vvv -o summary --no-with-color --threads=1 --types=none
```

I see this in the output: :

```
DEBUG: Starting MDS scheduler with 1 threads
DEBUG: Starting disk 2096 (pointer 0x557c4e5b5800) thread #1
DEBUG: Starting disk 2096 (pointer 0x557c4e5b5800) thread #2
```

Which is confusing. It says only "1 threads", but then itemizes two threads.

`iotop` does indeed show only thread producing disk I/O.

However, htop shows two processes, each consuming about the same CPU %.

I realize that spawning two processes might not necessarily conflict with the "only one thread" directive. (E.g. one process might be a watchdog, and/or only calculating checksums, etc.)

So either the debug message is just potentially confusing (compounded by two possibly normal processes in htop), or the flag isn't being fully honored?

**Comment by sahib** [comment]
> Which is confusing. It says only "1 threads", but then itemizes two threads.

The debug output is not meant for users... :smirk: 
One thread is reading, one is hashing. 

> So either the debug message is just potentially confusing (compounded by two possibly normal processes in htop), or the flag isn't being fully honored?

``rmlint`` is a highly multithreaded and complex program, that might decide upon input how many threads it needs.  Using ``--threads`` was added as means for debugging for us. If you check the manpage it says:

```
The number of threads to use during file tree traversal and hashing.  
rmlint probably knows better than you how to set this value, so just leave it as it is.
Setting it to 1 will also not make rmlint a single threaded program.
```

I strongly advice you to let ``rmlint`` guess itself what number of threads it needs.

**Comment by jim-collier** [comment]
I totally get that, and did read that specific disclaimer. And understand. :-) The thing that triggered this question/concern, before even digging into the debug output, was that iotop showed two threads doing heavy reading from the array. Any simultaneous, non-sequential reading incurs heavy penalties on my hardware configuration. The only way to figure out what's really going on, is to A) dig deeper, and/or B) ask the devs.

With 36tb of raw storage, at about 90% capacity--doing concurrent, non-sequential reading and writing across 4 the devices in the array would result in a substantial decrease in average drive lifetime and array durability! In my experience having killed over 100 drives in some 30-odd years, it's days/weeks-long thrashing that kills them faster than anything else.
