### ISSUE TITLE
Message "WARNING: failed to setxattr ... Operation not permitted"

### ISSUE THREAD

**Issue by jim-collier** [sahib/rmlint#365]
I realize this may not be an rmlint problem, but hoping you've seen it before. (I don't see any similar existing issues.)

Theres a bunch of these messages:
```
WARNING: failed to setxattr for /mnt/btrfs/array-f7/LONG-PATH/S20virtualbox-ose: Operation not permitted
```

Where "`LONG-PATH`" is a long sub-path that I've redacted for privacy/security. But the fact that the entire filespec is 154 characters long might mean something. (All the files with the error have long paths...but then again most of the other files do too, including ones _without_ the error that are longer).

**Comment by jim-collier** [comment]
Ah, never mind, probably.

A random sampling of files with the error, show them to be symlinks.

The interesting thing though, is:

- Some of the symlinks are valid (but point to files on a different filesystem)
- The different filesystem is ext4, which supports xattrs
- The command is using the `--no-followlinks` flag.

I don't know if the last point means it's not working as expected, but since it's not actually following directory symlinks, I suppose that's probably working as intended? Might the fact that the symlinks are pointing to another filesystem, have something to do with it? (The command also has the `--no-crossdev` flag specified.)

**Comment by sahib** [comment]
> Theres a bunch of these messages:

``rmlint`` is just passing the error ``setxattr()`` gives to you. I can only guess about the reason.

> But the fact that the entire filespec is 154 characters long might mean something.

``rmlint`` uses buffers for paths that are PATH_MAX long - which is usually 4096. Shouldn't be a problem.
