### ISSUE TITLE
Alpine docker GUI: Failed to load shredder: No module named 'shredder'

### ISSUE THREAD

**Issue by bobbintb** [sahib/rmlint#369]
I am trying to create a docker image of rmlint that uses Alpine 3.9 as a base image. The base image has Openbox to so apps can be run on a headless server and view the gui in a webpage. When I try to run `rmlint --gui` I get the following error:

`Failed to load shredder: No module named 'shredder'
This might be due to a corrupted install; try reinstalling.`

I read of similar issues with Debian, but the error was slightly different and from what I've read, doesn't appear to be the same issue. This is the base image I am using:

https://github.com/jlesage/docker-baseimage-gui

And these are the extra packages I have installed. 
`add-pkg build-base \
        python \
        git \
        scons \
        glib \
        glib-dev \
        libelf \
        libelf-dev \
        sqlite-libs \
        json-glib-dev \
        gtk+3.0 \
        librsvg \
        py-gobject \
        py-sphinx \
        elfutils \
        libc6-compat \
        py-cairo \
        dconf \
        gtksourceview`

I'm sure many of these aren't needed but I've just been looking at the build dependencies from other distros and trying to go from there. The compiling doesn't produce any errors. shredder.c seems to compile just fine.

**Comment by sahib** [comment]
Hello @bobbintb,

you did install from source? Did you do the ``sudo scons DEBUG=1 --prefix=/usr install`` step?
The error you're getting means that the python part of ``rmlint`` was not installed (which is partly also named ``shredder``, this is not ``shredder.c``) or was installed in a path that is not reachable (``rmlint --gui`` [basically starts a python interpreter](https://github.com/sahib/rmlint/blob/master/lib/cmdline.c#L138)). Also check if h

**Comment by sahib** [comment]
Any updates on this? I will close this issue after some time otherwise.
