### ISSUE TITLE
Shredder GUI: Tooltips can't handle filenames containing ampersands

### ISSUE THREAD

**Issue by ferdnyc** [sahib/rmlint#371]
Using the GUI interface, whenever a file/directory name contains an ampersand, it's displayed properly in the tree list. But whenever the software attempts to display a tooltip containing the name, a Pango warning is output on the console (actually, Pango warnings are spewed out on the console as long as the tooltip is attempting to show):

> (shredder:12122): Pango-WARNING **: 14:17:05.417: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as `&amp;`
> 
> (shredder:12122): Pango-WARNING **: 14:17:05.430: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as `&amp;`
> 
> (shredder:12122): Pango-WARNING **: 14:17:07.682: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as `&amp;`

This is accompanied by an empty tooltip:

![Screenshot from 2019-07-13 14-24-02](https://user-images.githubusercontent.com/538020/61175262-2234f580-a57a-11e9-8e89-d219f3fb0d7d.png)

The same is true in the tree view, although the tooltips there only cause a single error message, not a stream of them.

**Comment by sahib** [comment]
Hello @ferdnyc,

thanks for the report. I forgot to escape the path for use as markup text. Should be fixed as of ae121067.

**Comment by sahib** [comment]
There was actually another case in the tree tooltip which is fixed by 1c0abb3c9c7c9bc62495c9d357af9ead1fc117d0.

**Comment by ferdnyc** [comment]
Confirmed, the tree <big><strong>&</strong></big> the chart can both show tooltips with ampersands, with the latest code. Thanks!
