### ISSUE TITLE
GUI: No window close icon

### ISSUE THREAD

**Issue by ferdnyc** [sahib/rmlint#372]
The GUI window comes up without any of the usual client-side decorations, including the close button:

![image](https://user-images.githubusercontent.com/538020/61175299-ca4abe80-a57a-11e9-8e41-e39173676c8c.png)

(Hrm, that totally empty screenshot was ill-advised, in retrospect.)

This leaves no easy way to close the window, except for awkward options like the "Quit" selection in the gear menu, or keyboard combinations.

If the concern is about people accidentally closing the window and losing their progress, an "Are you sure?" popup when the window is closed (via any method) seems like a better solution than removing the close button. (Added points if the confirmation popup can be turned off/on in the settings.)

**Comment by sahib** [comment]
Hi @ferdnyc,

the close button is back since 47a21277775fbfca52483661a24c263dddf39f75.

**Comment by ferdnyc** [comment]
Awesome, thanks! `\o/`

**Comment by ferdnyc** [comment]
Hmm. Actually, I just pulled the `develop` branch, and after a `make run`... I'm still not seeing it.

I see in the 47a2127 diff where the close_button is _created_, but not where it's actually added to the interface.

**Comment by sahib** [comment]
Do a ``export PYTHONPATH=.`` in the same directory as the ``Makefile`` or just install it. You're most likely running the old shredder still.

**Comment by ferdnyc** [comment]
Aha, yep! That's got it, my mistake. Sorry about that.

**Comment by sahib** [comment]
No problem, I make that mistake often enough myself. :smirk:

**Comment by ferdnyc** [comment]
Doing something like this in the Makefile should solve that, since I believe a path inside the current directory is always preferred for an import, even without `PYTHONPATH` being set.

```diff
diff --git a/gui/Makefile b/gui/Makefile
index 8ce64ff9..1a479211 100644
--- a/gui/Makefile
+++ b/gui/Makefile
@@ -7,6 +7,6 @@ schema:
        @glib-compile-schemas ~/.glib-schemas

 run: resources schema
-       @GSETTINGS_SCHEMA_DIR=~/.glib-schemas/ python3 shredder/__main__.py
+       @GSETTINGS_SCHEMA_DIR=~/.glib-schemas/ python3 -c "import shredder; shredder.run_gui()"

 all: run
-- 
2.21.0
```

**Comment by sahib** [comment]
Right, that would be a better solution. Replaced as of 16522e54.
