### ISSUE TITLE
Path field in script "Save to file" dialog lags super weirdly

### ISSUE THREAD

**Issue by ferdnyc** [sahib/rmlint#373]
Something seems to be... "off"... with the Name: entry field, in the file-chooser dialog that comes up when you click "Save to file" on the script listing from the results display.

Running from the source tree (via `make run` in `rmlint/gui`), the dialog comes up with a default filename, and a default save location of the current directory.

Typically I'll want to throw the script to `/tmp`, since I'll only need to run it once. So, my normal approach would be to take advantage of the default input focus and position being right at the start of the filename. I'd just type <kbd>/</kbd><kbd>t</kbd><kbd>m</kbd><kbd>p</kbd><kbd>/</kbd>, then hit <kbd>Enter</kbd> to select the dialog's default "Save" action, and done.

Problem is, when I try to do that in this dialog, my keyboard input is so lagged and spotty that it's almost impossible to get those five characters typed in, and even more difficult to go back and make edits if there are any typos. (Likely, since the lag causes both dropped characters, and unnecessarily repeated inputs after I _assume_ that a letter was dropped only to find out it was just lagged.)

Even more vexing, keyboard navigation with the left and right arrow keys is almost completely non-functional. Sometimes I'll get the input caret to move _**one**_ letter over, and then it'll freeze up — to the point it even stops blinking — and make me think that the entire dialog is lagged/frozen. Only to then discover that, if I mouse-select some text and use the context menu to Cut/Copy/Paste/Delete (rather than the non-functional keyboard shortcuts), everything is super responsive with no lag whatsoever. Yet, my keyboard input is still being ignored by a non-blinking, frozen-looking input caret.

It's really a very, _very_ odd pathology, and I've never seen anything quite like it before.

**Comment by sahib** [comment]
I can't reproduce this behavior on my side. I can type <kbd>/</kbd><kbd>t</kbd><kbd>m</kbd><kbd>p</kbd><kbd>/</kbd> just fine without any lag. This can have many reasons and most I can think of are not directly related to ``rmlint``. Some points to think about:

* Do you have any network mounts active? This sometimes happen to me if I have (e.g.) a broken FUSE mount that takes forever to complete something in ``/tmp/``.
* What ``GTK+`` version are you running on? (``3.24.8`` for me). I should note that I run outside of GNOME.
* Does this also happen in other file save dialogs of other applications? Because that's just what is used by the GUI, there are  no notable customizations to that field as far I can tell.
* Is the CPU load high while typing?

**Comment by ferdnyc** [comment]
> I can't reproduce this behavior on my side. I can type /tmp/ just fine without any lag. This can have many reasons and most I can think of are not directly related to `rmlint`. Some points to think about:
> 
> * Do you have any network mounts active? This sometimes happen to me if I have (e.g.) a broken FUSE mount that takes forever to complete something in `/tmp/`.

I do. None of them _broken_, but... well, I'm not making life easy for Gio. Details below.

> * What `GTK+` version are you running on? (`3.24.8` for me). I should note that I run outside of GNOME.

I'm on `gtk3-3.24.10-1.fc30.x86_64` from the Fedora 30 dist repo.

> * Does this also happen in other file save dialogs of other applications? Because that's just what is used by the GUI, there are  no notable customizations to that field as far I can tell.

Oh, no, I'd definitely have noticed. Like I said, I've never seen anything like it before.

> * Is the CPU load high while typing?

Appears so, yes. My CPU load is high anyway, currently (I have a Windows VM running in the background), but with `top` running I noticed that load for the `ibus-daemon` process, specifically, _rockets_ upward when this is happening, as does the load for both `gnome-shell` and `gjs`. They end up consuming around 15%, 25%, 10% (respectively) of my total 4-core CPU, so basically two cores are pegged. (Though I don't know that `gjs` and `ibus-daemon` are literally running on the same core.)  The high load exactly corresponds to the keyboard lag.

Package/version details for those binaries are:
* ibus-daemon: `ibus-1.5.20-4.fc30.x86_64`
* gnome-shell: `gnome-shell-3.32.2-2.fc30.x86_64`
* gjs: `gjs-1.56.2-4.fc30.x86_64`

I actually couldn't reproduce this just now either, first time I tried. Everything was fine when I ran a compare, then hit "Save to file". But when I _canceled_ that first attempt (just the save dialog), then hit "Save to file" **again**, the lag started happening again, and now occurs every time.


I should also detail the nature of the comparison I'm running, as it may very well be involved. (Even though I'm running from my git clone which is in a local directory under my `$HOME`, and I'm saving to `/tmp/` which (on Fedora) is just an in-memory `tmpfs` mount.) 

The comparison I ran was a two-directory compare:
1. A local USB-mounted filesystem
2. A SSHFS-mounted _remote_ directory on a DIFFERENT system (tagged as "preferred")

(Why, yes. That is in fact very, _very_ slow. But it works fine, with patience.) 

So, maaaybe that's involved. I'll see if I can reproduce with two local directories.

The _other_-other weird thing is this: If I cancel the dialog after typing a slash in the front of the default filename, then bringing the dialog back up again will cause this completion popup, which will be positioned some variable (but wrong) distance away from the input field. If there's no slash in front of the name before I cancel, the popup doesn't show on reentry.

(You have no idea how hard it was to get this screenshot. The only option was `gnome-screenshot` on a timer, since any interaction at all will dismiss the popup. But first I had to first figure out how to reliably cause the issue, so I knew when to start the timer running.)
![Screenshot from 2019-07-16 16-54-50](https://user-images.githubusercontent.com/538020/61329269-e81e5a80-a7ea-11e9-9495-6a99aa72cc74.png)

**Comment by sahib** [comment]
> I do. None of them broken, but... well, I'm not making life easy for Gio. Details below.

Can you please try with everything non-local and/or FUSE disabled? 

> Appears so, yes. My CPU load is high anyway, currently (I have a Windows VM running in the background), but with top running I noticed that load for the ibus-daemon process, specifically, rockets upward when this is happening, as does the load for both gnome-shell and gjs. They end up consuming around 15%, 25%, 10% (respectively) of my total 4-core CPU, so basically two cores are pegged. (Though I don't know that gjs and ibus-daemon are literally running on the same core.) The high load exactly corresponds to the keyboard lag.

Probably a issue with those services then. In any case I would suggest to report this upstream since I'm somewhat clueless what's going on here. I'm not sure if this is even related to ``rmlint`` or if we just trigger a bad condition by accident.

**Comment by ferdnyc** [comment]
> > I do. None of them broken, but... well, I'm not making life easy for Gio. Details below.
> 
> Can you please try with everything non-local and/or FUSE disabled?

Sorry, it took me a few days to find a time window where I could test that, but I have. 

The answer is: No change with all network and external mounts disconnected. The exact same symptoms occur even with an all-local compare. (A path in my home directory vs. a partial copy of its contents in `/var/tmp/`.)
1. Entering "Save to file" the first time, everything is fine.
2. If I place a `/` at the front of the path, Cancel the window, and hit "Save to file" _again_, the completion popup that comes up for the filename input field is detached, and ends up almost halfway down the window.
3. Typing in front of the filename from now on will trigger an almost immediate freeze of all keyboard input response, though mouse input is unaffected.
4. Load for `ibus-daemon`, `gnome-shell`, and `gjs` are all excessively high until the save is canceled again.

I'm still trying to collect more data, if I can figure out how/where. Sysprof _sees_ the spikes, but is really no help at all in figuring out what's going on while they're happening other than "d-bus stuff, maybe?"

![image](https://user-images.githubusercontent.com/538020/61654661-eccf8c80-ac8a-11e9-8e3c-5dd7f66c3797.png)

So far `dbus-monitor` doesn't seem to be seeing anything _too_ unusual, even running as root. Lots of Polkit activity streaming back and forth across the system bus, but I assume that's normal these days.

I'm a little reluctant to go to the Gnome developers when all I have for them are "steps to reproduce" that involve running one _specific_ application, but I'll keep digging to see if I can come up with something a bit more concrete.

**Comment by sahib** [comment]
> Sorry, it took me a few days to find a time window where I could test that, but I have.

No problem.

> I'm a little reluctant to go to the Gnome developers when all I have for them are "steps to reproduce" that involve running one specific application, but I'll keep digging to see if I can come up with something a bit more concrete.

In this case you would have to resort to testing on other systems (other than fedora 30) and/or machines to narrow down the parts that are involved. Since this would be a lot of work I still recommend to ask on a suitable mailing list - they might have a better intuition on what is happening here and might save us a lot of work. At least they can tell us what parts are involved, because I'm a bit clueless on what is happening to be honest and I still can't reproduce it.

> If I place a / at the front of the path, Cancel the window, and hit "Save to file" again, the completion popup that comes up for the filename input field is detached, and ends up almost halfway down the window.

This sounds a lot like a problem outside of ``rmlint`` - I'm using a basic  [GtkFileChooserWidget](https://github.com/sahib/rmlint/blob/master/gui/shredder/views/editor.py#L305) for this.

**Comment by ferdnyc** [comment]
I'm going to close this as I don't expect I'll have time to pursue it further, and it can't be reproduced on other systems.
