### ISSUE TITLE
Generated script doesn't actually delete itself

### ISSUE THREAD

**Issue by ferdnyc** [sahib/rmlint#374]
The `.sh` script saved by Shredder (using the "Save to file" option) doesn't actually delete itself even when it says it will (meaning, the `-x` argument is not given), because instead of the actual path it's saved under, the filename it tries to delete is a nonexistent temporary pathname, e.g.:
```sh
#
# Lines 387-391 in the file '/tmp/rmlint-2019-07-15T18:43:43-0400.sh' :
#
if [ -z $DO_REMOVE ] && [ -z $DO_DRY_RUN ]
then
  echo "Deleting script " "$0"             
  rm -f '/tmp/shredder-_w0wrovc/shredder.sh';                                    
fi
```

**Comment by sahib** [comment]
Should be fixed as of dc5eae1a.
