### ISSUE TITLE
Null separated output

### ISSUE THREAD

**Issue by panhartstuff** [sahib/rmlint#388]
Is there a way to have null separated output? Like `find . -type f -print0`

**Comment by sahib** [comment]
Please elaborate a bit more on your usecase. There is no such option currently. But you can easily build [powerful oneliners](https://rmlint.readthedocs.io/en/latest/tutorial.html#copying-unique-files) with ``-o json`` and ``jq``.

**Comment by panhartstuff** [comment]
It's so that it can be parsed more safely in bash, as unix filenames can contain newlines, but not null.
I'm currently using it within a bash script, as a way to generate a list of unique files within 2 dirs.
Then I iterate through the list in order to do some stuff with the filenames.

Using find I can do this in bash:
```
while IFS= read -r -d $'\0' filename; do
	filelist+=("$filename")
done < <(find . -maxdepth 1 -type f -print0 2> /dev/null)`

for name in "${filelist[@]}"; do
	echo $name
done
```
and I'm hoping to do something similar with rmlint.

**Comment by sahib** [comment]
Ah, so it's about unique files. In this case you can use this trick:

```
$ rmlint /tmp  -o json -c json:unique | jq -cj '.[] | select(.type == "unique_file") | .path+"\u0000"' | xargs -0 -n1 echo
/tmp/file_1
/tmp/file_2
...
```

I recommend [to read a bit](https://stedolan.github.io/jq/manual/) about ``jq``. If you need it as bash array, you could use it like that:

```
while IFS= read -r -d $'\0' filename; do
	filelist+=("$filename")
done < <(rmlint -V /tmp  -o json -c json:unique | jq -cj '.[] | select(.type == "unique_file") | .path+"\u0000"')
```

This is a bit long to be honest, so I added an option as of 94f0a3cf so you can shorten that too:

```
$ rmlint /tmp  -o uniques -c uniques:print0
/tmp/file_1
/tmp/file_2
...
```

Still, in case of duplicates and more complex operations you can always resort to using ``jq`` which can be used safely with newlines.

**Comment by panhartstuff** [comment]
Thank you for the addition!

> Still, in case of duplicates and more complex operations you can always resort to using jq which can be used safely with newlines.
I see, I'll keep this ind mind.

I want to confirm another thing just for safety:
`rmlint -D -k -o uniques "$path1" // "$path2"`
This will find any unique files between $path1 and $path2, that exists in $path2 but NOT in $path1, while ignoring the directory structure inside it, is that right?
Also it seems that the position of the directories in the command doesn't have to be before or after the options?

**Comment by sahib** [comment]
> This will find any unique files between $path1 and $path2, that exists in $path2 but NOT in $path1, while ignoring the directory structure inside it, is that right?

That command will find all unique files in both directories, but...

- ``-k`` will leave out all files in ``$path1`` since you told ``rmlint`` to **k**eep them.
- ``-D`` will (well, it should) not have any notable effect here.
- The directory structure will not have any effect here, since unique files are always files. Directories are not supported.

So in sum you will only get unique files from ``path2`` which is what you meant I think.

> Also it seems that the position of the directories in the command doesn't have to be before or after the options?

Correct.

**Comment by panhartstuff** [comment]
`-D will (well, it should) not have any notable effect here.
The directory structure will not have any effect here, since unique files are always files. Directories are not supported.`
I see, my assumption was very wrong then. With that command rmlint should behave this way right?:
For example in the case of:
/$path1/subpath/file1.mp4
/$path2/file2.mp4
or
/$path1/file1.mp4
/$path2/subpath/file2.mp4
where the contents of file1.mp4 and file2.mp4 are identical, rmlint will not mark file2.mp4 as unique.

while in the case of:
/$path1/otherfile.doc
/$path2/subpath/file2.mp4
or
/$path1/subpath/otherfile.doc
/$path2/file2.mp4
where the contents of otherfile.doc and file2.mp4 are NON-identical, rmlint will mark file2.mp4 as unique.

**Comment by sahib** [comment]
This is correct.

**Comment by panhartstuff** [comment]
Alright thanks for all the help!
But seems that -k doesn't work with the json trick (it still prints unique files from $path1), so I need to use the develop branch for the uniques:print0 feature.
Is that branch currently safe to use for important operations?

**Comment by sahib** [comment]
Hm, I see. It's because the ``json`` output does not expose the ``is_original`` field for ``unique_file``s. Otherwise we could filter it by that. I might add that too...

> Is that branch currently safe to use for important operations?

Feel free to try. All tests pass, so it should be about as safe as ``master``.

**Comment by panhartstuff** [comment]
Thank you, it works perfectly

**Comment by sahib** [comment]
Good. I also added ``is_original`` to the ``unique_file`` json output as of  84cc6d865147bca2714bb5ec4aeff361d6ef82a5 and b44c4e6f75085c102d37300e4d5911dc2ba22e31. This way the json trick from above will work now:

```
tree /tmp/u*
/tmp/u1
├── 1x
└── dup
/tmp/u2
├── 2x
└── dup
$ rmlint -k -o json -c json:unique /tmp/u1 // /tmp/u2  | jq '.[] |  select(.type == "unique_file" and .is_original == false) ' 
{
  "id": 1963343888,
  "type": "unique_file",
  "progress": 100,
  "checksum": "7939bb31938b6bbab9fc1b34ea84db75289ec3aaebe77754ccaca9e8dca20e4b81b11ac70caa244bc0358e2b9cecc10934c09e528771a22e9e20611994920d0b",
  "path": "/tmp/u1/1x",
  "size": 3,
  "depth": 1,
  "inode": 34843349,
  "disk_id": 48,
  "is_original": false,
  "mtime": 1577283079.8934262
}
```
