### ISSUE TITLE
find . -iname "*.jpg" -type f -size +1M -print0 | rmlint -0

### ISSUE THREAD

**Issue by 5hubh0** [sahib/rmlint#389]
find . -iname "*.jpg" -type f -size +1M -print0 | rmlint -0

does not work i.e. does not filter and transcends into each and every file.

Installed from arch repos

**Comment by sahib** [comment]
That works for me. What does ``rmlint --version`` say? I was trying the latest ``master``.

**Comment by 5hubh0** [comment]
Thank you for responding. 
rmlint  2.9.0-2 from arch repository.
Yes the git master works.
Anyways my problem was to remove redundancies from multiple external drives having a total of about a million files to process which I indiscriminately and haphazardly backed up.
I am an SQL guy and hence I imported size, ctime, path to sqlite3 from flat files generated by find and used SQL to remove the files from each source (removing rows from tables i.e. dry run) and then used rm. This was specific to my use case but was based on the ideas behind rmlint.
