### ISSUE TITLE
Support custom "hash" functions

### ISSUE THREAD

**Issue by simaoafonso-pwt** [sahib/rmlint#393]
I'm trying to find duplicate emails on a bunch of Maildirs.

I have a script to find the email's Message-ID, and wanted to de-duplicate based on this string:
```sh
#!/bin/sh
exec grep -iE "^Message-ID: " "$1" | tail --bytes="+13"
```
---

I'm not sure this is already supported, based on the docs. It's different from having a custom command to select which file "wins".

The simplest thing I'm thinking of is having a custom "hash" function that passes the file through a custom execution. This might be extremely slow, but useful for corner cases.

**Comment by sahib** [comment]
Hello @simaoafonso-pwt,

I think there was already a feature request for this somewhere (I fail to find it right now). Back then it was about detecting duplicated music. The conclusion back then was that this is something we'd like to see but it is quite hard to implement with the current architecture of ``rmlint``. So definitely not something that will happen in the near future.

Maybe there are other options:

* Use the clamping options (``-q`` / ``-Q``) if there is a static portion of the file you can compare.
* Write a script that parses the message id and put it into a file that is named the same as the source file. This would result in a tree of files that has the same layout and naming as the maildirs, but only contains maildirs. Run ``rmlint`` on that and replace the path prefix in ``rmlint.sh`` before executing it.

**Comment by simaoafonso-pwt** [comment]
>     * Write a script that parses the message id and put it into a file that is named the same as the source file. This would result in a tree of files that has the same layout and naming as the maildirs, but only contains maildirs. Run `rmlint` on that and replace the path prefix in `rmlint.sh` before executing it.

This sound like a possible solution.

Thanks for the swift response.
