### ISSUE TITLE
Treat sidecar files atomically with the main content

### ISSUE THREAD

**Issue by didenko** [sahib/rmlint#395]
There are situations when a software stores metadata in "sidecar" files with an added extension to avoid modifying the original. In those situations, it normal that the main content may not change, while the sidecar will differ. That makes it easy to leave "dangling" sidecar files when the main content is removed as duplicates.

An example of such sidecar files in photography:

```bash
[vlad@box Images]$ l 071123_9426*
-rw-rw---- 957K 2007-11-28  071123_9426.jpg*
-rw-rw---- 1.3K 2019-05-18  071123_9426.jpg.xmp
[vlad@box Images]$
```
The suggestion is to introduce a behavior and a configuration parameter to treat sidecar files as  "packages" (see #394) with main content. Here is an example use of the parameter:
> --sidecar ext:xmp
> --sidecar prefix:'~'

**Comment by sahib** [comment]
Hello @didenko,

The same as in #394 applies. The issue can be solved by using hardlinks and the proposed solution is too specific and relatively much code to implement.
