### ISSUE TITLE
Prioritizing Multiple Regex Conditions

### ISSUE THREAD

**Issue by madjoe** [sahib/rmlint#399]
I tried to use the following setup for my usecase:
`rmlint -S 'r<.*(ABC|DEF|GHI).*>R<.*(tmp|temp|cache).*>m'  /test`

The idea was to promote all paths containing **ABC|DEF|GHI** respectively as originals, demote all of those containing **tmp|temp|cache** in their paths and if none of those is applicable, to promote the oldest content as originals.

Not sure if **rmlint** currently works as described above. If not, it should be mentioned within the docs, I guess?

Furthermore, prioritizing **ABC** over **DEF** and **DEF** over **GHI** doesn't seem to be possible yet? That would be a very useful feature. Say if **ABC** and **DEF** are folders with coded filenames and **GHI** does not contain coded filenames yet, therefore **ABC** and **DEF** have more _valuable_ content for us (within the filename). Could it be done by tagging somehow?

I tried it by following documentation, but without success. Please show me how it should be done properly. Thanks!

**Comment by sahib** [comment]
(Note: Part of prior discussion happened via mail, part of the answer copied from there)

> The idea was to promote all paths containing ABC|DEF|GHI respectively as originals, demote all of those containing tmp|temp|cache in their paths and if none of those is applicable, to promote the oldest content as originals.
> 
> Not sure if rmlint currently works as described above. If not, it should be mentioned within the docs, I guess?


I had a try with with this dataset (all have the same content):

```
$ tree /tmp/t 
/tmp/t 
├── ABC 
├── another 
├── DEF 
├── other 
├── xxx-cache-yyy 
├── xxx-temp-yyy 
└── xxx-tmp-yyy
```

```bash
$ ./rmlint -S 'x<.*(ABC|DEF).*>X<.*(tmp|temp|cache).*>m'  /tmp/t 

# Duplicate(s): 
   ls '/tmp/t/DEF' 
   rm '/tmp/t/ABC' 
   rm '/tmp/t/other' 
   rm '/tmp/t/another' 
   rm '/tmp/t/xxx-cache-yyy' 
   rm '/tmp/t/xxx-temp-yyy' 
   rm '/tmp/t/xxx-tmp-yyy'
```

So it seems to work. The docs should note though that parantheses do not need to be escaped (for some reason, This is the library that rmlint uses internally: https://developer.gnome.org/glib/stable/glib-Perl-compatible-regular-expressions.html (claims to be PCRE)).


> Furthermore, prioritizing ABC over DEF and DEF over GHI doesn't seem to be possible yet? That would be a very useful feature. Say if ABC and DEF are folders with coded filenames and GHI does not contain coded filenames yet, therefore ABC and DEF have more valuable content for us (within the filename). Could it be done by tagging somehow?

It should be possible by chaining a few more patterns. What's wrong with this?

```bash
$ rmlint -S 'x<.*ABC.*>x<.*DEF.*>x<.*GHI.*>X<.*(tmp|temp|cache).*>m' /tmp/t

# Duplicate(s):
    ls '/tmp/t/ABC'
    rm '/tmp/t/DEF'
    rm '/tmp/t/GHI'
    rm '/tmp/t/another'
    rm '/tmp/t/other'
    rm '/tmp/t/xxx-cache-yyy'
    rm '/tmp/t/xxx-tmp-yyy'
    rm '/tmp/t/xxx-tempt-yyy'
```

> I tried it by following documentation, but without success. Please show me how it should be done properly. Thanks!

It would be helpful if you could write some docs snippets - it's always better when that comes from a user. I could add it too, but this way I'm sure at least one user understood the feature.

**Comment by madjoe** [comment]
This snippet is **absolutely useful** and I'm sure it has to be mentioned within the docs/examples (with a proper explanation of what it does) to help the others. I do believe there are many usecases that could benefit from it. I just tested it and it works great:
`$ rmlint -S 'r<.*ABC.*>r<.*DEF.*>r<.*GHI.*>R<.*(tmp|temp|cache).*>m' /test`

Previously I tried with this one, but it doesn't obey the weight/priorities, of course (therefore it's not that useful and I would not include it within the docs), but again - it does what it does:
`$ rmlint -S 'r<.*(ABC|DEF|GHI).*>R<.*(tmp|temp|cache).*>m' /test`

If I come up with any other similarly useful snippet for the docs, I will list it here.

**Comment by sahib** [comment]
I added documentation here: 129dd0a53f8469b0ffbb8e30859ed70a8560230d

> If I come up with any other similarly useful snippet for the docs, I will list it here.

It would be even cooler if you'd made an [Pull Request](https://rmlint.readthedocs.io/en/latest/developers.html#making-contributions). 

----

I'll close this issue for now since the original issue is done. You can still post here.
