### ISSUE TITLE
Keeping directory timestamp does not work when directory contains whitespaces

### ISSUE THREAD

**Issue by niririke** [sahib/rmlint#406]
Due to an issue with quoting [here](https://github.com/sahib/rmlint/blob/1b9726f574e057610c669925eda86c1247a1b0ae/lib/formats/sh.sh#L259) keeping timestamp for directories with whitespaces breaks. It was fixed in #392. I am leaving this issue here to document it and to highlight importance of the pull request. This issue should be closed when the pull request is merged.

**Comment by sahib** [comment]
PR #392 has been merged. Thanks for the reminder.
