### ISSUE TITLE
Ignoring return value of rm_sys_stat in lib/utilities.c

### ISSUE THREAD

**Issue by Cebtenzzre** [sahib/rmlint#410]
https://github.com/sahib/rmlint/blob/3a7d52db5d3ddf82b00e45ea3ead69e8e413c725/lib/utilities.c#L655
https://github.com/sahib/rmlint/blob/3a7d52db5d3ddf82b00e45ea3ead69e8e413c725/lib/utilities.c#L676
These stat calls can fail for reasons that should not be unexpected, e.g. no read permission.
In my case, this resulted in the wrong st_dev value being considered an "evil fs", and rmlint ignored all of the files I was trying to scan.

This would be easier to catch if rm_sys_stat used the `warn_unused_result` attribute. It wouldn't be hard to implement a WARN_UNUSED macro similarly to how the INLINE macro conditionally uses `__always_inline__`.

**Comment by sahib** [comment]
Hello @Cebtenzzre,

thanks for the tip. This should be resolved as of 61e6037a4c0ac18e67ae30adb834c318390fa4b9.
