### ISSUE TITLE
[Clarification request] Best option to find "non-duplicates"

### ISSUE THREAD

**Issue by Wikinaut** [sahib/rmlint#412]
Scenario:

I have a few USB-Disks Z(i) and want to know, which files/directories have not yet been backuped to a backup repository "A" regardless of the directory in "A" - the exact directory does not matter, because I already cleaned and reorganised "A" (using ```fslint```).

I am pretty sure, that ```rmlint``` can help here to detect "non-duplicates" (```fslint``` cannot and there was not acceptance of my request there) - but how?

P.S.
I found this general hint: https://geekhack.org/index.php?PHPSESSID=lfbltdh8vo37c6313nqql4c9eqhe1aka&topic=78535.msg2030525#msg2030525

**Comment by Wikinaut** [comment]
I think, the answer is here: https://rmlint.readthedocs.io/en/v2.6.1/tutorial.html#original-detection-selection

![grafik](https://user-images.githubusercontent.com/1151915/83362638-238a2f00-a393-11ea-8b6d-58eb59317121.png)

**Comment by sahib** [comment]
I'm not sure if I understood your usecase, but this might be helpful too:

* https://rmlint.readthedocs.io/en/latest/tutorial.html#copying-unique-files

Why did you read the docs for version 2.6.1 by the way?

**Comment by Wikinaut** [comment]
@sahib: easy to explain: I intentionally studied the 2.6.1 docs, because this is the version I got by ```sudo apt install rmlint``` on LinuxMint 19.3.
