### ISSUE TITLE
rmlint does 800 getwinsize syscalls per second with -g

### ISSUE THREAD

**Issue by phiresky** [sahib/rmlint#425]
Feel free to close this if you think it's irrelevant, just noticed this while doing 

`sudo strace -e '!futex' -y -f -p $(pidof rmlint)`

I saw that rmlint is doing 800+ syscalls like this

`ioctl(1</dev/pts/13>, TIOCGWINSZ ..` per second

Guessing it's to display the progressbar - I'm not sure if it impacts perf. just thought you should know.

**Comment by sahib** [comment]
Thanks for the hint. It didn't seem to have any noticeable performance effect, but I still fixed it as of 08574bdf020c25465cfa2b03d7593226099cb203.
