### ISSUE TITLE
load json from previous run into GUI

### ISSUE THREAD

**Issue by honelnik** [sahib/rmlint#426]
Hello,

first of all thanks so much, rmlint is amazing.

Is there a way to load json from my previous scan into the GUI?
My scan ran for around 90min, so I was wondering if I can have GUI not have to spawn another rmlint and just use the data already available.

Thank you

**Comment by sahib** [comment]
Hello @honelnik,

this is currently not possible with the GUI.

You can run the command line to replay your ``.json`` file:

```bash
$ rmlint --replay rmlint.json /the/directory/you/ran
```

This will create a ``.sh`` file you can run directly:

```bash
./rmlint.sh
```

See also the documentation: https://rmlint.readthedocs.io/en/latest/tutorial.html#replaying-results

**Comment by honelnik** [comment]
Hi @sahib 

thanks for the response, I know about the replay feature, what I am asking for though is - can I visualize this replay in the gui?
Or does shredder need to scan the folders every time?

THank you
