### ISSUE TITLE
Further documentation around ownership and permissions

### ISSUE THREAD

**Issue by trixpan** [sahib/rmlint#427]
The documentation doesn't seem to make many comments about it, but it seems like "unresolved" (i.e. numeric as opposed to "username")  uid or gid may lead to a file not to be marked as a duplicate.

Further clarification would be great

**Comment by sahib** [comment]
Those are counted as "bad user id / group id". See the ``-T`` option (e.g. [in the manpage](https://rmlint.readthedocs.io/en/latest/rmlint.1.html)). If you only care for duplicates you can run:

```
rmlint -T df
```

**Comment by SeeSpotRun** [comment]
@trixpan are you happy for me to close this issue?
