### ISSUE TITLE
json_object_get_boolean_member: assertion 'node != NULL' failed when running with --replay option

### ISSUE THREAD

**Issue by nijhawank** [sahib/rmlint#432]
With rmlint --xattr --replay rmlint.json , it runs fine and even displays the duplicate report and a summary but throws the below warning at the very start of it.

INFO: Loading json-results `blah blah blah/rmlint.json'
json_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failedjson_object_get_boolean_member: assertion 'node != NULL' failed
Duplicate(s):
    ls 'blah blah blah'
    rm 'blah blah'

This is on macOS Mojave with apfs filesystem. rmlint was installed using brew.

**Comment by sahib** [comment]
2e6bfd5a85f5cbc876e938ae3dfb1c944ee0578b should make the loading more thorough. The messages likely did not have any effect on the output itself. Could it be that the ``rmlint.json`` was created by an older version of it, by chance?

Anyways, please try the changes. If it works I will close your tickets.
