### ISSUE TITLE
Fix default max size in Settings or its handling (and GUI typo)

### ISSUE THREAD

**Issue by miskovics** [sahib/rmlint#437]
`rmlint --gui` does not produce any matches with default settings, it seems the call to `rmlint` fails:

```
$ rmlint --no-with-color -T duplicates --see-symlinks --hidden -c sh:handler=remove --hardlinked --crossdev --size 1-18446744073709551615 --max-depth 512 -o json -c json:oneline /
ERROR: cannot parse --size: Max is smaller than min.
```

Reducing `Size limits` in `Settings` from `16 Petabyte` to `1 Terrabye` (typo) fixed the problem.

**Comment by sahib** [comment]
Did you try the latest ``develop``? This bug was supposedly fixed since some time. Please always mention what version you're using.

**Comment by miskovics** [comment]
I used the latest official one from Ubuntu 20.04 LTS repo, this is the version today.

```
$ rmlint --version
version 2.9.0 compiled: Dec 31 2019 at [22:27:25] "Odd Olm" (rev 2)
compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support

rmlint was written by Christopher <sahib> Pahl and Daniel <SeeSpotRun> Thomas.
The code at https://github.com/sahib/rmlint is licensed under the terms of the GPLv3.
$ 
```

**Comment by sahib** [comment]
Well, yes, that's the old version from over a year ago. 
You have to either [update from source](https://rmlint.readthedocs.io/en/latest/install.html#installation) or ask your distribution maintainers to update. 

> Reducing Size limits in Settings from 16 Petabyte to 1 Terrabye (typo) fixed the problem.

I fixed the typo, which is indeed still in the current version.
