### ISSUE TITLE
Man page typos and formatting errors

### ISSUE THREAD

**Issue by Flurrywinde** [sahib/rmlint#442]
In the Formatters section of the man page, I found a few things that seem like typos and formatting errors. Unfortunately my knowledge of roff isn't up to par, but I got my local copy working. Here's the diff:
```
721a722
> .INDENT 0.0
723,725c724
< .INDENT 2.0
< .TP
< .B \fBsh\fP: Output all found lint as shell script This formatter is activated
---
> .B \fBsh\fR: Output all found lint as shell script. This formatter is activated
727d725
< .UNINDENT
729c727
```
But warning: it's just a hack job. For example, I couldn't figure out why \fP wasn't turning off bold (\fB) like it does everywhere else, so I just used \fR. Maybe someone with better roff skills can do it right.

Thanks, BTW, for this great utility. It seems like the best dupe fixer yet.

**Comment by sahib** [comment]
Should be fixed as of 29612f93 - we do not write roff directly, but let it generate it via Sphinx.
