### ISSUE TITLE
Match based on filename and size

### ISSUE THREAD

**Issue by Telofy** [sahib/rmlint#446]
Sorry if I’m just overlooking the right flag for the job, but I’ve been reading through the man page quite a bit now, and I’m still wondering whether rmlint also supports one simple matching algorithm: Find files that share the same filename and size.

I’ve searched through the issue tracker and found a few requests for fuzzy filename matching. That’s not what I mean. I’m referring to files that have the exact same filename and the exact same size. (Some people may also want to include the modification time, but for me that wouldn’t help.)

The background is that I’m dealing with 140–400 GiB of photos, and accessing or hashing each of them would take a long time. I’m also pretty sure the algorithm would work well since the photos almost all have unique names and are all pretty big, so that they’re unlikely to coincidentally have the same size.

Thank you!

Update: `rmlint -b -PPP -Q 128K -g .` only took ~ 15 minutes. It compares only files with the same filename, uses the least “paranoid” hashing algorithm, and only considers the first 128 KiB of the files (if I understand that option correctly – maybe it’s the last 128 KiB) for the comparison.

**Comment by sahib** [comment]
Hello @Telofy,

what you want is the ``--match-basename / -b`` option. The basename is the last part in a path (so for ``/a/b/c`` it is ``c``, while the dirname is ``/a/b``). Duplicates are always matched by size before hashing, so there is no explicit option for that.

> Update: rmlint -b -PPP -Q 128K -g . only took ~ 15 minutes. It compares only files with the same filename, uses the least “paranoid” hashing algorithm, and only considers the first 128 KiB of the files (if I understand that option correctly – maybe it’s the last 128 KiB) for the comparison.

It's the first 128K. I would advise not using ``-q / -Q`` though since you might get false positives in the worst cases (diff only after 128k).

**Comment by Telofy** [comment]
Hi Sahib!

Thank you! Yes, my problem is mostly about speeding up the process as much as possible because the data is fairly special so that I can be almost sure that there won’t be any false positives (and don’t care about the extremely minor, unlikely data loss).

My hope was that I can speed up the process to the point where rmlint doesn’t need to look at the file content at all, so that it can just process the file metadata, which should be vastly faster. Something like `-Q 1` goes a bit in that direction, but it still needs to access file content once, which, because of the seek, probably already slows the process quite a bit. It also won’t consider the file size, which should be a piece of metadata that can be read very quickly. Oh yeah, my data is on a good old spinning mechanical hard drive. ^^

But ~ 15 minutes is actually fast enough for me for now. :-)

Thanks for the awesome tool!
