### ISSUE TITLE
Documentation: clarification about the -C / --xattr option

### ISSUE THREAD

**Issue by ThomVivet** [sahib/rmlint#452]
About the `-C / --xattr` option, I can read into the documentation here https://rmlint.readthedocs.io/en/latest/rmlint.1.html:
> Shortcut for --xattr-write, --xattr-write, --write-unfinished.

I suppose that instead of that we should read :
`--xattr-`**read**, ` --xattr-write`, `--write-unfinished `

Is that right ?

**Comment by vb0** [comment]
Also I think --xattr-write and --write-unfinished should (at least for now) NEVER be combined because of https://github.com/sahib/rmlint/issues/439#issuecomment-734771299

**Comment by sahib** [comment]
> I suppose that instead of that we should read :
> --xattr-read, --xattr-write, --write-unfinished

That has been already fixed in 0c6ae08118e597e0be9537b8828c2a585de26ebf. It will propagate to the docs on the next release.
