### ISSUE TITLE
Output files terminated randomly

### ISSUE THREAD

**Issue by nstephenh** [sahib/rmlint#453]
Hello! I have a large number of files that need de-duplicated, and so I ran rmlint on my files, but when I ran the removal script I noticed it terminated due to a missing quote. I've inspected both the script and json file, and they both seem to stop mid-line. Any ideas what could be causing this?

The dataset is quite large (22TB) and it found nearly 4tb of dupes over 5 days 10 hours. I'm also accessing it via smb and storing the rmlint files to the smb share as well.

Thanks

**Comment by sahib** [comment]
Hello @nstephenh,

hard to tell without knowing what version of ``rmlint`` you were using. If you're using the last version:

* Did ``rmlint`` finish at all?
* Is the connection to your SMB share stable?

> The dataset is quite large (22TB) and it found nearly 4tb of dupes over 5 days 10 hours. I'm also accessing it via smb and storing the rmlint files to the smb share as well.

Just as a note: Scanning / removing over SMB will be very slow.

**Comment by nstephenh** [comment]
I'm going to close this because it likely was something related to my connection to my share. I re-ran rmlint from a local directory (still scanning the SMB share) so the script and json files were saved to my ssd. It went a lot faster and there were no issues. Besides this, I haven't seen any other issues with my SMB share though.
