### ISSUE TITLE
MacPorts install option?

### ISSUE THREAD

**Issue by ylluminate** [sahib/rmlint#468]
Been working at purging our systems of Homebrew due to some various reasons and trouble that it causes. MacPorts has proven to be much more reliable and solid a package manager. Has anyone successfully built an `rmlint` MacPorts recipe as of yet or is this still something that needs to be done?

**Comment by SeeSpotRun** [comment]
Neither @sahib nor I are Mac users so it's going to need someone else to contribute this.

Here's the early history for Homebrew recipe: https://github.com/sahib/rmlint/issues/175

**Comment by SeeSpotRun** [comment]
Ok I now have access to a Mac development environment so may be able to make some progress on this...

**Comment by SeeSpotRun** [comment]
I have a working MacPorts recipe for rmlint command-line version, trying to get gui working now but struggling...

Are people specifically looking for gui on Mac or happy with command-line?

**Comment by SeeSpotRun** [comment]
... got there in the end!

Looking for testers for https://github.com/SeeSpotRun/ports/blob/main/sysutils/rmlint/Portfile

After cloning and setting up as local MacPorts repo,
```
$ sudo port install rmlint
```
... should install command-line version.

For gui:
```
$ sudo port install rmlint +gui
$ # (may need to log out and back in again to enable xorg-server)
$ export PYTHONPATH="/opt/local/lib/python3.9/site-packages:$PYTHONPATH"
$ shredder
```

**Comment by ylluminarious** [comment]
@SeeSpotRun Thanks for the Portfile! The CLI version appears to be working perfectly.

The GUI version, however, threw the following error when I tried to run it:

```
Traceback (most recent call last):
  File "/opt/local/bin/shredder", line 4, in <module>
    import shredder
ModuleNotFoundError: No module named 'shredder'
```

Does this have something to do with the following statement which is printed after it installs?:

```
--->  Some of the ports you installed have notes:
  xinit has the following notes:
    To use MacPorts' X11 as the default server, install xorg-server, log out, and log back in.
```

CC @ylluminate

**Comment by SeeSpotRun** [comment]
> Does this have something to do with the following statement which is printed after it installs?

No, it's probably just a PYTHONPATH issue.  I've done a fix for this but had forgotten to push back up to repo.
Meanwhile this should work:
```
$ export PYTHONPATH=$"/opt/local/lib/python3.9/site-packages:$PYTHONPATH"
$ shredder
```

**Comment by ylluminarious** [comment]
@SeeSpotRun Thanks so much! Your updates appear to be working perfectly. Now I can use both the GUI and CLI versions flawlessly. You should probably make a PR to [macports-ports](https://github.com/macports/macports-ports) and I'm sure they'll accept it quite readily.

Thanks again!

**Comment by SeeSpotRun** [comment]
Cool, will wait until next `rmlint` release (planned for June) then PR the portfile.

**Comment by ylluminate** [comment]
Thank you by the way!
