### ISSUE TITLE
rmlint.sh: empty

### ISSUE THREAD

**Issue by melnit** [sahib/rmlint#472]
Hello,

I have a habit of hording backups so it's not unusual for me to have multiple versions of the same data, usually stacked inside the largest storage device I can muster up. As you might imagine, rmlint does wonders me; I backup my backups and let it rip on the data. A little while ago, I put together a few drives, made a FreeBSD based zpool, shared a dataset via NFS to my laptop and mounted it on my Fedora 33 workstation. Althought I tried going out of my way to compile/install rmlint on any of the recent versions of FreeBSD, I had no luck and finally decided it might be better to let it run on Linux anyway. Happily, rmlint runs jut fine on my Fedora 33 but I encounter a strange error when processing my NFS share:

After running "rmlint -p -v -g (-D)" on around 850GB of mixed data, the generated rmlint.json and rmlint.sh files are empty, which means that I can not launch the cleaning operation. I normally relax all permissions and/or other restrictions before doing any such work on my data and make sure It's not being accessed by anyone/thing else. I've even tried to run rmlint with sudo but all to no avail. I've just noticed that this only happens when the rmlint.json/sh files are generated inside the OpenZFS dataset while the folders down below tend to work just fine. Both UNIX permissions as well as ACLs are fully relaxed; is there anything about the dataset I'd also have to change via "zfs set"?

Thanks a lot. I'm really getting tired of processing all this data.
Cheers!
M.

**Comment by SeeSpotRun** [comment]
By "empty" do you mean zero-length files, or just zero duplicates detected?

**Comment by SeeSpotRun** [comment]
Please re-open if further action required
