### ISSUE TITLE
`_build/man/rmlint.1` should be `_build/man/1/rmlint.1` in develop branch

### ISSUE THREAD

**Issue by Flurrywinde** [sahib/rmlint#502]
In compiling the develop branch, I got:
```
gzip_file(["docs/rmlint.1.gz"], ["docs/_build/man/rmlint.1"])
gzip: /home/kanon/code/rmlint/docs/_build/man/rmlint.1: No such file or directo
ry
Warning: could not gzip /home/kanon/code/rmlint/docs/_build/man/rmlint.1 to /ho
me/kanon/code/rmlint/docs/rmlint.1.gz: Command 'gzip -c /home/kanon/code/rmlint
/docs/_build/man/rmlint.1 > /home/kanon/code/rmlint/docs/rmlint.1.gz' returned
non-zero exit status 1.
```

**Comment by SeeSpotRun** [comment]
Hmmm, it looks like we [call gzip without actually checking if it's installed](https://github.com/sahib/rmlint/blob/e9018c47554bc4316794023fa882ce2ad226bec6/docs/SConscript#L37-L44), which leads to a not-very-helpful error message.

Please check output of
```
$ gzip -V
```

**Comment by Flurrywinde** [comment]
gzip -V produces `gzip 1.10`. As for the `.../1/...`, IIRC, when I saw, `gzip: /home/kanon/code/rmlint/docs/_build/man/rmlint.1: No such file or directory`, I did a search for rmlint.1, and I found it here: `/home/kanon/code/rmlint/docs/_build/man/1/rmlint.1`. It must get there somehow.

So then I edited the command in the warning and did ran it myself from the command line: `gzip -c /home/kanon/code/rmlint/docs/_build/man/1/rmlint.1 > /home/kanon/code/rmlint/docs/rmlint.1.gz`.

**Comment by SeeSpotRun** [comment]
Ok that's odd.  Looks like I have some reading up to do on `scons` and its handling of environment variables.  I suspect that there is some environment-based expansion (maybe [here](https://github.com/SCons/scons/blob/cf62ab0371a135d137e5dfd9a3c3e5ab2d0168a1/SCons/Action.py#L454-L455)?)

... of the string `'_build/man/rmlint.1'` passed here: https://github.com/sahib/rmlint/blob/e9018c47554bc4316794023fa882ce2ad226bec6/docs/SConscript#L54-L57

... but for some reason the same expansion is not applied here: https://github.com/sahib/rmlint/blob/e9018c47554bc4316794023fa882ce2ad226bec6/docs/SConscript#L59-L61

Can you think of anything in your setup (what distro are you running) that might help explain why this manifests for you and not for others?

**Comment by SeeSpotRun** [comment]
... maybe something to do with `MANPATH` or `/etc/man_db.conf`?

**Comment by SeeSpotRun** [comment]
Please try from https://github.com/SeeSpotRun/rmlint/tree/fix/manpage_path

This should use same path mapping for both sphinx and gzip.

**Comment by SeeSpotRun** [comment]
Ah wait, it looks like it's a new sphinx 'feature' introduced here: https://github.com/sphinx-doc/sphinx/commit/178c05b0597e144fdc2117c7b46ac15723a290e8

So `sphinx` is now inserting `/1/` in the path but `scons` doesn't know about this.  Have turned this off via https://github.com/SeeSpotRun/rmlint/commit/491ea0cf25ddbe4147ed49359aa1a4d9bf2d5381

**Comment by Flurrywinde** [comment]
Confirmed: running `scons` on the current develop branch produces the error, but running it with `491ea0c` checked out works fine. All is well.
