### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by shaansharma1980** [sahib/rmlint#517]
On Ubuntu 20.04 > `**sudo apt install rmlint -y**` doesn't show any package by that name, is there a PPA for Ubuntu 16.04 as well as I'm finding it difficult to install glib-2.0 due to dependency issues with other packages ?

**Comment by SeeSpotRun** [comment]
Re 20.04, should be there according to https://packages.ubuntu.com/focal/rmlint

Re 16.04, that's pretty much [EOL](https://ubuntu.com/about/release-cycle) so sorry I don't have much appetite to try to find a glib-2.0 workaround.
