### ISSUE TITLE
Preprocessing seems stuck - debugging tips?

### ISSUE THREAD

**Issue by james-cook** [sahib/rmlint#561]
In my current run  preprocessng seems to get stuck.

The HDD is working away. No spin down. But the numbers in the preprocessing line do not change, even after many hours.
This happens with master and with develop + some patches.

The original command:
`rmlint --progress --xattr --keep-all-tagged --must-match-tagged '/srv/dev-disk-by-label-OMV2/shd2/from.ext.hdd.M-family.TOSH_SOURCE-HDD_ORPHANS/from.ext.hdd.F' // '/srv/dev-disk-by-label-OMV2/shd2/from.ext.hdd.F'`

The first dir is "new" and contains no hardlinks of any kind (internal to the directory or outside the directory). I more or less assume that all files in dir1 are inside dir2 - I am using rmlint to check this for sure.
The second dir is the product of many `rmlint -c sh:hardlink` runs and contains many repeated inodes.

Preprocess output gets "stuck" here:
```
?¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦?          Traversing (2434375 usable files / 10873 + 5196 ignored files / folders)
... reduces files to 1614949 / found 47955 other lint)

```
Thinking there might be a very large file on which rmlint is taking so much time I limited the max file size to 2GB with `-s -2GB `in the command line. This doesn't change much, rmlint is stuck preprocessing at:
```
?¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦?          Traversing (2434336 usable files / 10873 + 5196 ignored files / folders)
... reduces files to 1614915 / found 47955 other lint)

```
I am now running the same job overnight with -vvv instead of --progress to see what emerges.

Any tips on how to find if and why preprocessing may be stuck in a loop e.g. Debug line in **preprocess.c**?

**Comment by Cebtenzzre** [comment]
A backtrace would be helpful to see what step it's actually on. Otherwise I'd just be making guesses.
