### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alexrtou** [sahib/rmlint#583]
Hello,
This is not an issue but a question. 

I can't find a way to directly open the output file in the GUI to chose the manually which version I want to keep :

The whole search takes about 45 minutes... and I have 11Go to check manually... I'll need to work on the result in batches :)
Maybe, is there an other way to do that ?

Thanks in advance

**Comment by Cebtenzzre** [comment]
As far as I know, there is currently no way to save and resume a session in the GUI - is that what you are trying to do? The command-line version has a --rank-by option if you have simple criteria in mind for which files to keep. Reflinking and hardlinking are worth considering if you would like to save disk space without removing any files. And you can always edit the generated script by hand. 

You can leave this issue open if you think the GUI can be improved.

**Comment by alexrtou** [comment]
Hello,
Thanks, I read the entire documentation... And I saw that.
I have started to list the original directories, I am going to tune the search as much as possible.
Because I have too many lines to check in a standard editor (~17000 command lines).
