### ISSUE TITLE
Long Task Heartbeat Spinner

### ISSUE THREAD

**Issue by aaronxn** [sahib/rmlint#588]
A simple request: 

if the job lasts longer than 30s display a spinner or other "I'm alive" indicator. 

Great tool, love it!

**Comment by Cebtenzzre** [comment]
Could you clarify whether you're referring to the CLI program or the shredder GUI, and which job is not displaying a status indicator? The CLI has a --progress option for scanning, the generated scripts have verbose logging by default, and the GUI uses spinners for many tasks.

**Comment by Cebtenzzre** [comment]
Closing due to lack of response. Please reopen if you would like to provide additional information.
