### ISSUE TITLE
generated rmlint.sh script dry-run (-n) is incompatible with paranoid (-p) for directories

### ISSUE THREAD

**Issue by brianrmurphy** [sahib/rmlint#610]
Running the generated script "./rmlint.sh -n -p" runs "rmlint --equal" to compare directories but running "rmlint --equal" overwrites rmlint.sh and rmlint.json.

I think the latter behavior (overwriting rmlint.sh and rmlint.json when you run rmlint --equal) is the real bug, since it contradicts the man page, but the problem shows up here.

**Comment by Cebtenzzre** [comment]
This is a duplicate of issue #552.
