### ISSUE TITLE
Change formater after the fact

### ISSUE THREAD

**Issue by Som-anon** [sahib/rmlint#635]
Is there a way to change formater after generating the rmlint.sh file?
If you forgot to specify sh:reflink or something in the beginning is it still possible to invoke it later without having to rescan everything?
Is it maybe even possible to create reflink copies after deleting the duplicates by mistake? In theorey I could modify remove_cmd or create a script that modifies the rmlint.sh file, but I hoped that it would be easier somehow

**Comment by cebtenzzre** [comment]
rmlint by default will generate a .json file as well as the .sh script, which you can use with --replay mode to specify any action you would like, e.g. `rmlint --replay rmlint.json <orig_path> -c sh:link` (replace <orig_path> with the path or paths you passed to the original rmlint command). It will generate a file called rmlint.replay.sh by default.
