### ISSUE TITLE
Alive?  Maintained?

### ISSUE THREAD

**Issue by StatusCode404** [sahib/rmlint#638]
Just checking if rmlint is still alive and still actively being maintained?  No pulse since Aug.

Is it still reliable with the latest btrfs versions in latest kernels?

**Comment by cebtenzzre** [comment]
Sorry, I do read the issues. But between my day job and my other open-source obligations (llama.cpp as of the last few months), there's not much time left for rmlint. And it's a relatively straightforward program that still works fine on btrfs when I do use it.

If you stay away from --xattr and fancy use of --replay (with additional options), you probably won't run into any bugs. Those are the only options that I think are poorly implemented at the moment.

**Comment by StatusCode404** [comment]
Thanks for the response!
