### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\g'

### ISSUE THREAD

**Issue by rajkamerkar** [sahib/rmlint#656]
i am newly trying to use the kohya with zero knowledge of coding i tried to install and run the kohya seeing some tutorials but facing this issue when i run this command ".\setup.bat" would be a great help !! thanks in advance 

C:\Users\kamer\kohya\kohya_ss\setup\setup_windows.py:251: SyntaxWarning: invalid escape sequence '\g'
  "start cmd /k .\gui.bat --inbrowser", shell=True
Traceback (most recent call last):
  File "C:\Users\kamer\kohya\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "C:\Users\kamer\kohya\kohya_ss\setup\setup_common.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by cebtenzzre** [comment]
This is the rmlint repository. I think you're looking for https://github.com/bmaltais/kohya_ss
