### ISSUE TITLE
Implement --xattr-clear, --xattr-writ and --xattr-read

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#91]
We can optionally make use of extended fille attributes. For example we can store the checksum of finished files and write them to the xattr's of that file.

As key one could use something like this:

    user.rmlint.$checksum_type.cksum

where ```$checksum_type``` is replaced by e.g. ```sha256```.

The options would do the following:

* ```--xattr-read:``` Read checksum from file. By default this pulls in ```-q 45% -Q 55%``` to read some bytes in the middle (they're back, yay! :smile:) in order to compensate outdated checksums.
* ```--xattr-write:``` Write finished checksums to attributes.
* ```--xattr-clear:``` Make rmlint not search any dupes, just traverse and clear all traversed files from rmlints special attributes

Potential idea would be also to save a timestamp inside the file attributes. By default rmlint would ignore timestamps older than 1 hour or something to minimize the risk of old checksums.
If older, the attributes will be cleared again.

Not all filesystems support this, also this is linux specific and potentially dangerous.
Benefit is basically a natural way for other applications to read the checksums rmlint calculated (in addition to the json output). Also this would implement a caching layer for large datasets.

*Potential problems:*

* This is probably hard to implement for ```-a paranoid```.
* Not all filesystems support this; needs checks from scons for ``setxattr(2), getxattr(2) and removexattr(2)```. 
* Gracefully support filesystems that do not support this. I.e. do not spam the terminal with messages, but complain at least once.

Idea is shamelessly stolen from: https://bitbucket.org/maugier/shatag

**Comment by sahib** [comment]
Implemented mostly.

Also implemented a more general ```--cache``` param that can load rmlint's own json files as a caching layer, since this is basically the same codepath. For this, json-glib is used which is a new external dependency (although it's a pretty common, well distributed library).

One possible improvement would be making partial cache matches work. Currently, if not all checksums for a particular size group can be loaded from the cache, it is processed manually. This is needed, since we do iterative hashing and need the "checksums in between" we cannot just hash one missing file with the current code (does not make much sense anyways). What might be possible though: If only one file in a RmShredGroup is not loadable from the cache, but gets sorted out early, we can stop hashing for the rest. 

The current code is not capable of doing this and Im not sure what would be a clean way of doing this would look like with the current shredder. Maybe the shredder expert @SeeSpotRun can look into this. :smile:

**Comment by SeeSpotRun** [comment]
I think we can use the same approach (and therefore code) as shredder currently does for hardlinks:
* When there is a cluster of files with pre-matched hashes, all except one are rolled up into a GQueue which is attached to the "master" of that cluster as RmFile->prematch_queue
* Any hardlinks of any files in the master file's file->prematch_queue also get added to that queue
* The master RmFile is passed to shredder.
* At the end of shredding, the files in ->prematch_queue are unpacked and added to the RmShredGroup.

So for example if we had had files with the following filename:content(pre-hash):
f1:aaa(h1)
f2:aaa(h1)
f3:aaa(h1)
f4:aab(-)
f5:aba(-)
f6:aaa(-)
f7:aaa(-) has no pre-hash but is hardlinked to f2
Then:
* f2 and f3 would be attached to f1->prematch_queue based on pre-hash
* f7 would be attached to f1->prematch_queue based on pre-hash
* shredder compares start of files =>  f1:a == f4:a == f5:a == f6:a
* shredder compares middle of files =>  f1:aa == f4:aa == f6:aa != f5:ab (so f5 gets dumped)
* shredder compares end of files =>  f1:aaa == f6:aaa != f4:aab (so f4 gets dumped)
* f1->prematch_queue gets unbundled, so final group contains {f1, f2, f3, f6, f7} and these get sent to the output handler.

So I think the only code changes will be a rename of RmFile->hardlinks to RmFile->prematch_queue, and some changes in preprocess.c to detect and bundle the pre-hashes.

**Comment by sahib** [comment]
Sounds like a much nicher idea, but will this work when you have only two files, one pre-hashed one not? What will the unhashed one compare to? The pre-hashed one will be read fully and compared to the unhashed one if I understand correctly? (just asking, I would be okay with that.)

Also consider that it's possible to save the unfinished hashes of files using ```--write-unfinished / -U``` - they're written out to json with a type of ```unfinished_cksum``` then.

**Comment by SeeSpotRun** [comment]
Yes the above approach would re-hash one file out of each hash cluster.  So it's not very efficient in the case of one pre-hashed file and one unhashed duplicate.
The most efficient strategy in that particular case would probably be:
* Compare start of the two files;
* If the starts match then hash the file that wasn't pre-hashed and compare is to the pre-hashed one.

The optimum strategy would be slightly different depending on the number of unhashed files, eg if we had 50 unhashed files and one or more pre-hashed then probably a few more increments make sense before jumping to 100%.  The extra cost to shred 51 files vs 50 is small, and by shredding there is a chance that we can avoid fully hashing some of the 50 files if they differ somewhere in the middle.

So we can just modify rm_shred_get_read_size() to check if the RmShredGroup contains a pre-hashed file, and if yes put in some logic to decide when it becomes "cost-effective" to read the whole file.  Somewhere around https://github.com/sahib/rmlint/blob/develop/lib/shredder.c#L562-L565

Regarding storing and using partial hashes, I think it's over-complicating things and would prefer not to go there.

And with paranoid hashing I think we just ignore the pre-hash results altogether.

**Comment by sahib** [comment]
I would totally be okay with the above approach. I was just asking to see if I understood that correctly. Having partially unhashed files should be the very exception anyways, since the usecase for ```--cache``` are just fast re-runs of rmlint of large datasets. We don't expect much change between individual runs. And if there was some change, hashing one extra file won't kill us. 

Regarding paranoid hashes: I would be okay with that too. Another approach would be to use ```digest->shadow_hash``` for the preprocessed filtering. ```digest->shadow_hash``` is basically a spooky hash that gets calculated along the paranoid checksum so we can present a nice compact hash in the output.

**Comment by SeeSpotRun** [comment]
I keep getting the shakes whenever I try to make a start on this.  In principle it's quite simple but it has to handle tricky cases like:
* hardlinked files with different ext_cksum (abort!)
* two different hardlink clusters, which contains one or more file with matching ext_cksums.

Now to make things worse, it's occurred to me that we might also want to check for existing reflinks.  Oy vey!

**Comment by sahib** [comment]
Uh, do we want to check for existing reflinks? :stuck_out_tongue: 
What exactly do you mean by that anyways? 
Check if the file is reflinked always? What would be so bad about removing it and reflinking it again? 

Regarding hardlinks: Why would we want to handle this? There is a warning in the manpage that the external checksums passed to rmlint could be possibly wrong (modified by external source e.g.) - generally we cannot do much against that without rehashing the whole thing. It's true that we could issue a warning for the hardlink case, but I begin to think that it would be the best to leave the current implementation in develop which should support the supposed usecase of ``--cache`` just fine.

**Comment by sahib** [comment]
Should be fixed as of:

https://github.com/sahib/rmlint/commit/6b3b80b6ef226673a93e03645c727e397577c0af

**Comment by SeeSpotRun** [comment]
Ok working version of the new shredder preprocessing method is written.  It should now only ever hash one file out of any cluster of files with matching ext_cksums.
There is room to add back in the logic for the cases when a group has only ext_cksums, ie no files need hashing.

**Comment by sahib** [comment]
Seems to loop infinite on test_merge_directories.test_hardlinks. Even without -D.

**Comment by sahib** [comment]
The original feature is long implemented and the optimization discussed above has been impractical to implement. Closing therefore.
