### ISSUE TITLE
Use GLib's GOptionEntry API; get rid of getopt.

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#92]
Documentation:

https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html

Benefits:

- Nicer code. 
- Long options without short equivalent.
- Same option parsing on every platform.

Disadvantes:

- Lots of testing to stay compatible.
- No natural notion of specifiying a flag more than once.
  ```-vvv`` can be implemented as ```-v``` with the optional argument ```vv`` though.
  Same for ```-ppp```.

**Comment by sahib** [comment]
Im working on that. Half way through.

**Comment by SeeSpotRun** [comment]
https://github.com/sahib/rmlint/commit/3feb029a09dd2dec02ecd49cc5a0d392125cb769 214 additions and 457 deletions - nice work!

**Comment by sahib** [comment]
Done. @SeeSpotRun: it's not shorter in total though, but much more readable now. 

Testing welcome.
