### ISSUE TITLE
Support cp --reflink for filesystem that support it.

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#93]
Similar to ```-c sh:use_ln``` (replace file by hardlink) a ```-c sh:use_reflink``` can be provided that replaces the duplicate file by a CopyOnWrite version of the original. 

*Potential problems:*

* How to properly handle systems that do not support this?
* Are the copies recognized as duplicates afterwards again?

@SeeSpotRun wanted to implement this.

**Comment by sahib** [comment]
@SeeSpotRun: I merged your changes from your reflink branch (because it would have created merge conflicts in case of later merge). Afterwards I tried to tidy up the sh formatter. It works like this now:

-  There is a proper sh-template now with bash-functions:
    https://github.com/sahib/rmlint/blob/develop/lib/formats/sh.sh
- with ```-c sh:link``` he tries to emit reflink commands first, symlink afterwards and if that doesn't work, hardlinks are used.
- The order in which those occur/tried can be altered with ```-c sh:order```.
- A user defined command can be given with ```-c sh:cmd```. It is pasted in the template and 
  the ```user_command``` func is called in this case.

See here for details:

https://github.com/sahib/rmlint/blob/develop/lib/formats/sh.c.in

Testing and documentation still needed.

**Comment by sahib** [comment]
Implemented in ```develop```; closing.

**Comment by SeeSpotRun** [comment]
I'm going to come back to the another time to add a test to see if the files are already reflinked.  Unfortunately there is no direct way to identify this with btrfs; it can be done by comparing fiemap offsets.  Fortunately we already have the fiemap offset data!
