### ISSUE TITLE
badids does not disable with -L

### ISSUE THREAD

**Issue by heinowalther** [sahib/rmlint#95]
root@download:/Newz/scripts# rmlint -L

Bad UID(s):
chown root /Newz/scripts/dupe6.txt
chown root /Newz/scripts/dupe5.txt
chown root /Newz/scripts/dupe4.txt
chown root /Newz/scripts/dupe3.txt
chown root /Newz/scripts/script.pl

....
....
....

==> In total 136 files, whereof 0 are duplicates in 0 groups.
==> This equals 0 B of duplicates which could be removed.
==> 134 other suspicious item(s) found, which may vary in size.

-------------------------------------------------------------------------------
Sadly no checkking is done on the files with bad UID...  (they can be read just fine with the user executing rmlint...)  only think which helped was to do the chown on the files...

root@download:/Newz/scripts# rmlint --version
version 2.0.0 compiled: Jan  7 2015 at [17:01:25] "Personable Pidgeon" (rev 4a9ff20)
compiled with: +mounts +nonstripped +fiemap -sha512 +bigfiles +intl

/Heino

**Comment by sahib** [comment]
Hi,

```-L``` means ```--no-hardlinked``` which is the default. 
You probably want ```-T defaults,-badids```.

Ah, I see you included your version; ignore that part in my mail then.

**Comment by heinowalther** [comment]
Sorry I think I have mistaken the docs...I'll quickly close this again :-)
