### ISSUE TITLE
Use different standard hashing algorithm. 

### ISSUE THREAD

**Issue by sahib** [sahib/rmlint#99]
Im thinking about changing the standard hashing algorithm to ```sha1```. 

Reasoning: 

- It's only slightly slower (see below).
- It may be considered more secure by many people.
- It would give -P (--less-paranoid) a bit more sense.

Here are some averaged out runs on average data sets with cleared fs cache:

* (current default, *spooky128*): 32% cpu 1:39.02s (2nd run: 95% cpu 14,927)
* *md5:* 34% 1:42.18s
* *sha1:* 36% cpu 1:44.87s (2nd run: 95% cpu 19.212s)
* *sha256:* 40% cpu 1:52.45s
* *sha512:* 40% cpu 1:50.23s

All find the same number of duplicates btw. (phew)

**Comment by SeeSpotRun** [comment]
ok happy with that, I can always use -P to spare my poor cpu's anyways

**Comment by sahib** [comment]
Done as of b2c81bccab7d6ddb4b67fa4f92ef20cdc4547b05. Default is *sha1* now. 

- *pp* is now the paranoid mode.
- *p* uses **sha512*.
- *P* uses the bastard hash (out of city/spooky)
- *PP* uses plain old spooky.
